/* V24 · Gear workspace: personal readiness, shared allocation, kits, team overview. */
(function(){
  const VER=1;
  const STATUS={ready:['Готово','ok'],check:['Проверить','warn'],borrow:['Нужно одолжить','risk'],missing:['Нет / не готово','risk'],unset:['Не отмечено','']};
  const PRIORITY={required:'Обязательно',weather:'По погоде',recommended:'Рекомендуется'};
  const CATS={
    pack:['Рюкзак и упаковка','Защита вещей от влаги и нормальная укладка.'],
    clothing:['Одежда и обувь','По погоде; обувь должна быть разношенной.'],
    food:['Вода и питание','Запас на плановый маршрут и небольшой резерв.'],
    light:['Свет и инструмент','Свет и минимум для бытовых полевых задач.'],
    nav:['Навигация и связь','Офлайн-маршрут, питание электроники и резерв.'],
    health:['Аптечка и здоровье','Личные лекарства и средства для мелких проблем.'],
    hygiene:['Гигиена','Минимальный набор без лишнего веса.'],
    docs:['Документы','Документы, деньги и офлайн-контакты группы.']
  };
  const PERSONAL=[
    ['pg0','Рюкзак','pack','required','Под объём конкретного похода.'],
    ['pg8','Чехол от дождя на рюкзак','pack','weather','Нужен при вероятности осадков.'],
    ['pg9','Гермомешок / плотные пакеты','pack','recommended','Для сухой одежды и электроники.'],
    ['pg19','Пакет для мусора','pack','required','Мусор с маршрута уносим с собой.'],
    ['pg10','Походная обувь','clothing','required','Разношенная и подходящая под покрытие.'],
    ['pg6','Запасные носки / сухой слой','clothing','required','Минимум один сухой комплект.'],
    ['pg11','Утепляющий слой','clothing','weather','Флис / кофта по температуре.'],
    ['pg2','Дождевик / мембранная куртка','clothing','weather','Сверить с прогнозом.'],
    ['pg12','Головной убор','clothing','weather','По сезону.'],
    ['pg1','Питьевая вода','food','required','Объём зависит от маршрута и погоды.'],
    ['pg13','Личный перекус','food','required','То, что удобно есть без готовки.'],
    ['pg3','Налобный фонарь','light','required','Проверить включение и заряд.'],
    ['pg7','Телефон + офлайн-карта / трек','nav','required','Маршрут должен открываться без связи.'],
    ['pg4','Power bank + кабель','nav','recommended','Полностью зарядить перед выходом.'],
    ['pg5','Личные лекарства','health','required','Общая аптечка не заменяет личные лекарства.'],
    ['pg24','Личная мини-аптечка / пластыри','health','recommended','Для небольших повреждений и мозолей.'],
    ['pg16','Репеллент / средство от клещей','health','weather','По сезону.'],
    ['pg17','Салфетки + антисептик','hygiene','recommended','Упаковать от влаги.'],
    ['pg18','Документ / карта / наличные','docs','recommended','По необходимости поездки; контакты сохранить офлайн.']
  ].map(([id,title,category,priority,help])=>({id,title,category,priority,help}));
  const FINAL=[
    ['weather','Проверить прогноз','За 1–2 дня и утром перед выходом.'],['shoes','Проверить обувь и одежду','Не брать новую непроверенную обувь.'],
    ['charge','Зарядить телефон и power bank','Проверить кабель.'],['offline','Скачать офлайн-карту и маршрут','Открыть один раз без сети.'],
    ['lamp','Проверить фонарь','Включение и заряд.'],['water','Проверить воду и еду','Хватит ли на весь участок.'],
    ['meds','Проверить личные лекарства','Постоянно принимаемые должны быть с собой.'],['shared','Сверить общее имущество','Не забыть распределённое и не дублировать лишнее.']
  ].map(([id,title,hint])=>({id,title,hint}));
  const FIRST_AID=['Стерильные салфетки / марля','Бинт','Эластичный бинт','Пластыри разных размеров','Пластыри / тейп от мозолей','Медицинский тейп','Одноразовые перчатки','Средство для обработки небольших повреждений','Ножницы','Пинцет','Термоодеяло','Краткая памятка первой помощи'].map((title,i)=>({id:'fa'+i,title}));
  const REPAIR=['Армированный скотч / тейп','Пластиковые стяжки','Шнур / паракорд','Иголка и прочная нить','Небольшая запасная фурнитура'].map((title,i)=>({id:'rp'+i,title}));
  const DEFAULT_META={
    g0:{cat:'health',unit:'шт.',desc:'Базовый групповой комплект. Проверяет ответственный за первую помощь.',kit:FIRST_AID,note:'Базовая шпаргалка по комплектности, не индивидуальное медицинское назначение.'},
    g1:{cat:'nav',unit:'шт.',desc:'Резерв навигации, распределённый между участниками.'},g2:{cat:'nav',unit:'шт.',desc:'Бумажная карта / атлас как резерв электронного трека.'},
    g3:{cat:'nav',unit:'шт.',desc:'Резерв питания навигации и связи.'},g4:{cat:'light',unit:'компл.',desc:'Небольшой полевой ремнабор.',kit:REPAIR,note:'Состав адаптируется под конкретное снаряжение.'},
    g5:{cat:'pack',unit:'шт.',desc:'Общее дождевое укрытие, если требуется по погоде или задаче.'}
  };
  const SHARED_CATS={health:'Медицина',nav:'Навигация и связь',light:'Ремонт и инструмент',pack:'Укрытие и быт',food:'Вода и питание',other:'Прочее'};
  const PRESETS={custom:['Своя позиция',1,'шт.','other',''],radios:['Рации',4,'шт.','nav','Если используются группой; проверить заряд и распределение.'],trash:['Пакеты для общего мусора',2,'шт.','pack','Распределить между участниками.'],water:['Общая вода',6,'л','food','Только если общий запас нужен по маршруту.'],kitchen:['Кухонный комплект',1,'компл.','food','Подключать, если планируется готовка.']};
  let mode='personal';

  const G=()=>ensure();
  function organizer(){const lead=S.roles.find(r=>r.title==='Руководитель')?.p,gear=S.roles.find(r=>r.title==='Снаряжение')?.p;return S.current===lead||S.current===gear||S.current==='p1'}
  function ensure(){
    if(!S.gearV30||S.gearV30.version!==VER){const old=S.checks||{};S.gearV30={version:VER,status:{},final:{},kits:{},meta:{}};(S.participants||[]).forEach(p=>{const checked=new Set(old[p.id]||[]);S.gearV30.status[p.id]={};PERSONAL.forEach(i=>S.gearV30.status[p.id][i.id]=checked.has(i.id)?'ready':'unset');S.gearV30.final[p.id]={}})}
    const g=S.gearV30;g.status||={};g.final||={};g.kits||={};g.meta||={};
    const oldItems=new Map((S.personal||[]).map(i=>[i.id,i]));S.personal=PERSONAL.map(i=>({...oldItems.get(i.id),...i}));
    (S.participants||[]).forEach(p=>{g.status[p.id]||={};g.final[p.id]||={};PERSONAL.forEach(i=>{if(!STATUS[g.status[p.id][i.id]])g.status[p.id][i.id]='unset'});FINAL.forEach(i=>{if(typeof g.final[p.id][i.id]!=='boolean')g.final[p.id][i.id]=false})});
    (S.shared||[]).forEach(x=>{g.meta[x.id]={...(DEFAULT_META[x.id]||{}),...(g.meta[x.id]||{})};x.a=Array.isArray(x.a)?x.a:[];x.confirmed=Array.isArray(x.confirmed)?x.confirmed:[];const kit=g.meta[x.id].kit||[];if(kit.length){g.kits[x.id]||={};kit.forEach(i=>{if(typeof g.kits[x.id][i.id]!=='boolean')g.kits[x.id][i.id]=false})}});
    sync(false);return g;
  }
  function sync(write=true){if(!S.gearV30)return;S.checks||={};S.participants.forEach(p=>S.checks[p.id]=PERSONAL.filter(i=>S.gearV30.status[p.id]?.[i.id]==='ready').map(i=>i.id));if(write)save()}
  function pstat(pid){const st=G().status[pid]||{},ready=PERSONAL.filter(i=>st[i.id]==='ready').length,req=PERSONAL.filter(i=>i.priority==='required'),reqOpen=req.filter(i=>st[i.id]!=='ready').length,check=PERSONAL.filter(i=>st[i.id]==='check').length,help=PERSONAL.filter(i=>['borrow','missing'].includes(st[i.id])).length;return{ready,total:PERSONAL.length,pct:Math.round(ready/PERSONAL.length*100),reqOpen,check,help}}
  function fstat(pid){const f=G().final[pid]||{},done=FINAL.filter(i=>f[i.id]).length;return{done,total:FINAL.length,pct:Math.round(done/FINAL.length*100)}}
  function aq(x){return x.a.reduce((n,a)=>n+(+a[1]||0),0)}function cq(x){return x.a.reduce((n,a)=>n+(x.confirmed.includes(a[0])?(+a[1]||0):0),0)}function mine(x){return +(x.a.find(a=>a[0]===S.current)?.[1]||0)}
  function kstat(x){const kit=G().meta[x.id]?.kit||[],c=G().kits[x.id]||{},done=kit.filter(i=>c[i.id]).length;return{done,total:kit.length}}
  function sstate(x){const need=+x.need||0,k=kstat(x);if(aq(x)<need)return[aq(x)?`Не хватает ${need-aq(x)}`:'Не назначено','risk'];if(cq(x)<need)return['Нужно подтвердить','warn'];if(k.total&&k.done<k.total)return['Проверить комплект','warn'];return['Готово','ok']}
  function totals(){const l=S.shared||[];return{all:l.length,ok:l.filter(x=>sstate(x)[1]==='ok').length,def:l.filter(x=>aq(x)<(+x.need||0)).length,conf:l.filter(x=>aq(x)>=(+x.need||0)&&cq(x)<(+x.need||0)).length}}
  function metric(a,b,c,t=''){return `<div class="g30-metric ${t}"><small>${esc(a)}</small><strong>${esc(b)}</strong><span>${esc(c)}</span></div>`}
  function tabs(){const a=[['personal','Моё снаряжение'],['shared','Общее']];if(organizer())a.push(['team','Команда']);return `<div class="g30-tabs">${a.map(([k,v])=>`<button data-g30-mode="${k}" class="${mode===k?'active':''}">${v}</button>`).join('')}</div>`}
  function pri(i){return `<span class="g30-priority ${i.priority}">${PRIORITY[i.priority]}</span>`}
  function opts(v){return Object.entries(STATUS).map(([k,m])=>`<option value="${k}" ${k===v?'selected':''}>${m[0]}</option>`).join('')}

  function personal(){const s=pstat(S.current),st=G().status[S.current]||{};return `<div class="g30-summary">${metric('Готовность',`${s.ready}/${s.total}`,`${s.pct}% списка`,s.reqOpen?'':'ok')}${metric('Обязательное',s.reqOpen?`${s.reqOpen} не закрыто`:'всё закрыто','главный контроль',s.reqOpen?'risk':'ok')}${metric('Проверить',s.check,'заряд / состояние',s.check?'warn':'')}${metric('Нужна помощь',s.help,'нет вещи / одолжить',s.help?'risk':'')}</div><section class="g30-panel"><div class="g30-person"><div class="avatar">${initials(pn(S.current))}</div><div><small>МОЯ ПОДГОТОВКА</small><b>${esc(pn(S.current))}</b><span>Однодневный поход / тренировка · ночёвка не включена</span></div><strong>${s.pct}%</strong></div>${Object.entries(CATS).map(([cat,m])=>{const items=PERSONAL.filter(i=>i.category===cat),ready=items.filter(i=>st[i.id]==='ready').length,issues=items.filter(i=>['check','borrow','missing'].includes(st[i.id])||(i.priority==='required'&&st[i.id]!=='ready')).length;return `<details class="g30-cat" ${issues?'open':''}><summary><span><b>${m[0]}</b><small>${m[1]}</small></span><em>${ready}/${items.length}${issues?` · ${issues} требуют внимания`:''}</em></summary><div>${items.map(i=>{const v=st[i.id]||'unset',tone=STATUS[v][1];return `<div class="g30-item ${tone}"><span><b>${esc(i.title)}</b>${pri(i)}<small>${esc(i.help)}</small></span><select class="${tone}" data-g30-status="${i.id}">${opts(v)}</select></div>`}).join('')}</div></details>`}).join('')}</section>${finalBlock()}`}
  function finalBlock(){const f=G().final[S.current],s=fstat(S.current);return `<section class="g30-panel"><div class="g30-head"><div><div class="page-kicker">Перед выходом</div><h2>Финальная проверка</h2><p>Действия для конкретного мероприятия, а не постоянное состояние вещей.</p></div><b>${s.done}/${s.total}</b></div><div class="g30-final">${FINAL.map(i=>`<button class="${f[i.id]?'done':''}" data-g30-final="${i.id}"><i>${f[i.id]?'✓':''}</i><span><b>${i.title}</b><small>${i.hint}</small></span></button>`).join('')}</div></section>`}

  function owners(x){return x.a.length?`<div class="g30-owners">${x.a.map(a=>`<span class="${x.confirmed.includes(a[0])?'ok':''}"><b>${esc(pn(a[0]))}</b> · ${a[1]} ${esc(G().meta[x.id]?.unit||'шт.')}${x.confirmed.includes(a[0])?' ✓':''}</span>`).join('')}</div>`:'<small class="g30-muted">Никто не взял</small>'}
  function kit(x){const m=G().meta[x.id]||{},arr=m.kit||[];if(!arr.length)return'';const k=kstat(x),can=mine(x)>0||organizer();return `<details class="g30-kit"><summary><span><b>Состав комплекта</b><small>${esc(m.note||'Проверить комплектность перед выходом.')}</small></span><em>${k.done}/${k.total}</em></summary><div>${arr.map(i=>`<button ${can?'':'disabled'} class="${G().kits[x.id]?.[i.id]?'done':''}" data-g30-kit="${x.id}:${i.id}"><i>${G().kits[x.id]?.[i.id]?'✓':''}</i>${esc(i.title)}</button>`).join('')}</div></details>`}
  function actions(x){const n=mine(x),full=aq(x)>=(+x.need||0),confirmed=x.confirmed.includes(S.current),u=G().meta[x.id]?.unit||'шт.';if(n)return `<div class="g30-actions"><span class="g30-step"><button data-g30-qty="${x.id}:-1">−</button><b>${n} ${esc(u)}</b><button data-g30-qty="${x.id}:1" ${full?'disabled':''}>+</button></span><button class="btn ${confirmed?'alt':'sand'} sm" data-g30-confirm="${x.id}">${confirmed?'Подтверждено ✓':'Подтвердить'}</button></div>`;return full?'<small class="g30-muted">Потребность распределена</small>':`<button class="btn sand sm" data-g30-take="${x.id}">Возьму 1 ${esc(u)}</button>`}
  function shared(){const t=totals(),grouped={};S.shared.forEach(x=>{const c=G().meta[x.id]?.cat||'other';(grouped[c]||=[]).push(x)});return `<div class="g30-summary">${metric('Позиций',t.all,'общее имущество')}${metric('Готово',`${t.ok}/${t.all}`,'распределено и проверено',t.ok===t.all?'ok':'')}${metric('Дефицит',t.def,'не хватает количества',t.def?'risk':'ok')}${metric('Подтверждение',t.conf,'назначено, но не подтверждено',t.conf?'warn':'')}</div><section class="g30-panel"><div class="g30-head"><div><div class="page-kicker">Команда</div><h2>Общее имущество</h2><p>Количество распределяется между людьми; назначение и подтверждение разделены.</p></div>${organizer()?'<button class="btn sand" id="g30Add">+ Добавить</button>':''}</div>${Object.entries(grouped).map(([c,list])=>`<div class="g30-group"><div class="g30-group-title"><b>${esc(SHARED_CATS[c]||'Прочее')}</b><span>${list.filter(x=>sstate(x)[1]==='ok').length}/${list.length} готово</span></div>${list.map(x=>{const m=G().meta[x.id]||{},ss=sstate(x),u=m.unit||'шт.';return `<article class="g30-shared ${ss[1]}"><div><p><b>${esc(x.title)}</b><em class="${ss[1]}">${ss[0]}</em></p><small>${esc(m.desc||'')}</small><div class="g30-counts"><span>Нужно <b>${x.need} ${esc(u)}</b></span><span>Назначено <b>${aq(x)} ${esc(u)}</b></span><span>Подтверждено <b>${cq(x)} ${esc(u)}</b></span></div></div><div>${owners(x)}</div><div>${actions(x)}</div>${kit(x)}</article>`}).join('')}</div>`).join('')}</section>`}

  function problems(pid){const st=G().status[pid]||{};return PERSONAL.filter(i=>['borrow','missing','check'].includes(st[i.id])||(i.priority==='required'&&st[i.id]!=='ready')).map(i=>[i,st[i.id]||'unset'])}
  function team(){const people=S.participants.filter(p=>p.rsvp!=='no'),req=PERSONAL.filter(i=>i.priority==='required'),all=people.flatMap(p=>problems(p.id)),borrow=all.filter(x=>x[1]==='borrow').length,missing=all.filter(x=>x[1]==='missing').length,ready=people.filter(p=>req.every(i=>G().status[p.id]?.[i.id]==='ready')).length,t=totals();return `<div class="g30-summary">${metric('Люди',`${ready}/${people.length}`,'закрыли обязательное',ready===people.length?'ok':'warn')}${metric('Нужно одолжить',borrow,'запросы участников',borrow?'risk':'ok')}${metric('Нет / не готово',missing,'явные проблемы',missing?'risk':'ok')}${metric('Общее',`${t.ok}/${t.all}`,'полностью готово',t.ok===t.all?'ok':'warn')}</div><section class="g30-panel"><div class="g30-head"><div><div class="page-kicker">Организатор</div><h2>Готовность команды</h2><p>Фокус на обязательном и исключениях.</p></div></div><div class="g30-team">${people.map(p=>{const pr=problems(p.id),rr=req.filter(i=>G().status[p.id]?.[i.id]==='ready').length,f=fstat(p.id);return `<div class="g30-team-row"><span class="g30-team-person"><span class="avatar">${initials(p.name)}</span><span><b>${esc(p.name)}</b><small>${p.rsvp==='yes'?'Участвует':p.rsvp==='maybe'?'Возможно':'Нет ответа'}</small></span></span><span><b>${rr}/${req.length}</b><small>обязательное</small></span><span><b>${f.done}/${f.total}</b><small>перед выходом</small></span><span class="g30-problems">${pr.length?pr.slice(0,3).map(([i,v])=>`<em class="${STATUS[v][1]||'warn'}">${esc(i.title)} · ${esc(v==='unset'?'не отмечено':STATUS[v][0])}</em>`).join(''):'<em class="ok">Критичных проблем нет</em>'}</span></div>`}).join('')}</div></section>`}

  function page(){ensure();if(mode==='team'&&!organizer())mode='personal';return `${pageHead('Подготовка','Снаряжение','Личная сборка, распределение общего имущества и финальная проверка перед выходом.',organizer()&&mode==='shared'?'<button class="btn sand" id="g30AddTop">+ Добавить общее</button>':'')}${tabs()}<div class="g30-content">${mode==='personal'?personal():mode==='shared'?shared():team()}</div>`}
  function qty(id,d){const x=S.shared.find(g=>g.id===id);if(!x)return;let r=x.a.find(a=>a[0]===S.current),n=+(r?.[1]||0);if(d>0&&aq(x)>=(+x.need||0))return toast('Потребность уже распределена');n=Math.max(0,n+d);if(r)r[1]=n;else if(n)x.a.push([S.current,n]);x.a=x.a.filter(a=>+a[1]>0);x.confirmed=x.confirmed.filter(p=>p!==S.current);save();render()}
  function modal(){const l=document.getElementById('modalLayer');if(!l)return;l.innerHTML=`<div class="g30-backdrop" data-g30-close></div><div class="g30-modal"><div class="g30-modal-head"><b>Добавить общее имущество</b><button data-g30-close>×</button></div><div class="g30-modal-body"><label>Шаблон<select id="g30Preset">${Object.entries(PRESETS).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></label><label>Название<input id="g30Title"></label><div><label>Нужно<input id="g30Need" type="number" min="1" value="1"></label><label>Единица<input id="g30Unit" value="шт."></label></div><label>Раздел<select id="g30Cat">${Object.entries(SHARED_CATS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Подсказка<textarea id="g30Desc" rows="3"></textarea></label></div><div class="g30-modal-foot"><button class="btn alt" data-g30-close>Отмена</button><button class="btn sand" id="g30Save">Добавить</button></div></div>`;l.classList.add('open');l.setAttribute('aria-hidden','false');const apply=()=>{const v=PRESETS[document.getElementById('g30Preset').value];document.getElementById('g30Title').value=v[0]==='Своя позиция'?'':v[0];document.getElementById('g30Need').value=v[1];document.getElementById('g30Unit').value=v[2];document.getElementById('g30Cat').value=v[3];document.getElementById('g30Desc').value=v[4]};apply();document.getElementById('g30Preset').onchange=apply;l.querySelectorAll('[data-g30-close]').forEach(b=>b.onclick=close);document.getElementById('g30Save').onclick=()=>{const title=document.getElementById('g30Title').value.trim();if(!title)return toast('Укажи название');const id='g30_'+Date.now(),need=Math.max(1,+document.getElementById('g30Need').value||1);S.shared.push({id,title,need,a:[],confirmed:[]});G().meta[id]={unit:document.getElementById('g30Unit').value.trim()||'шт.',cat:document.getElementById('g30Cat').value,desc:document.getElementById('g30Desc').value.trim()};save();close();render()}}
  function close(){const l=document.getElementById('modalLayer');l.classList.remove('open');l.setAttribute('aria-hidden','true');l.innerHTML=''}
  function bind30(){document.body.classList.toggle('g30-active',tab==='gear');if(tab!=='gear')return;document.querySelectorAll('[data-g30-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.g30Mode;render()});document.querySelectorAll('[data-g30-status]').forEach(s=>s.onchange=()=>{G().status[S.current][s.dataset.g30Status]=s.value;sync();render()});document.querySelectorAll('[data-g30-final]').forEach(b=>b.onclick=()=>{G().final[S.current][b.dataset.g30Final]=!G().final[S.current][b.dataset.g30Final];save();render()});document.querySelectorAll('[data-g30-take]').forEach(b=>b.onclick=()=>qty(b.dataset.g30Take,1));document.querySelectorAll('[data-g30-qty]').forEach(b=>b.onclick=()=>{const [id,d]=b.dataset.g30Qty.split(':');qty(id,+d)});document.querySelectorAll('[data-g30-confirm]').forEach(b=>b.onclick=()=>{const x=S.shared.find(g=>g.id===b.dataset.g30Confirm);if(!x||!mine(x))return;x.confirmed.includes(S.current)?x.confirmed=x.confirmed.filter(p=>p!==S.current):x.confirmed.push(S.current);save();render()});document.querySelectorAll('[data-g30-kit]').forEach(b=>b.onclick=()=>{const [id,k]=b.dataset.g30Kit.split(':');const x=S.shared.find(g=>g.id===id);if(!x||(!mine(x)&&!organizer()))return;G().kits[id][k]=!G().kits[id][k];save();render()});document.getElementById('g30Add')?.addEventListener('click',modal);document.getElementById('g30AddTop')?.addEventListener('click',modal)}

  progress=function(pid){const req=PERSONAL.filter(i=>i.priority==='required'),done=req.filter(i=>G().status[pid]?.[i.id]==='ready').length;return[done,req.length,Math.round(done/req.length*100)]};
  ensure();sync(true);const oldBind=bind;gearPage=page;bind=function(){oldBind();bind30()};document.querySelector('.build-label')?.replaceChildren(document.createTextNode('V24 · снаряжение · комплекты и готовность'));render();
})();
