/* V41 — clearer day plan and compact checkpoint list. */
(()=>{
'use strict';
let view41='day';
const km41=()=>{try{return (routeLenV13()/1000).toFixed(1).replace('.',',')+' км'}catch(e){return S.event?.distance||'—'}};
const calc41=()=>routePlanStatsV23();
function summary41(){const s=calc41();return `<div class="v41-summary"><div><small>Дистанция</small><strong>${km41()}</strong><span>по текущей линии</span></div><div><small>Старт</small><strong>${editorV13.start}</strong><span>маршрута</span></div><div><small>Финиш</small><strong>${finalEtaV13()}</strong><span>расчётный</span></div><div><small>Движение</small><strong>${fmtMinutesV23(s.base)}</strong><span>без остановок</span></div><div><small>Перерывы</small><strong>${fmtMinutesV23(s.pauses)}</strong><span>${breaksV23().length} событий</span></div><div><small>Резерв</small><strong>${reservePctV23()}%</strong><span>${fmtMinutesV23(s.reserve)}</span></div></div>`}
function tabs41(){return `<div class="v41-tabs"><button class="${view41==='day'?'active':''}" data-v41-view="day">План дня</button><button class="${view41==='route'?'active':''}" data-v41-view="route">Маршрут и перерывы</button><button class="${view41==='pace'?'active':''}" data-v41-view="pace">Расчёт темпа</button></div>`}
function sync41(){const a=(S.timeline||[]).find(t=>/старт маршрут/i.test(t.title||'')),b=(S.timeline||[]).find(t=>/(заверш|финиш).*маршрут/i.test(t.title||'')),bad=(a&&a.time!==editorV13.start)||(b&&b.time!==finalEtaV13());return bad?`<div class="v41-sync warn"><span><b>В расписании и расчёте маршрута разное время</b><small>Расчёт: ${editorV13.start} → ${finalEtaV13()}</small></span><button class="btn alt sm" id="v41Sync">Синхронизировать</button></div>`:`<div class="v41-sync ok"><span><b>Расписание согласовано с маршрутом</b><small>${editorV13.start} → ${finalEtaV13()}</small></span></div>`}
function day41(){const rows=[...(S.timeline||[])].sort((a,b)=>(a.time||'').localeCompare(b.time||''));return `<div class="v41-day-layout"><section class="v41-panel"><div class="v41-panel-head"><div><div class="page-kicker">Организация мероприятия</div><h2>План дня</h2><p>Сбор, выезд, маршрут, остановки и завершение в одном расписании.</p></div></div>${sync41()}<div class="v41-day-list">${rows.map((t,i)=>`<article class="v41-day-row"><div class="v41-day-time">${esc(t.time)}</div><div class="v41-day-line"><i></i>${i<rows.length-1?'<span></span>':''}</div><div class="v41-day-main"><div><b>${esc(t.title)}</b>${t.route?'<em>Маршрут</em>':''}</div><p>${esc(t.note||'Без комментария')}</p><div class="v41-day-meta"><span><small>Ответственный</small><b>${esc(pn(t.owner))}</b></span><span><small>Привязка</small><b>${t.route?esc(routeName(t.route)):'Без привязки'}</b></span></div></div><div class="v41-day-actions"><button class="icon-btn" data-edit-time="${t.id}">✎</button><button class="icon-btn" data-del-time="${t.id}">×</button></div></article>`).join('')}</div></section><aside class="v41-side"><div class="v41-side-card"><small>РАСЧЁТ МАРШРУТА</small><strong>${editorV13.start} → ${finalEtaV13()}</strong><span>${km41()} · ${PACE_PROFILES_V23[planProfileV23()].short.toLowerCase()} темп</span><button class="btn alt sm" data-v41-view="route">Открыть маршрутный план</button></div><div class="v41-side-card"><small>ПЕРЕРЫВЫ</small><strong>${breaksV23().length}</strong><span>Всего ${fmtMinutesV23(breaksTotalV23())}</span><button class="btn alt sm" data-v41-view="route">Настроить</button></div></aside></div>`}
function route41(){return `<section class="v41-panel"><div class="v41-panel-head"><div><div class="page-kicker">Расчётный маршрут</div><h2>Контрольные точки и перерывы</h2><p>КП приходят из карты. Перерывы — отдельные временные события между точками.</p></div></div>${routeTimelineHtmlV23()}</section>`}
function pace41(){return `<div class="v41-pace"><section class="v41-panel"><div class="v41-panel-head"><div><div class="page-kicker">Параметры</div><h2>Старт и резерв</h2><p>Изменения сразу пересчитывают ETA контрольных точек.</p></div></div><div class="plan-settings-v23"><div class="plan-start-reserve-v23"><label>Время старта<input type="time" id="routeStartV23" value="${editorV13.start}"></label><label>Организационный резерв<input type="number" min="0" max="50" step="1" id="reserveV23" value="${reservePctV23()}"><span>% от времени движения</span></label></div></div></section><section class="v41-panel"><div class="v41-panel-head"><div><div class="page-kicker">Темп группы</div><h2>Скорость по типу участка</h2><p>Выберите профиль и при необходимости скорректируйте значения.</p></div></div>${speedCardsV23()}</section></div>`}
function page41(){ensurePlanV23();let actions=view41==='day'?'<button class="btn sand" id="addTimeline">+ Этап</button>':view41==='route'?'<button class="btn alt" id="copyAllCpV23">Скопировать КП</button><button class="btn sand" id="addBreakGeneralV23">+ Перерыв</button>':'';return `${pageHead('Организация дня','План','Единое расписание похода: организационные этапы, расчёт движения, контрольные точки и остановки.',actions)}${summary41()}${tabs41()}${view41==='day'?day41():view41==='route'?route41():pace41()}`}
function syncTimes41(){let n=0;(S.timeline||[]).forEach(t=>{if(/старт маршрут/i.test(t.title||'')&&t.time!==editorV13.start){t.time=editorV13.start;n++}if(/(заверш|финиш).*маршрут/i.test(t.title||'')&&t.time!==finalEtaV13()){t.time=finalEtaV13();n++}});if(n){S.timeline.sort((a,b)=>(a.time||'').localeCompare(b.time||''));save();render();toast('Время маршрута синхронизировано')}else toast('Расписание уже совпадает с расчётом')}
function cp41(){return dynamicCpsV13().map(cp=>`<div class="v41-cp-row"><button class="v41-cp-main" data-cp-dyn-v13="${cp.id}"><span class="v41-cp-index ${cp.number==='С'||cp.number==='Ф'?'endpoint':''}">${cp.number}</span><span class="v41-cp-copy"><b>${esc(cp.title)}</b><small><span class="grid-code-v12">${gridCodeDynamicV13(cp.lat,cp.lon)}</span>${cp.km.toFixed(1).replace('.',',')} км · ${cp.lat.toFixed(6)}, ${cp.lon.toFixed(6)}</small></span><span class="v41-cp-eta"><small>ETA</small><b>${cp.arrival}</b></span></button><div class="v41-cp-actions"><button data-copy-cp-v23="${cp.id}">Копировать</button><button data-open-cp-v23="${cp.id}">Яндекс ↗</button></div></div>`).join('')}
planPage=page41;cpRowsDynamicV23=cp41;cpRowsDynamicV13=cp41;
const oldBind41=bind;bind=function(){oldBind41();document.querySelectorAll('[data-v41-view]').forEach(b=>b.onclick=()=>{view41=b.dataset.v41View;render()});document.getElementById('v41Sync')?.addEventListener('click',syncTimes41);if(tab==='plan'){const x=document.querySelector('.build-label');if(x)x.textContent='V41 · единый план дня'}};
render();
})();
