/* V9.1 — fix panel recursion and keep grid editor compatible */
function panelV15(){
  if(!editorModeV13)return `<div class="metric"><small>Расчётная длина</small><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong><em>по сохранённой линии</em></div><div class="metric"><small>Расчётный финиш</small><strong>${finalEtaV13()}</strong><em>${fmtDurationV13(routeDurationMinV13())}</em></div><div class="metric"><small>КП</small><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong><em>координаты и ETA</em></div><div class="metric"><small>Сетка</small><strong>${gridCfgV13().cell} × ${gridCfgV13().cell} м</strong><em>${editorV13.grid.offsetX||editorV13.grid.offsetY?'со смещением':'по PDF'}</em></div>`;
  let sel='';
  if(selectedV13?.type==='vertex'){
    const i=selectedV13.index,p=editorV13.route[i],end=i===0?'Старт':i===editorV13.route.length-1?'Финиш':`Точка ${i+1}`;
    sel=`<div class="editor-card-v13"><small>${end}</small><strong id="pointCoordsV15">${p[0].toFixed(6)}, ${p[1].toFixed(6)}</strong><div class="coord-grid-v15"><label>Широта<input id="vertexLatV15" type="number" step="0.000001" value="${p[0].toFixed(6)}"></label><label>Долгота<input id="vertexLonV15" type="number" step="0.000001" value="${p[1].toFixed(6)}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" data-save-point-v15="${i}">Применить координаты</button><button class="btn alt sm" data-delete-point-v15="${i}" ${i===0||i===editorV13.route.length-1?'disabled':''}>Удалить точку</button></div>${(i===0||i===editorV13.route.length-1)?`<label class="loop-toggle-v15"><input id="loopLockV15" type="checkbox" ${editorV13.loopLocked!==false?'checked':''}><span><b>Старт и финиш совпадают</b><small>Если включено, перемещение лагеря меняет обе конечные точки.</small></span></label>`:''}<div class="editor-help-v15">Перетаскивание меняет только выбранную точку. Соседние узлы остаются на своих координатах.</div></div>`;
  } else if(selectedV13?.type==='segment'){
    const i=selectedV13.index,t=editorV13.terrain[i]||'unknown',a=editorV13.route[i],b=editorV13.route[i+1];
    sel=`<div class="editor-card-v13"><small>Участок ${i+1}</small><strong>${(havV13(a,b)*DISTANCE_CAL_V13/1000).toFixed(2).replace('.',',')} км</strong><label>Тип движения<select data-terrain-v15="${i}">${Object.entries(TERRAIN_V13).map(([k,v])=>`<option value="${k}" ${k===t?'selected':''}>${v.label}</option>`).join('')}</select></label><div class="editor-inline-v13"><button class="btn sand sm" data-route-one-v15="${i}">По тропе этот участок</button><button class="btn alt sm" data-split-v15="${i}">+ Точка в середине</button></div><div class="editor-help-v15">На самой линии также появляется кнопка «+». Добавь точку и затем смести только её.</div></div>`;
  } else if(selectedV13?.type==='cp'){
    const cp=editorV13.cps.find(x=>x.id===selectedV13.id),d=dynamicCpsV13().find(x=>x.id===selectedV13.id);
    if(cp)sel=`<div class="editor-card-v13"><small>${d?.number==='С'?'Старт':d?.number==='Ф'?'Финиш':`КП ${d?.number||''}`} · ${gridCodeDynamicV13(cp.lat,cp.lon)}</small><label>Название<input id="cpTitleV15" value="${esc(cp.title)}"></label><label>Остановка, мин<input id="cpStopV15" type="number" min="0" max="240" value="${cp.stopMin||0}"></label><div class="coord-grid-v15"><label>Широта<input id="cpLatV15" type="number" step="0.000001" value="${cp.lat.toFixed(6)}"></label><label>Долгота<input id="cpLonV15" type="number" step="0.000001" value="${cp.lon.toFixed(6)}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" data-save-cp-v15="${cp.id}">Сохранить КП</button><button class="btn alt sm" data-delete-cp-v15="${cp.id}" ${cp.locked?'disabled':''}>Удалить КП</button></div><p>${d?`${d.km.toFixed(1).replace('.',',')} км от старта · ETA ${d.arrival}`:''}</p></div>`;
  } else if(editorToolV13==='grid'){
    const g=editorV13.grid;
    sel=`<div class="editor-card-v13"><small>Координатная сетка</small><label>Размер клетки<select id="gridCellV14">${[100,200,250,500].map(v=>`<option value="${v}" ${+g.cell===v?'selected':''}>${v} × ${v} м</option>`).join('')}<option value="custom" ${![100,200,250,500].includes(+g.cell)?'selected':''}>Свой размер</option></select></label><label>Свой размер, м<input id="gridCustomV14" type="number" min="50" max="1000" step="10" value="${+g.cell||200}"></label><div class="grid-nudge-v14"><span></span><button data-grid-nudge-v14="up">↑</button><span></span><button data-grid-nudge-v14="left">←</button><button type="button" class="grid-nudge-center-v14">${+g.offsetX||0}; ${+g.offsetY||0}</button><button data-grid-nudge-v14="right">→</button><span></span><button data-grid-nudge-v14="down">↓</button><span></span></div><div class="editor-grid2-v13"><label>Смещение X, м<input id="gridOffsetXV14" type="number" step="10" value="${+g.offsetX||0}"></label><label>Смещение Y, м<input id="gridOffsetYV14" type="number" step="10" value="${+g.offsetY||0}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" id="applyGridV14">Применить</button><button class="btn alt sm" id="resetGridV14">PDF 200 м</button></div><p>Стрелки двигают сетку по 25 м. Поля ниже задают точное смещение.</p></div>`;
  }
  const empty=`<div class="editor-empty-v13"><strong>${editorToolV13==='route'?'Выбери точку или участок':editorToolV13==='cp'?'Добавь или выбери КП':'Сетка'}</strong><p>${editorToolV13==='route'?(routeActionV15==='add'?'Клик по карте добавит одну точку маршрута.':routeActionV15==='path'?'Укажи начало и конец участка прямо на линии.':'Выбери белую точку и двигай только её. Клик по участку откроет действия справа.'):editorToolV13==='cp'?'Клик по карте добавляет КП точно в выбранных координатах.':'Настрой размер и смещение сетки.'}</p></div>`;
  return `<div class="editor-summary-v13"><div class="editor-stat-v13"><span>Длина</span><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div class="editor-stat-v13"><span>Финиш</span><strong>${finalEtaV13()}</strong></div><div class="editor-stat-v13"><span>КП</span><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong></div></div>${sel||empty}`;
}
editorPanelV13=panelV15;
const buildV151=document.querySelector('.build-label');if(buildV151)buildV151.textContent='V9.1 · точный редактор маршрута';
render();
