function iconVertexV13(active=false){return L.divIcon({className:'',html:`<span class="route-vertex-v13 ${active?'active':''}"></span>`,iconSize:[12,12],iconAnchor:[6,6]})}
function iconCpV13(label,active=false){return L.divIcon({className:'',html:`<span class="route-cp-v13 ${active?'active':''}">${label}</span>`,iconSize:[26,26],iconAnchor:[13,13]})}
function clearEditLayersV13(){routeSegLayersV13.forEach(x=>routeMapV11?.removeLayer(x));routeVertexLayersV13.forEach(x=>routeMapV11?.removeLayer(x));Object.values(cpLayersV13).forEach(x=>routeMapV11?.removeLayer(x));routeSegLayersV13=[];routeVertexLayersV13=[];cpLayersV13={};if(routeLineV13&&routeMapV11?.hasLayer(routeLineV13))routeMapV11.removeLayer(routeLineV13);routeLineV13=null}
function routeColorV13(i){const t=editorV13.terrain[i]||'unknown';return TERRAIN_V13[t]?.color||TERRAIN_V13.unknown.color}
function drawRouteV13(){if(!routeMapV11)return;clearEditLayersV13();if(!editorModeV13){routeLineV13=L.polyline(editorV13.route,{color:'#6c22c7',weight:4,opacity:.98,lineJoin:'round',lineCap:'round',smoothFactor:.1,interactive:false}).addTo(routeMapV11)}else{
  for(let i=0;i<editorV13.route.length-1;i++){const seg=L.polyline([editorV13.route[i],editorV13.route[i+1]],{color:routeColorV13(i),weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:.95,interactive:true,bubblingMouseEvents:false}).addTo(routeMapV11);seg.on('click',e=>{L.DomEvent.stopPropagation(e);if(editorToolV13==='route'){selectedV13={type:'segment',index:i};render()}});routeSegLayersV13.push(seg)}
  if(editorToolV13==='route'){const z=routeMapV11.getZoom();const step=z>=16?1:z>=15?2:4;editorV13.route.forEach((p,i)=>{if(i!==0&&i!==editorV13.route.length-1&&i%step!==0&&selectedV13?.index!==i)return;const m=L.marker(p,{icon:iconVertexV13(selectedV13?.type==='vertex'&&selectedV13.index===i),draggable:true,zIndexOffset:500}).addTo(routeMapV11);m.on('dragstart',()=>pushHistoryV13());m.on('drag',ev=>{const ll=ev.target.getLatLng();editorV13.route[i]=[ll.lat,ll.lng];redrawRouteOnlyV13()});m.on('dragend',()=>{saveEditorV13();if(editorV13.snapCps)snapAllCpsV13();selectedV13={type:'vertex',index:i};render()});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);selectedV13={type:'vertex',index:i};render()});routeVertexLayersV13.push(m)})}
 }
 const cps=dynamicCpsV13();cps.forEach(cp=>{const label=cp.number==='С'?'С':cp.number==='Ф'?'Ф':cp.number,m=L.marker([cp.lat,cp.lon],{icon:iconCpV13(label,selectedV13?.type==='cp'&&selectedV13.id===cp.id),draggable:editorModeV13,zIndexOffset:800}).addTo(routeMapV11);m.bindTooltip(`${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':'КП '+cp.number} · ${cp.title} · ${gridCodeDynamicV13(cp.lat,cp.lon)}`,{direction:'top'});if(editorModeV13){m.on('dragstart',()=>pushHistoryV13());m.on('dragend',ev=>{const ll=ev.target.getLatLng(),obj=editorV13.cps.find(x=>x.id===cp.id);if(obj){if(editorV13.snapCps){const n=nearestRouteV13(ll.lat,ll.lng);obj.lat=n.lat;obj.lon=n.lon}else{obj.lat=ll.lat;obj.lon=ll.lng}saveEditorV13();selectedV13={type:'cp',id:cp.id};render()}});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);selectedV13={type:'cp',id:cp.id};render()})}cpLayersV13[cp.id]=m})
}
function redrawRouteOnlyV13(){if(!routeMapV11)return;routeSegLayersV13.forEach((seg,i)=>seg.setLatLngs([editorV13.route[i],editorV13.route[i+1]]));Object.values(cpLayersV13).forEach((m)=>{});}
function snapAllCpsV13(){editorV13.cps.forEach(cp=>{if(cp.id==='cp0'||cp.id==='cpf')return;const n=nearestRouteV13(cp.lat,cp.lon);if(n){cp.lat=n.lat;cp.lon=n.lon}});const s=editorV13.cps.find(x=>x.id==='cp0'),f=editorV13.cps.find(x=>x.id==='cpf');if(s){s.lat=editorV13.route[0][0];s.lon=editorV13.route[0][1]}if(f){f.lat=editorV13.route[editorV13.route.length-1][0];f.lon=editorV13.route[editorV13.route.length-1][1]}saveEditorV13()}
function insertRoutePointV13(lat,lon){const n=nearestRouteV13(lat,lon);if(!n)return;pushHistoryV13();editorV13.route.splice(n.seg+1,0,[lat,lon]);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const i=+k;next[i>n.seg?i+1:i]=v});next[n.seg+1]=next[n.seg]||'unknown';editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13={type:'vertex',index:n.seg+1};render();toast('Узел маршрута добавлен')}
function deleteVertexV13(i){if(i<=0||i>=editorV13.route.length-1){toast('Старт и финиш удалять нельзя');return}pushHistoryV13();editorV13.route.splice(i,1);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n===i) return;next[n>i?n-1:n]=v});editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13=null;render();toast('Узел удалён')}
function addCpV13(lat,lon){pushHistoryV13();let p={lat,lon};if(editorV13.snapCps){const n=nearestRouteV13(lat,lon);p={lat:n.lat,lon:n.lon}}const id='u'+Date.now();editorV13.cps.push({id,title:'Новая контрольная точка',lat:p.lat,lon:p.lon,stopMin:0,locked:false});saveEditorV13();selectedV13={type:'cp',id};editorToolV13='route';render();toast('КП добавлена — задай название')}
function deleteCpV13(id){const cp=editorV13.cps.find(x=>x.id===id);if(!cp||cp.locked){toast('Старт / финиш удалять нельзя');return}pushHistoryV13();editorV13.cps=editorV13.cps.filter(x=>x.id!==id);saveEditorV13();selectedV13=null;render();toast('КП удалена')}
function updateCpV13(id,patch){const cp=editorV13.cps.find(x=>x.id===id);if(!cp)return;pushHistoryV13();Object.assign(cp,patch);saveEditorV13();render();toast('КП обновлена')}
function setTerrainV13(i,type){pushHistoryV13();editorV13.terrain[i]=type;saveEditorV13();render();toast(`Участок: ${TERRAIN_V13[type]?.label||type}`)}
async function routeSegmentBrouterV13(i){if(lastBrouterPendingV13)return;const a=editorV13.route[i],b=editorV13.route[i+1];if(!a||!b)return;lastBrouterPendingV13=true;toast('Строю участок по тропам OSM…');try{const u=`https://brouter.de/brouter?lonlats=${a[1]},${a[0]}%7C${b[1]},${b[0]}&profile=trekking&alternativeidx=0&format=geojson`,r=await fetch(u);if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),coords=j?.features?.[0]?.geometry?.coordinates||j?.geometry?.coordinates;if(!Array.isArray(coords)||coords.length<2)throw new Error('Нет геометрии');pushHistoryV13();const repl=coords.map(c=>[+c[1],+c[0]]);editorV13.route.splice(i,2,...repl);const delta=repl.length-2,next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n<i)next[n]=v;else if(n>i)next[n+delta]=v});for(let n=i;n<i+repl.length-1;n++)next[n]='trail';editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13={type:'segment',index:i};render();toast('Участок проложен по тропам. Если не подходит — Отменить.')}catch(e){toast('Не удалось построить по тропам. Оставил ручную геометрию.')}finally{lastBrouterPendingV13=false}}

function terrainSummaryV13(fromM,toM){const cum=routeCumV13(),counts={};for(let i=0;i<editorV13.route.length-1;i++){const a=cum[i],b=cum[i+1];if(b<fromM||a>toM)continue;const t=editorV13.terrain[i]||'unknown',m=Math.max(0,Math.min(b,toM)-Math.max(a,fromM));counts[t]=(counts[t]||0)+m}const keys=Object.entries(counts).sort((a,b)=>b[1]-a[1]);return keys.length?keys.slice(0,2).map(([t])=>TERRAIN_V13[t].label).join(' + '):'—'}
function dynamicNavRowsV13(){const cps=dynamicCpsV13();return cps.slice(0,-1).map((a,i)=>{const b=cps[i+1],dist=Math.max(0,b.km-a.km),az=Math.round(bearingV13([a.lat,a.lon],[b.lat,b.lon])),terr=terrainSummaryV13(a.km*1000,b.km*1000);return `<button class="nav-leg" type="button" data-cp-dyn-v13="${b.id}"><span class="leg-num">${String(i+1).padStart(2,'0')}</span><span><b>${esc(a.title)} → ${esc(b.title)}</b><small>${esc(terr)}</small></span><span class="leg-data"><b>${dist.toFixed(1).replace('.',',')} км</b><small>${az}°</small></span></button>`}).join('')}
function cpRowsDynamicV13(){return dynamicCpsV13().map(cp=>`<button class="cp-row" data-cp-dyn-v13="${cp.id}" type="button"><span class="cp-index">${cp.number}</span><span class="cp-main"><b>${esc(cp.title)}</b><small><span class="grid-code-v12">${gridCodeDynamicV13(cp.lat,cp.lon)}</span>${cp.lat.toFixed(6)}, ${cp.lon.toFixed(6)}</small></span><span class="cp-km">${cp.km.toFixed(1).replace('.',',')} км</span><span class="cp-time">${cp.arrival}<small>${cp.stopMin?`стоп ${cp.stopMin} мин`:''}</small></span></button>`).join('')}
