/* V10 — in-place editor controls + explicit A/B trail routing */
let pathAV16=null,pathBV16=null,pathLayersV16=[],routeHitLayersV16=[],pathErrorV16='';

function clearHitV16(){routeHitLayersV16.forEach(l=>{try{routeMapV11?.removeLayer(l)}catch(e){}});routeHitLayersV16=[]}
function clearPathLayersV16(){pathLayersV16.forEach(l=>{try{routeMapV11?.removeLayer(l)}catch(e){}});pathLayersV16=[]}
function clearPathAnchorsV16(redraw=true){pathAV16=null;pathBV16=null;pathErrorV16='';clearPathLayersV16();if(redraw)refreshToolstripV16()}
function nearV16(a,b,m=0.6){return havV13(a,b)<=m}
function anchorMeasureV16(a){if(!a)return 0;return a.seg+(a.frac||0)}
function anchorFromLatLngV16(lat,lon){const n=nearestRouteV13(lat,lon);if(!n)return null;const a=editorV13.route[n.seg],b=editorV13.route[n.seg+1],d=Math.max(0.01,havV13(a,b)),frac=Math.max(0,Math.min(1,havV13(a,[n.lat,n.lon])/d));return {seg:n.seg,frac,lat:n.lat,lon:n.lon}}
function anchorFromVertexV16(i){const last=editorV13.route.length-1,p=editorV13.route[i];if(i>=last)return {seg:last-1,frac:1,lat:p[0],lon:p[1]};return {seg:i,frac:0,lat:p[0],lon:p[1]}}
function orderedAnchorsV16(){if(!pathAV16||!pathBV16)return null;return anchorMeasureV16(pathAV16)<=anchorMeasureV16(pathBV16)?[pathAV16,pathBV16]:[pathBV16,pathAV16]}
function pathPreviewPointsV16(){const ab=orderedAnchorsV16();if(!ab)return [];const [a,b]=ab,pts=[[a.lat,a.lon]];for(let i=a.seg+1;i<=b.seg;i++)pts.push(editorV13.route[i]);pts.push([b.lat,b.lon]);return pts.filter((p,i,arr)=>!i||!nearV16(p,arr[i-1],.2))}
function pathAnchorIconV16(label){return L.divIcon({className:'',html:`<span class="path-anchor-v16">${label}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}
function renderPathAnchorsV16(){clearPathLayersV16();if(!routeMapV11||routeActionV15!=='path')return;if(pathAV16){const m=L.marker([pathAV16.lat,pathAV16.lon],{icon:pathAnchorIconV16('A'),zIndexOffset:1800,interactive:false}).addTo(routeMapV11);pathLayersV16.push(m)}if(pathBV16){const m=L.marker([pathBV16.lat,pathBV16.lon],{icon:pathAnchorIconV16('B'),zIndexOffset:1800,interactive:false}).addTo(routeMapV11);pathLayersV16.push(m)}if(pathAV16&&pathBV16){const pts=pathPreviewPointsV16();if(pts.length>1){const l=L.polyline(pts,{color:'#c7a65a',weight:9,opacity:.62,dashArray:'7 7',interactive:false,lineCap:'round'}).addTo(routeMapV11);l.bringToBack();pathLayersV16.push(l)}}}
function pickPathAnchorV16(lat,lon){const a=anchorFromLatLngV16(lat,lon);if(!a)return;if(!pathAV16){pathAV16=a;pathBV16=null;pathErrorV16='';toast('Точка A выбрана. Теперь выбери B на маршруте.')}else if(!pathBV16){if(Math.abs(anchorMeasureV16(a)-anchorMeasureV16(pathAV16))<0.01){toast('Точка B должна быть дальше от A');return}pathBV16=a;pathErrorV16='';toast('A и B выбраны. Нажми «Проложить по тропе».')}else{pathAV16=a;pathBV16=null;pathErrorV16='';toast('Новая точка A выбрана. Теперь выбери B.')}renderPathAnchorsV16();refreshToolstripV16()}
function pickPathVertexV16(i){const a=anchorFromVertexV16(i);pickPathAnchorV16(a.lat,a.lon)}

function routeToolstripV16(){if(!editorModeV13)return '';let hint='';if(editorToolV13==='route'){if(routeActionV15==='add')hint='Добавление точки: нажми прямо на линию маршрута. Масштаб и положение карты не изменятся.';else if(routeActionV15==='path')hint=!pathAV16?'Шаг 1 из 2: нажми на маршрут в месте начала фрагмента.':!pathBV16?'Шаг 2 из 2: нажми на маршрут в месте окончания фрагмента.':'A и B зафиксированы. Проверь выделенный фрагмент и только потом запускай прокладку.';else hint='Выбор: перетаскивай одну белую точку или нажми на участок. Переключение инструментов больше не перезагружает карту.'}else if(editorToolV13==='cp')hint='КП: клик по карте добавляет точку; существующую можно перетаскивать.';else hint='Сетка: размер и смещение настраиваются справа.';return `<div class="route-toolstrip-v15 route-toolstrip-v16" id="routeToolstripV16"><div class="route-toolgroup-v15"><button class="route-tool-v15 ${editorToolV13==='route'?'active':''}" data-tool-v16="route">Линия</button><button class="route-tool-v15 ${editorToolV13==='cp'?'active':''}" data-tool-v16="cp">КП</button><button class="route-tool-v15 ${editorToolV13==='grid'?'active':''}" data-tool-v16="grid">Сетка</button></div>${editorToolV13==='route'?`<div class="route-toolgroup-v15"><button class="route-tool-v15 ${routeActionV15==='select'?'active':''}" data-action-v16="select">Выбрать / двигать</button><button class="route-tool-v15 ${routeActionV15==='add'?'active':''}" data-action-v16="add">+ Точка</button><button class="route-tool-v15 path ${routeActionV15==='path'?'active':''}" data-action-v16="path">По тропе</button></div>`:''}${editorToolV13==='route'&&routeActionV15==='path'?`<div class="path-flow-v16"><div class="path-steps-v16"><span class="${pathAV16?'done':'active'}"><b>A</b>${pathAV16?'выбрана':'начало'}</span><i>→</i><span class="${pathBV16?'done':pathAV16?'active':''}"><b>B</b>${pathBV16?'выбрана':'конец'}</span></div><button class="btn sand sm" id="applyPathV16" ${pathAV16&&pathBV16?'':'disabled'}>${lastBrouterPendingV13?'Прокладываю…':'Проложить по тропе'}</button><button class="btn alt sm" id="clearPathV16" ${pathAV16||pathBV16?'':'disabled'}>Сбросить A/B</button></div>`:''}<div class="route-hint-v15 route-hint-v16">${pathErrorV16?`<span class="path-error-v16">${esc(pathErrorV16)}</span>`:hint}</div></div>`}
toolstripV15=routeToolstripV16;

function bindToolstripV16(){document.querySelectorAll('[data-tool-v16]').forEach(b=>b.onclick=()=>setToolV16(b.dataset.toolV16));document.querySelectorAll('[data-action-v16]').forEach(b=>b.onclick=()=>setActionV16(b.dataset.actionV16));document.getElementById('applyPathV16')?.addEventListener('click',applyPathRoutingV16);document.getElementById('clearPathV16')?.addEventListener('click',()=>clearPathAnchorsV16(true))}
function refreshToolstripV16(){const old=document.getElementById('routeToolstripV16');if(!old)return;const wrap=document.createElement('div');wrap.innerHTML=routeToolstripV16();const next=wrap.firstElementChild;old.replaceWith(next);bindToolstripV16()}
function setToolV16(tool){editorToolV13=tool;routeActionV15='select';selectedV13=null;clearPathAnchorsV16(false);drawRouteV16();refreshPanelV15();refreshToolstripV16()}
function setActionV16(action){routeActionV15=action;selectedV13=null;clearPathAnchorsV16(false);drawRouteV16();refreshPanelV15();refreshToolstripV16();if(action==='path')toast('Режим «По тропе»: сначала выбери A, затем B прямо на линии маршрута.')}

function addPointSnappedV16(lat,lon){const n=nearestRouteV13(lat,lon);if(!n)return;const d=havV13([lat,lon],[n.lat,n.lon]);if(d>140){toast('Нажми ближе к линии маршрута — точка добавляется на выбранный участок.');return}const idx=insertPointAtV15(n.seg,n.lat,n.lon);routeActionV15='select';drawRouteV16();setSelectedV15({type:'vertex',index:idx});refreshToolstripV16();toast('Точка добавлена на линию. Теперь её можно сместить.')}
addPointMapV15=addPointSnappedV16;

function clearRouteHitV16(){routeHitLayersV16.forEach(x=>{try{routeMapV11?.removeLayer(x)}catch(e){}});routeHitLayersV16=[]}
function handleRouteHitV16(i,ll){if(editorToolV13!=='route')return;if(routeActionV15==='path')return pickPathAnchorV16(ll.lat,ll.lng);if(routeActionV15==='add'){const n=nearestRouteV13(ll.lat,ll.lng);if(!n)return;const idx=insertPointAtV15(n.seg,n.lat,n.lon);routeActionV15='select';drawRouteV16();setSelectedV15({type:'vertex',index:idx});refreshToolstripV16();toast('Точка добавлена на этот участок.');return}setSelectedV15({type:'segment',index:i})}
function drawRouteV16(){if(!routeMapV11)return;clearEditLayersV13();clearMidV15();clearRouteHitV16();clearPathLayersV16();if(!editorModeV13){routeLineV13=L.polyline(editorV13.route,{color:'#6c22c7',weight:4,opacity:.98,lineJoin:'round',lineCap:'round',smoothFactor:.08,interactive:false}).addTo(routeMapV11)}else{
  for(let i=0;i<editorV13.route.length-1;i++){const visible=L.polyline([editorV13.route[i],editorV13.route[i+1]],{color:routeColorV13(i),weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:selectedV13?.type==='segment'&&selectedV13.index!==i?.55:.95,interactive:false,lineCap:'round'}).addTo(routeMapV11);routeSegLayersV13.push(visible);if(editorToolV13==='route'){const hit=L.polyline([editorV13.route[i],editorV13.route[i+1]],{color:'#000',weight:18,opacity:.001,interactive:true,bubblingMouseEvents:false}).addTo(routeMapV11);hit.on('click',e=>{L.DomEvent.stopPropagation(e);handleRouteHitV16(i,e.latlng)});routeHitLayersV16.push(hit)}}
  if(editorToolV13==='route'){const step=visibleStepV15();editorV13.route.forEach((p,i)=>{if(i!==0&&i!==editorV13.route.length-1&&i%step!==0&&selectedV13?.index!==i)return;const m=L.marker(p,{icon:iconPointV15(i,selectedV13?.type==='vertex'&&selectedV13.index===i,false),draggable:routeActionV15==='select',zIndexOffset:(i===0||i===editorV13.route.length-1)?1500:1200}).addTo(routeMapV11);m._routeIndexV15=i;m.on('dragstart',()=>{pushHistoryV13();dragBaseV15=cloneV13(editorV13.route)});m.on('drag',ev=>{const ll=ev.target.getLatLng();editorV13.route[i]=[ll.lat,ll.lng];syncEndpointCpV15(i,ll);updateRouteGeomV15()});m.on('dragend',()=>{dragBaseV15=null;saveEditorV13();setSelectedV15({type:'vertex',index:i});refreshPanelV15();toast('Точка перемещена')});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);if(routeActionV15==='path')return pickPathVertexV16(i);if(routeActionV15==='add'){toast('Это уже существующая точка. Для новой нажми между точками на линии.');return}setSelectedV15({type:'vertex',index:i})});routeVertexLayersV13.push(m)})}
 }
 const cps=dynamicCpsV13();cps.forEach(cp=>{const interactive=!editorModeV13||editorToolV13==='cp',m=L.marker([cp.lat,cp.lon],{icon:iconCpV13(cp.number,selectedV13?.type==='cp'&&selectedV13.id===cp.id),draggable:editorModeV13&&editorToolV13==='cp',interactive,zIndexOffset:editorToolV13==='cp'?1350:700}).addTo(routeMapV11);m.bindTooltip(`${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':'КП '+cp.number} · ${cp.title} · ${gridCodeDynamicV13(cp.lat,cp.lon)}`,{direction:'top'});if(editorModeV13&&editorToolV13==='cp'){m.on('dragstart',()=>pushHistoryV13());m.on('dragend',ev=>{const ll=ev.target.getLatLng(),obj=editorV13.cps.find(x=>x.id===cp.id);if(!obj)return;obj.lat=ll.lat;obj.lon=ll.lng;if(cp.id==='cp0'){editorV13.route[0]=[ll.lat,ll.lng];if(editorV13.loopLocked!==false){editorV13.route[editorV13.route.length-1]=[ll.lat,ll.lng];const f=editorV13.cps.find(x=>x.id==='cpf');if(f){f.lat=ll.lat;f.lon=ll.lng}}}if(cp.id==='cpf'){editorV13.route[editorV13.route.length-1]=[ll.lat,ll.lng];if(editorV13.loopLocked!==false){editorV13.route[0]=[ll.lat,ll.lng];const s=editorV13.cps.find(x=>x.id==='cp0');if(s){s.lat=ll.lat;s.lon=ll.lng}}}saveEditorV13();drawRouteV16();setSelectedV15({type:'cp',id:cp.id});toast('КП перемещена')});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);setSelectedV15({type:'cp',id:cp.id})})}cpLayersV13[cp.id]=m});
 if(selectedV13?.type==='segment'&&routeActionV15==='select')showMidV15(selectedV13.index);renderPathAnchorsV16()}
drawRouteV15=drawRouteV16;drawRouteV13=drawRouteV16;

function appendRouteV16(state,p,t){if(!state.route.length){state.route.push(p);return}if(nearV16(state.route[state.route.length-1],p,.25))return;state.terrain[state.route.length-1]=t||'unknown';state.route.push(p)}
function replaceRangeWithRouteV16(repl){const ab=orderedAnchorsV16();if(!ab)return;const [a,b]=ab,oldR=editorV13.route,oldT=i=>editorV13.terrain[i]||'unknown',state={route:[],terrain:{}};appendRouteV16(state,oldR[0]);for(let i=0;i<a.seg;i++)appendRouteV16(state,oldR[i+1],oldT(i));const A=[a.lat,a.lon],B=[b.lat,b.lon];appendRouteV16(state,A,oldT(a.seg));const rr=repl.map(p=>[+p[0],+p[1]]);if(rr.length){rr[0]=A;rr[rr.length-1]=B;for(let i=1;i<rr.length;i++)appendRouteV16(state,rr[i],'trail')}else appendRouteV16(state,B,'trail');appendRouteV16(state,oldR[b.seg+1],oldT(b.seg));for(let i=b.seg+1;i<oldR.length-1;i++)appendRouteV16(state,oldR[i+1],oldT(i));editorV13.route=state.route;editorV13.terrain=state.terrain;if(editorV13.snapCps)snapAllCpsV13()}
async function applyPathRoutingV16(){if(!pathAV16||!pathBV16||lastBrouterPendingV13)return;lastBrouterPendingV13=true;pathErrorV16='';refreshToolstripV16();const ab=orderedAnchorsV16();try{const repl=await fetchBrouterV15([ab[0].lat,ab[0].lon],[ab[1].lat,ab[1].lon]);pushHistoryV13();replaceRangeWithRouteV16(repl);saveEditorV13();pathAV16=null;pathBV16=null;routeActionV15='select';selectedV13=null;drawRouteV16();refreshPanelV15();toast('Фрагмент перестроен по тропам OSM. Если не подходит — ↶')}catch(e){pathErrorV16='Не удалось построить этот фрагмент по OSM. Точки A/B сохранены — можно повторить или выбрать другой участок.';toast('Прокладка не удалась. A/B не сброшены.')}finally{lastBrouterPendingV13=false;refreshToolstripV16();renderPathAnchorsV16()}}

const bindV16Base=bind;bind=function(){bindV16Base();bindToolstripV16();if(tab==='route')setTimeout(()=>{renderPathAnchorsV16();updateDirtyUiV15()},0)};

const oldBeginV16=beginEditV15;beginEditV15=function(){oldBeginV16();pathAV16=null;pathBV16=null;pathErrorV16=''};
const oldSaveExitV16=saveAndExitV15;saveAndExitV15=function(){clearPathAnchorsV16(false);oldSaveExitV16()};
const oldDiscardExitV16=discardAndExitV15;discardAndExitV15=function(){clearPathAnchorsV16(false);oldDiscardExitV16()};

const buildV16=document.querySelector('.build-label');if(buildV16)buildV16.textContent='V10 · стабильное редактирование / понятная прокладка A→B';
render();
