/* V9 — precise route editing, trail range routing, explicit save/discard, live route sheet */
let editBaseV15=null,editDirtyV15=false,routeActionV15='select',rangeStartV15=null,routeMidLayerV15=null,dragBaseV15=null;
const persistEditorV15=saveEditorV13;

function sameV15(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch(e){return false}}
function dirtyV15(){editDirtyV15=!!editBaseV15&&!sameV15(editorV13,editBaseV15);updateDirtyUiV15()}
function updateDirtyUiV15(){const e=document.getElementById('editorStateV15');if(e){e.textContent=editDirtyV15?'Есть несохранённые изменения':'Изменений нет';e.classList.toggle('dirty',editDirtyV15)}}
function draftSaveV15(){if(editorModeV13&&editBaseV15){dirtyV15();return}persistEditorV15()}
saveEditorV13=draftSaveV15;

function beginEditV15(){if(editorModeV13)return;editBaseV15=cloneV13(editorV13);editDirtyV15=false;undoV13=[];redoV13=[];editorModeV13=true;editorToolV13='route';routeActionV15='select';selectedV13=null;rangeStartV15=null;renderPreserveV14()}
function saveAndExitV15(){if(!editorModeV13)return;editorModeV13=false;routeActionV15='select';rangeStartV15=null;selectedV13=null;editBaseV15=null;editDirtyV15=false;persistEditorV15();renderPreserveV14();toast('Изменения маршрута сохранены')}
function discardAndExitV15(){if(!editorModeV13)return;if(editDirtyV15&&!confirm('Отменить все изменения, сделанные после входа в редактор?'))return;if(editBaseV15)editorV13=cloneV13(editBaseV15);editorModeV13=false;routeActionV15='select';rangeStartV15=null;selectedV13=null;editBaseV15=null;editDirtyV15=false;renderPreserveV14();toast('Изменения отменены')}
window.addEventListener('beforeunload',e=>{if(editorModeV13&&editDirtyV15){e.preventDefault();e.returnValue=''}});

function iconPointV15(i,active=false,path=false){const end=i===0?'С':i===editorV13.route.length-1?'Ф':'';if(end)return L.divIcon({className:'',html:`<span class="route-endpoint-v15 ${active?'active':''} ${path?'path-anchor':''}">${end}</span>`,iconSize:[26,26],iconAnchor:[13,13]});return L.divIcon({className:'',html:`<span class="route-point-v15 ${active?'active':''} ${path?'path-anchor':''}"></span>`,iconSize:[14,14],iconAnchor:[7,7]})}
function iconMidV15(){return L.divIcon({className:'',html:'<span class="route-midadd-v15">+</span>',iconSize:[24,24],iconAnchor:[12,12]})}
function visibleStepV15(){const z=routeMapV11?.getZoom()||15;return z>=18?1:z>=17?2:z>=16?3:z>=15?5:z>=14?8:14}
function syncEndpointCpV15(i,ll){const last=editorV13.route.length-1;if(i===0){const s=editorV13.cps.find(x=>x.id==='cp0');if(s){s.lat=ll.lat;s.lon=ll.lng}if(editorV13.loopLocked!==false){editorV13.route[last]=[ll.lat,ll.lng];const f=editorV13.cps.find(x=>x.id==='cpf');if(f){f.lat=ll.lat;f.lon=ll.lng}}}else if(i===last){const f=editorV13.cps.find(x=>x.id==='cpf');if(f){f.lat=ll.lat;f.lon=ll.lng}if(editorV13.loopLocked!==false){editorV13.route[0]=[ll.lat,ll.lng];const s=editorV13.cps.find(x=>x.id==='cp0');if(s){s.lat=ll.lat;s.lon=ll.lng}}}}
function updateRouteGeomV15(){routeSegLayersV13.forEach((seg,i)=>{if(editorV13.route[i+1])seg.setLatLngs([editorV13.route[i],editorV13.route[i+1]])});routeVertexLayersV13.forEach(m=>{const i=m._routeIndexV15;if(editorV13.route[i])m.setLatLng(editorV13.route[i])});if(routeMidLayerV15&&selectedV13?.type==='segment'){const i=selectedV13.index,a=editorV13.route[i],b=editorV13.route[i+1];if(a&&b)routeMidLayerV15.setLatLng([(a[0]+b[0])/2,(a[1]+b[1])/2])}updateCpMarkersV14();const c=document.getElementById('pointCoordsV15');if(c&&selectedV13?.type==='vertex'){const p=editorV13.route[selectedV13.index];c.textContent=`${p[0].toFixed(6)}, ${p[1].toFixed(6)}`}}
function clearMidV15(){if(routeMidLayerV15&&routeMapV11?.hasLayer(routeMidLayerV15))routeMapV11.removeLayer(routeMidLayerV15);routeMidLayerV15=null}
function showMidV15(i){clearMidV15();if(!editorModeV13||editorToolV13!=='route'||!routeMapV11)return;const a=editorV13.route[i],b=editorV13.route[i+1];if(!a||!b)return;routeMidLayerV15=L.marker([(a[0]+b[0])/2,(a[1]+b[1])/2],{icon:iconMidV15(),zIndexOffset:1100}).addTo(routeMapV11);routeMidLayerV15.bindTooltip('Добавить точку на этот участок',{direction:'top'});routeMidLayerV15.on('click',e=>{L.DomEvent.stopPropagation(e);splitSegmentV15(i)})}
function setSelectedV15(sel){selectedV13=sel;refreshSelectionV15();refreshPanelV15();if(sel?.type==='segment')showMidV15(sel.index);else clearMidV15()}
function refreshSelectionV15(){routeSegLayersV13.forEach((s,i)=>s.setStyle({weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:selectedV13?.type==='segment'&&selectedV13.index!==i?.55:.95}));routeVertexLayersV13.forEach(m=>{const i=m._routeIndexV15;m.setIcon(iconPointV15(i,selectedV13?.type==='vertex'&&selectedV13.index===i,rangeStartV15===i))})}

function drawRouteV15(){if(!routeMapV11)return;clearEditLayersV13();clearMidV15();if(!editorModeV13){routeLineV13=L.polyline(editorV13.route,{color:'#6c22c7',weight:4,opacity:.98,lineJoin:'round',lineCap:'round',smoothFactor:.08,interactive:false}).addTo(routeMapV11)}else{
 for(let i=0;i<editorV13.route.length-1;i++){const seg=L.polyline([editorV13.route[i],editorV13.route[i+1]],{color:routeColorV13(i),weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:selectedV13?.type==='segment'&&selectedV13.index!==i?.55:.95,interactive:editorToolV13==='route',bubblingMouseEvents:false}).addTo(routeMapV11);seg.on('click',e=>{if(editorToolV13!=='route')return;L.DomEvent.stopPropagation(e);if(routeActionV15==='path')return chooseRangeOnSegmentV15(i,e.latlng);routeActionV15='select';setSelectedV15({type:'segment',index:i})});routeSegLayersV13.push(seg)}
 if(editorToolV13==='route'){const step=visibleStepV15();editorV13.route.forEach((p,i)=>{if(i!==0&&i!==editorV13.route.length-1&&i%step!==0&&selectedV13?.index!==i&&rangeStartV15!==i)return;const m=L.marker(p,{icon:iconPointV15(i,selectedV13?.type==='vertex'&&selectedV13.index===i,rangeStartV15===i),draggable:routeActionV15==='select',zIndexOffset:(i===0||i===editorV13.route.length-1)?1400:1050}).addTo(routeMapV11);m._routeIndexV15=i;m.on('dragstart',()=>{pushHistoryV13();dragBaseV15=cloneV13(editorV13.route)});m.on('drag',ev=>{const ll=ev.target.getLatLng();editorV13.route[i]=[ll.lat,ll.lng];syncEndpointCpV15(i,ll);updateRouteGeomV15()});m.on('dragend',()=>{dragBaseV15=null;saveEditorV13();setSelectedV15({type:'vertex',index:i});refreshPanelV15();toast('Точка перемещена')});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);if(routeActionV15==='path')return chooseRangeAnchorV15(i);setSelectedV15({type:'vertex',index:i})});routeVertexLayersV13.push(m)})}
 }
 const cps=dynamicCpsV13();cps.forEach(cp=>{const interactive=!editorModeV13||editorToolV13==='cp',m=L.marker([cp.lat,cp.lon],{icon:iconCpV13(cp.number,selectedV13?.type==='cp'&&selectedV13.id===cp.id),draggable:editorModeV13&&editorToolV13==='cp',interactive,zIndexOffset:editorToolV13==='cp'?1300:700}).addTo(routeMapV11);m.bindTooltip(`${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':'КП '+cp.number} · ${cp.title} · ${gridCodeDynamicV13(cp.lat,cp.lon)}`,{direction:'top'});if(editorModeV13&&editorToolV13==='cp'){m.on('dragstart',()=>pushHistoryV13());m.on('dragend',ev=>{const ll=ev.target.getLatLng(),obj=editorV13.cps.find(x=>x.id===cp.id);if(!obj)return;obj.lat=ll.lat;obj.lon=ll.lng;if(cp.id==='cp0'){editorV13.route[0]=[ll.lat,ll.lng];if(editorV13.loopLocked!==false){editorV13.route[editorV13.route.length-1]=[ll.lat,ll.lng];const f=editorV13.cps.find(x=>x.id==='cpf');if(f){f.lat=ll.lat;f.lon=ll.lng}}}if(cp.id==='cpf'){editorV13.route[editorV13.route.length-1]=[ll.lat,ll.lng];if(editorV13.loopLocked!==false){editorV13.route[0]=[ll.lat,ll.lng];const s=editorV13.cps.find(x=>x.id==='cp0');if(s){s.lat=ll.lat;s.lon=ll.lng}}}saveEditorV13();drawRouteV15();setSelectedV15({type:'cp',id:cp.id});toast('КП перемещена')});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);setSelectedV15({type:'cp',id:cp.id})})}cpLayersV13[cp.id]=m})
 if(selectedV13?.type==='segment')showMidV15(selectedV13.index)
}
drawRouteV13=drawRouteV15;

function insertPointAtV15(seg,lat,lon){pushHistoryV13();editorV13.route.splice(seg+1,0,[lat,lon]);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;next[n>seg?n+1:n]=v});next[seg+1]=next[seg]||'unknown';editorV13.terrain=next;saveEditorV13();return seg+1}
function addPointMapV15(lat,lon){const n=nearestRouteV13(lat,lon);if(!n)return;const idx=insertPointAtV15(n.seg,lat,lon);routeActionV15='select';drawRouteV15();setSelectedV15({type:'vertex',index:idx});toast('Точка маршрута добавлена')}
function splitSegmentV15(i){const a=editorV13.route[i],b=editorV13.route[i+1];if(!a||!b)return;const idx=insertPointAtV15(i,(a[0]+b[0])/2,(a[1]+b[1])/2);drawRouteV15();setSelectedV15({type:'vertex',index:idx});toast('Добавлена точка — теперь её можно точно сместить')}
function deletePointV15(i){if(i<=0||i>=editorV13.route.length-1){toast('Старт и финиш можно двигать, но не удалять');return}pushHistoryV13();editorV13.route.splice(i,1);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n===i)return;next[n>i?n-1:n]=v});editorV13.terrain=next;saveEditorV13();selectedV13=null;drawRouteV15();refreshPanelV15();toast('Точка маршрута удалена')}
function applyPointCoordsV15(i){const lat=+document.getElementById('vertexLatV15')?.value,lon=+document.getElementById('vertexLonV15')?.value;if(!Number.isFinite(lat)||!Number.isFinite(lon)){toast('Проверь координаты');return}pushHistoryV13();editorV13.route[i]=[lat,lon];syncEndpointCpV15(i,{lat,lng:lon});saveEditorV13();drawRouteV15();setSelectedV15({type:'vertex',index:i});toast('Координаты точки обновлены')}
function applyCpV15(id){const cp=editorV13.cps.find(x=>x.id===id);if(!cp)return;const title=document.getElementById('cpTitleV15')?.value.trim(),stop=+document.getElementById('cpStopV15')?.value||0,lat=+document.getElementById('cpLatV15')?.value,lon=+document.getElementById('cpLonV15')?.value;if(!title||!Number.isFinite(lat)||!Number.isFinite(lon)){toast('Проверь название и координаты');return}pushHistoryV13();Object.assign(cp,{title,stopMin:stop,lat,lon});if(id==='cp0'){editorV13.route[0]=[lat,lon];if(editorV13.loopLocked!==false){editorV13.route[editorV13.route.length-1]=[lat,lon];const f=editorV13.cps.find(x=>x.id==='cpf');if(f){f.lat=lat;f.lon=lon}}}if(id==='cpf'){editorV13.route[editorV13.route.length-1]=[lat,lon];if(editorV13.loopLocked!==false){editorV13.route[0]=[lat,lon];const s=editorV13.cps.find(x=>x.id==='cp0');if(s){s.lat=lat;s.lon=lon}}}saveEditorV13();drawRouteV15();setSelectedV15({type:'cp',id});toast('КП обновлена')}
function deleteCpV15(id){const cp=editorV13.cps.find(x=>x.id===id);if(!cp||cp.locked){toast('Старт и финиш удалять нельзя');return}pushHistoryV13();editorV13.cps=editorV13.cps.filter(x=>x.id!==id);saveEditorV13();selectedV13=null;drawRouteV15();refreshPanelV15();toast('КП удалена')}
function addCpMapV15(lat,lon){pushHistoryV13();const id='u'+Date.now();editorV13.cps.push({id,title:'Новая контрольная точка',lat,lon,stopMin:0,locked:false});saveEditorV13();drawRouteV15();setSelectedV15({type:'cp',id});toast('КП добавлена — координаты уже рассчитаны')}

function chooseRangeAnchorV15(i){if(rangeStartV15===null){rangeStartV15=i;selectedV13={type:'vertex',index:i};refreshSelectionV15();refreshPanelV15();toast('Начало выбрано. Теперь выбери конец участка.');return}if(i===rangeStartV15){rangeStartV15=null;refreshSelectionV15();refreshPanelV15();return}const a=rangeStartV15,b=i;rangeStartV15=null;routeRangeBrouterV15(a,b)}
function chooseRangeOnSegmentV15(i,ll){const idx=insertPointAtV15(i,ll.lat,ll.lng);drawRouteV15();chooseRangeAnchorV15(idx)}
async function fetchBrouterV15(a,b){const u=`https://brouter.de/brouter?lonlats=${a[1]},${a[0]}%7C${b[1]},${b[0]}&profile=trekking&alternativeidx=0&format=geojson`,r=await fetch(u);if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),c=j?.features?.[0]?.geometry?.coordinates||j?.geometry?.coordinates;if(!Array.isArray(c)||c.length<2)throw new Error('no geometry');return c.map(x=>[+x[1],+x[0]])}
async function routeRangeBrouterV15(i1,i2){if(lastBrouterPendingV13)return;let a=Math.min(i1,i2),b=Math.max(i1,i2);if(b-a<1)return;lastBrouterPendingV13=true;toast('Прокладываю выбранный фрагмент по дорогам и тропам OSM…');try{const repl=await fetchBrouterV15(editorV13.route[a],editorV13.route[b]);pushHistoryV13();const oldCount=b-a+1,delta=repl.length-oldCount,next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n<a)next[n]=v;else if(n>=b)next[n+delta]=v});for(let n=a;n<a+repl.length-1;n++)next[n]='trail';editorV13.route.splice(a,oldCount,...repl);editorV13.terrain=next;saveEditorV13();routeActionV15='select';selectedV13={type:'segment',index:a};drawRouteV15();refreshPanelV15();toast('Фрагмент перестроен по OSM. Если не подходит — ↶')}catch(e){routeActionV15='select';toast('OSM не смог построить этот фрагмент. Маршрут не изменён.')}finally{lastBrouterPendingV13=false;rangeStartV15=null}}
async function routeOneSegmentV15(i){return routeRangeBrouterV15(i,i+1)}

function panelV15(){if(!editorModeV13)return editorPanelV13();let sel='';if(selectedV13?.type==='vertex'){const i=selectedV13.index,p=editorV13.route[i],end=i===0?'Старт':i===editorV13.route.length-1?'Финиш':`Точка ${i+1}`;sel=`<div class="editor-card-v13"><small>${end}</small><strong id="pointCoordsV15">${p[0].toFixed(6)}, ${p[1].toFixed(6)}</strong><div class="coord-grid-v15"><label>Широта<input id="vertexLatV15" type="number" step="0.000001" value="${p[0].toFixed(6)}"></label><label>Долгота<input id="vertexLonV15" type="number" step="0.000001" value="${p[1].toFixed(6)}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" data-save-point-v15="${i}">Применить координаты</button><button class="btn alt sm" data-delete-point-v15="${i}" ${i===0||i===editorV13.route.length-1?'disabled':''}>Удалить точку</button></div>${(i===0||i===editorV13.route.length-1)?`<label class="loop-toggle-v15"><input id="loopLockV15" type="checkbox" ${editorV13.loopLocked!==false?'checked':''}><span><b>Старт и финиш совпадают</b><small>При перемещении одной конечной точки вторая двигается вместе с ней.</small></span></label>`:''}<div class="editor-help-v15">Перетаскивание двигает только эту точку. Соседние точки маршрута больше не смещаются автоматически.</div></div>`}
else if(selectedV13?.type==='segment'){const i=selectedV13.index,t=editorV13.terrain[i]||'unknown',a=editorV13.route[i],b=editorV13.route[i+1];sel=`<div class="editor-card-v13"><small>Участок ${i+1}</small><strong>${(havV13(a,b)*DISTANCE_CAL_V13/1000).toFixed(2).replace('.',',')} км</strong><label>Тип движения<select data-terrain-v15="${i}">${Object.entries(TERRAIN_V13).map(([k,v])=>`<option value="${k}" ${k===t?'selected':''}>${v.label}</option>`).join('')}</select></label><div class="editor-inline-v13"><button class="btn sand sm" data-route-one-v15="${i}">По тропе этот участок</button><button class="btn alt sm" data-split-v15="${i}">+ Точка в середине</button></div><div class="editor-help-v15">Для длинного фрагмента включи сверху «По тропе A→B» и укажи начало и конец на карте.</div></div>`}
else if(selectedV13?.type==='cp'){const cp=editorV13.cps.find(x=>x.id===selectedV13.id),d=dynamicCpsV13().find(x=>x.id===selectedV13.id);if(cp)sel=`<div class="editor-card-v13"><small>${d?.number==='С'?'Старт':d?.number==='Ф'?'Финиш':`КП ${d?.number||''}`} · ${gridCodeDynamicV13(cp.lat,cp.lon)}</small><label>Название<input id="cpTitleV15" value="${esc(cp.title)}"></label><label>Остановка, мин<input id="cpStopV15" type="number" min="0" max="240" value="${cp.stopMin||0}"></label><div class="coord-grid-v15"><label>Широта<input id="cpLatV15" type="number" step="0.000001" value="${cp.lat.toFixed(6)}"></label><label>Долгота<input id="cpLonV15" type="number" step="0.000001" value="${cp.lon.toFixed(6)}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" data-save-cp-v15="${cp.id}">Сохранить КП</button><button class="btn alt sm" data-delete-cp-v15="${cp.id}" ${cp.locked?'disabled':''}>Удалить КП</button></div><p>${d?`${d.km.toFixed(1).replace('.',',')} км от старта · ETA ${d.arrival}`:''}</p></div>`}
else if(editorToolV13==='grid')return editorPanelV13();
const empty=`<div class="editor-empty-v13"><strong>${editorToolV13==='route'?'Выбери точку или участок':editorToolV13==='cp'?'Добавь или выбери КП':'Сетка'}</strong><p>${editorToolV13==='route'?(routeActionV15==='add'?'Клик по карте добавит одну точку маршрута.':'Ничего не двигается само: выбери белую точку и перетащи её.'):editorToolV13==='cp'?'Клик по карте добавит КП точно в выбранных координатах.':'Настрой сетку.'}</p></div>`;return `<div class="editor-summary-v13"><div class="editor-stat-v13"><span>Длина</span><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div class="editor-stat-v13"><span>Финиш</span><strong>${finalEtaV13()}</strong></div><div class="editor-stat-v13"><span>КП</span><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong></div></div>${sel||empty}`}
editorPanelV13=panelV15;

function toolbarV15(){return `<div class="editor-toolbar-v15">${!editorModeV13?`<button class="btn sand" id="beginEditV15">Редактировать маршрут</button>`:`<span class="editor-state-v15 ${editDirtyV15?'dirty':''}" id="editorStateV15">${editDirtyV15?'Есть несохранённые изменения':'Изменений нет'}</span><button class="btn editor-save-v15" id="saveEditV15">Сохранить изменения</button><button class="btn alt editor-discard-v15" id="discardEditV15">Не сохранять</button><button class="icon-btn" id="undoV15" ${undoV13.length?'':'disabled'} title="Отменить">↶</button><button class="icon-btn" id="redoV15" ${redoV13.length?'':'disabled'} title="Повторить">↷</button><button class="btn alt" id="resetPdfV15">Вернуть PDF</button>`}<button class="btn alt" id="gpxV15">GPX</button><button class="btn alt" id="pdfV15">PDF / печать</button></div>`}
editorToolbarV13=toolbarV15;
function toolstripV15(){if(!editorModeV13)return '';const hint=editorToolV13==='route'?(routeActionV15==='add'?'Добавление одной точки: кликни в нужном месте на карте.':routeActionV15==='path'?(rangeStartV15===null?'По тропе A→B: выбери начало на линии или белой точке.':'Начало выбрано. Теперь укажи конец фрагмента.'):'Выбор: двигай одну белую точку или кликни по участку. Ничего соседнее не двигается.'):(editorToolV13==='cp'?'КП: клик по карте добавляет точку; существующую можно перетащить.':'Сетка: размер и смещение настраиваются справа.');return `<div class="route-toolstrip-v15"><div class="route-toolgroup-v15"><button class="route-tool-v15 ${editorToolV13==='route'?'active':''}" data-tool-v15="route">Линия</button><button class="route-tool-v15 ${editorToolV13==='cp'?'active':''}" data-tool-v15="cp">КП</button><button class="route-tool-v15 ${editorToolV13==='grid'?'active':''}" data-tool-v15="grid">Сетка</button></div>${editorToolV13==='route'?`<div class="route-toolgroup-v15"><button class="route-tool-v15 ${routeActionV15==='select'?'active':''}" data-action-v15="select">Выбрать / двигать</button><button class="route-tool-v15 ${routeActionV15==='add'?'active':''}" data-action-v15="add">+ Точка</button><button class="route-tool-v15 path ${routeActionV15==='path'?'active':''}" data-action-v15="path">По тропе A→B</button></div>`:''}<div class="route-hint-v15">${rangeStartV15!==null?`<span class="path-progress-v15">A выбрана · точка ${rangeStartV15+1}</span> `:''}${hint}</div></div>`}

function refreshPanelV15(){const p=document.getElementById('editorPanelV15');if(p){p.innerHTML=panelV15();bindPanelV15()}const l=document.getElementById('routeLenV15');if(l)l.textContent=`${(routeLenV13()/1000).toFixed(1).replace('.',',')} км`;const f=document.getElementById('routeFinishV15');if(f)f.textContent=finalEtaV13();const c=document.getElementById('routeCpCountV15');if(c)c.textContent=String(dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length);dirtyV15()}
function bindPanelV15(){document.querySelectorAll('[data-save-point-v15]').forEach(b=>b.onclick=()=>applyPointCoordsV15(+b.dataset.savePointV15));document.querySelectorAll('[data-delete-point-v15]').forEach(b=>b.onclick=()=>deletePointV15(+b.dataset.deletePointV15));document.querySelectorAll('[data-split-v15]').forEach(b=>b.onclick=()=>splitSegmentV15(+b.dataset.splitV15));document.querySelectorAll('[data-route-one-v15]').forEach(b=>b.onclick=()=>routeOneSegmentV15(+b.dataset.routeOneV15));document.querySelectorAll('[data-terrain-v15]').forEach(s=>s.onchange=()=>{pushHistoryV13();editorV13.terrain[+s.dataset.terrainV15]=s.value;saveEditorV13();drawRouteV15();setSelectedV15({type:'segment',index:+s.dataset.terrainV15})});document.querySelectorAll('[data-save-cp-v15]').forEach(b=>b.onclick=()=>applyCpV15(b.dataset.saveCpV15));document.querySelectorAll('[data-delete-cp-v15]').forEach(b=>b.onclick=()=>deleteCpV15(b.dataset.deleteCpV15));document.getElementById('loopLockV15')?.addEventListener('change',e=>{editorV13.loopLocked=e.target.checked;saveEditorV13();refreshPanelV15()});bindPanelV14()}

function mountMapV15(){const el=document.getElementById('routeMapFinal');if(!el)return;if(routeMapV11){try{routeMapV11.remove()}catch(e){}routeMapV11=null;routeLayerV11=null;routeMarkersV11={}}dynamicGridLayerV13=null;dynamicGridSelectedV13=null;if(!window.L){el.innerHTML=`<div class="map-fallback-v11">${mapSvgV10()}<small>Онлайн-карта недоступна.</small></div>`;return}el.innerHTML='';routeMapV11=L.map(el,{zoomControl:true,attributionControl:true,preferCanvas:true,scrollWheelZoom:true,zoomSnap:.5,zoomDelta:.5,wheelPxPerZoomLevel:110,minZoom:12,maxZoom:19,fadeAnimation:false,markerZoomAnimation:false});routeLayerV11=makeTileV11(routeBaseV11).addTo(routeMapV11);if(gridEnabledV12){dynamicGridLayerV13=buildGridDynamicV13(routeMapV11);dynamicGridLayerV13.addTo(routeMapV11)}drawRouteV15();if(routeViewportV14){routeMapV11.setView([routeViewportV14.lat,routeViewportV14.lng],routeViewportV14.zoom,{animate:false});routeViewportV14=null}else routeMapV11.fitBounds(L.latLngBounds(editorV13.route),{padding:[34,34],animate:false});const Fit=L.Control.extend({onAdd(){const b=L.DomUtil.create('button','leaflet-bar fit-route-v11');b.type='button';b.innerHTML='⌂';b.title='Весь маршрут';L.DomEvent.disableClickPropagation(b);L.DomEvent.on(b,'click',()=>routeMapV11.fitBounds(L.latLngBounds(editorV13.route),{padding:[34,34],animate:true}));return b}});new Fit({position:'topleft'}).addTo(routeMapV11);routeMapV11.on('zoomend',()=>{if(editorModeV13&&editorToolV13==='route')drawRouteV15();if(gridEnabledV12)refreshGridV13()});routeMapV11.on('click',e=>{if(editorModeV13){if(editorToolV13==='cp')return addCpMapV15(e.latlng.lat,e.latlng.lng);if(editorToolV13==='route'&&routeActionV15==='add')return addPointMapV15(e.latlng.lat,e.latlng.lng);if(editorToolV13==='grid')return handleGridClickDynamicV13(e);if(editorToolV13==='route'&&routeActionV15==='select')return setSelectedV15(null)}else handleGridClickDynamicV13(e)});setTimeout(()=>routeMapV11&&routeMapV11.invalidateSize(false),100);updateGridStatusV13()}
mountRouteMapV13=mountMapV15;mountRouteMapV10=mountMapV15;

function routePageV15(){const body=routeModeV9==='points'?section('Контрольные точки',`<div class="cp-head"><span>КП</span><span>Точка</span><span>Км</span><span>ETA</span></div><div class="cp-list cp-list-v15">${cpRowsDynamicV13()}</div>`,'Координаты, километраж и ETA пересчитываются из текущей геометрии.'):routeModeV9==='navigation'?section('Переходы и азимуты',`<div class="navigation-note"><strong>Автопересчёт</strong><p>После сохранения маршрута расстояния, тип движения, ETA и азимуты используются в маршрутном бланке и PDF.</p></div><div class="nav-leg-list nav-leg-list-v15">${dynamicNavRowsV13()}</div>`):section('Полевой атлас и экспорт',`<div class="atlas-source"><div class="atlas-source__number">PDF</div><div><b>Редактор является источником атласа</b><p>Сохранённые линия, КП, сетка, скорости и остановки используются при формировании печатной версии.</p></div></div><div class="materials-list">${materialRowsV10()}</div>`);return `${pageHead('Навигация','Маршрут','Точное редактирование линии, контрольных точек и сетки с явным сохранением изменений.',toolbarV15())}${editorModeV13?`<div class="route-unsaved-banner-v15"><strong>Черновик:</strong> изменения не попадут в сохранённый маршрут, пока не нажмёшь «Сохранить изменения».</div>`:''}${toolstripV15()}<div class="route-layout route-layout-v10 route-editor-layout-v13"><div class="route-map"><div class="route-map-head-v11"><div><small>${editorModeV13?'Редактор':'Маршрут'}</small><strong>Томинский лесопарк · <span id="routeLenV15">${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</span></strong></div><div class="map-controls-v12"><div class="map-layer-switch-v11"><button type="button" data-map-layer-v11="osm" class="${routeBaseV11==='osm'?'active':''}">Карта</button><button type="button" data-map-layer-v11="sat" class="${routeBaseV11==='sat'?'active':''}">Спутник</button></div><button type="button" class="grid-toggle-v12 ${gridEnabledV12?'active':''}" data-grid-toggle-v12>Сетка ${gridCfgV13().cell} м</button></div></div><div class="map-shell-v11"><div id="routeMapFinal" class="leaflet-map leaflet-map-v11 ${routeActionV15==='path'?'edit-path-v15':''}"></div><div class="route-loading-v11">Загрузка подложки…</div></div><div class="route-map-foot-v11"><span>Колесо — масштаб</span><span>⌂ — весь маршрут</span><span>${editorModeV13?'Белые точки — узлы линии':'Клик по КП в списке — перейти'}</span></div></div><aside class="route-summary route-editor-panel-v15"><div id="editorPanelV15">${panelV15()}</div></aside></div><div class="segmented route-tabs"><button class="${routeModeV9==='points'?'active':''}" data-route-v9="points">КП</button><button class="${routeModeV9==='navigation'?'active':''}" data-route-v9="navigation">Навигация</button><button class="${routeModeV9==='atlas'?'active':''}" data-route-v9="atlas">Атлас</button></div>${body}`}
routePage=routePageV15;

function routeSheetRowsV15(){const cps=dynamicCpsV13();return cps.map((cp,i)=>{const prev=i?cps[i-1]:null,next=i<cps.length-1?cps[i+1]:null,leg=prev?Math.max(0,cp.km-prev.km):0,az=next?Math.round(bearingV13([cp.lat,cp.lon],[next.lat,next.lon])):null;return `<tr><td class="num">${cp.number}</td><td><b>${esc(cp.title)}</b><small>${gridCodeDynamicV13(cp.lat,cp.lon)}</small></td><td>${leg?leg.toFixed(1).replace('.',','):'—'} км</td><td>${cp.km.toFixed(1).replace('.',',')} км</td><td><b>${cp.arrival}</b>${cp.stopMin?`<small>стоп ${cp.stopMin} мин</small>`:''}</td><td>${az===null?'—':az+'°'}</td><td class="coords">${cp.lat.toFixed(6)}, ${cp.lon.toFixed(6)}</td></tr>`}).join('')}
function planPageV15(){const timeline=`<div class="timeline-head"><span>Время</span><span>Этап</span><span>Ответственный</span><span>Маршрут</span><span></span></div>${S.timeline.map(t=>`<div class="timeline-row"><div class="timeline-time">${esc(t.time)}</div><div><b>${esc(t.title)}</b><small>${esc(t.note||'')}</small></div><div>${esc(pn(t.owner))}</div><div>${t.route?esc(routeName(t.route)):'—'}</div><div class="row-actions"><button class="icon-btn" data-edit-time="${t.id}" title="Редактировать">✎</button><button class="icon-btn" data-del-time="${t.id}" title="Удалить">×</button></div></div>`).join('')}`;return `${pageHead('Расчёт маршрута','План','Маршрутный бланк строится автоматически из сохранённой линии, КП, скоростей и остановок.',`<button class="btn sand" id="addTimeline">Добавить орг. этап</button>`)}<div class="plan-auto-summary-v13"><div><small>Старт</small><strong>${editorV13.start}</strong></div><div><small>Финиш</small><strong>${finalEtaV13()}</strong></div><div><small>Длина</small><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div><small>КП</small><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong></div></div>${section('Параметры расчёта',`<div class="route-plan-controls-v15"><div class="route-plan-start-v15"><label>Время старта<input type="time" id="routeStartV15" value="${editorV13.start}"></label></div><div class="speed-row-v15">${Object.entries(TERRAIN_V13).map(([k,v])=>`<label><span>${v.label}</span><input type="number" min="0.5" max="8" step="0.1" data-speed-v15="${k}" value="${editorV13.speeds[k]??v.speed}"></label>`).join('')}</div></div>`,'Скорость задаётся в км/ч. Время каждой КП учитывает длину участков и остановки.')}${section('Маршрутный бланк',`<div class="route-form-v15"><table class="route-form-table-v15"><thead><tr><th>КП</th><th>Точка / квадрат</th><th>От предыдущей</th><th>Всего</th><th>ETA / стоп</th><th>Азимут дальше</th><th>WGS84</th></tr></thead><tbody>${routeSheetRowsV15()}</tbody></table></div>`,'Эти же данные используются при экспорте печатного атласа.')}${section('Организационный таймлайн',timeline,'Это отдельный командный план. Маршрутный расчёт выше меняется автоматически.')}`}
planPage=planPageV15;

const bindV15Base=bind;bind=function(){bindV15Base();document.getElementById('beginEditV15')?.addEventListener('click',beginEditV15);document.getElementById('saveEditV15')?.addEventListener('click',saveAndExitV15);document.getElementById('discardEditV15')?.addEventListener('click',discardAndExitV15);document.getElementById('undoV15')?.addEventListener('click',()=>{undoEditorV13();dirtyV15()});document.getElementById('redoV15')?.addEventListener('click',()=>{redoEditorV13();dirtyV15()});document.getElementById('resetPdfV15')?.addEventListener('click',()=>{if(confirm('Вернуть черновик к исходному маршруту PDF?')){editorV13=defaultEditorV13();saveEditorV13();selectedV13=null;rangeStartV15=null;drawRouteV15();refreshPanelV15()}});document.getElementById('gpxV15')?.addEventListener('click',downloadEditedGpxV13);document.getElementById('pdfV15')?.addEventListener('click',openAtlasPrintV13);document.querySelectorAll('[data-tool-v15]').forEach(b=>b.onclick=()=>{editorToolV13=b.dataset.toolV15;routeActionV15='select';rangeStartV15=null;selectedV13=null;renderPreserveV14()});document.querySelectorAll('[data-action-v15]').forEach(b=>b.onclick=()=>{routeActionV15=b.dataset.actionV15;rangeStartV15=null;selectedV13=null;renderPreserveV14()});bindPanelV15();document.querySelectorAll('[data-cp-dyn-v13]').forEach(b=>b.onclick=()=>{const cp=editorV13.cps.find(x=>x.id===b.dataset.cpDynV13);if(cp&&routeMapV11){routeMapV11.setView([cp.lat,cp.lon],15,{animate:true});setSelectedV15({type:'cp',id:cp.id})}});document.getElementById('routeStartV15')?.addEventListener('change',e=>{editorV13.start=e.target.value||'10:00';saveEditorV13();render();toast('Время старта обновлено')});document.querySelectorAll('[data-speed-v15]').forEach(i=>i.onchange=()=>{editorV13.speeds[i.dataset.speedV15]=Math.max(.5,Math.min(8,+i.value||4));saveEditorV13();render();toast('Скорость обновлена')});document.querySelectorAll('[data-grid-toggle-v12]').forEach(b=>b.onclick=()=>{gridEnabledV12=!gridEnabledV12;refreshGridV13();b.classList.toggle('active',gridEnabledV12)});document.querySelectorAll('[data-map-layer-v11]').forEach(b=>b.onclick=()=>{const kind=b.dataset.mapLayerV11;if(kind===routeBaseV11)return;replaceBaseV11(routeMapV11,document.querySelector('.map-shell-v11'),kind,false);document.querySelectorAll('[data-map-layer-v11]').forEach(x=>x.classList.toggle('active',x.dataset.mapLayerV11===kind))});if(tab==='route')requestAnimationFrame(mountMapV15)};

if(editorV13.loopLocked===undefined)editorV13.loopLocked=true;
const buildV15=document.querySelector('.build-label');if(buildV15)buildV15.textContent='V9 · точный редактор / сохранить или отменить';
render();
