function smoothDragRouteV14(i,ll){
  if(!dragRouteBaseV14)return;const base=dragRouteBaseV14,old=base[i],dLat=ll.lat-old[0],dLon=ll.lng-old[1],z=routeMapV11?.getZoom()||15,r=z>=17?2:z>=16?3:z>=15?4:6,last=base.length-1;
  for(let j=Math.max(0,i-r);j<=Math.min(last,i+r);j++){if((j===0||j===last)&&j!==i)continue;const dist=Math.abs(j-i),w=Math.cos((dist/(r+1))*Math.PI/2)**2;editorV13.route[j]=[base[j][0]+dLat*w,base[j][1]+dLon*w]}
  updateRouteGeometryV14();
}
function updateRouteGeometryV14(){
  routeSegLayersV13.forEach((seg,i)=>{if(editorV13.route[i+1])seg.setLatLngs([editorV13.route[i],editorV13.route[i+1]])});
  routeVertexLayersV13.forEach(m=>{const i=m._routeIndexV14;if(editorV13.route[i])m.setLatLng(editorV13.route[i])});
}
function updateCpMarkersV14(){const d=dynamicCpsV13();d.forEach(cp=>{const m=cpLayersV13[cp.id];if(m){m.setLatLng([cp.lat,cp.lon]);m.setIcon(iconCpV13(cp.number,selectedV13?.type==='cp'&&selectedV13.id===cp.id));m.setTooltipContent(`${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':'КП '+cp.number} · ${cp.title} · ${gridCodeDynamicV13(cp.lat,cp.lon)}`)}})}
function visibleVertexStepV14(){const z=routeMapV11?.getZoom()||15;return z>=17?1:z>=16?2:z>=15?4:8}
function drawRouteV14(){
  if(!routeMapV11)return;clearEditLayersV13();
  if(!editorModeV13){routeLineV13=L.polyline(editorV13.route,{color:'#6c22c7',weight:4,opacity:.98,lineJoin:'round',lineCap:'round',smoothFactor:.1,interactive:false}).addTo(routeMapV11)}else{
    for(let i=0;i<editorV13.route.length-1;i++){const seg=L.polyline([editorV13.route[i],editorV13.route[i+1]],{color:routeColorV13(i),weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:selectedV13?.type==='segment'&&selectedV13.index!==i?.65:.95,interactive:editorToolV13==='route',bubblingMouseEvents:false}).addTo(routeMapV11);seg.on('click',e=>{if(editorToolV13!=='route')return;L.DomEvent.stopPropagation(e);routeActionV14='select';setSelectedV14({type:'segment',index:i})});routeSegLayersV13.push(seg)}
    if(editorToolV13==='route'&&routeMapV11.getZoom()>=ROUTE_HANDLE_MIN_Z_V14){const step=visibleVertexStepV14();editorV13.route.forEach((p,i)=>{if(i!==0&&i!==editorV13.route.length-1&&i%step!==0&&selectedV13?.index!==i)return;const m=L.marker(p,{icon:iconVertexV13(selectedV13?.type==='vertex'&&selectedV13.index===i),draggable:routeActionV14==='select',zIndexOffset:500}).addTo(routeMapV11);m._routeIndexV14=i;m.on('dragstart',()=>{pushHistoryV13();dragRouteBaseV14=cloneV13(editorV13.route)});m.on('drag',ev=>smoothDragRouteV14(i,ev.target.getLatLng()));m.on('dragend',()=>{dragRouteBaseV14=null;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();setSelectedV14({type:'vertex',index:i});updateCpMarkersV14();refreshEditorPanelV14()});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);setSelectedV14({type:'vertex',index:i})});routeVertexLayersV13.push(m)})}
  }
  const cps=dynamicCpsV13();cps.forEach(cp=>{const label=cp.number,m=L.marker([cp.lat,cp.lon],{icon:iconCpV13(label,selectedV13?.type==='cp'&&selectedV13.id===cp.id),draggable:editorModeV13&&editorToolV13==='cp',zIndexOffset:800}).addTo(routeMapV11);m.bindTooltip(`${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':'КП '+cp.number} · ${cp.title} · ${gridCodeDynamicV13(cp.lat,cp.lon)}`,{direction:'top'});if(editorModeV13){m.on('dragstart',()=>pushHistoryV13());m.on('dragend',ev=>{const ll=ev.target.getLatLng(),obj=editorV13.cps.find(x=>x.id===cp.id);if(obj){if(editorV13.snapCps){const n=nearestRouteV13(ll.lat,ll.lng);obj.lat=n.lat;obj.lon=n.lon}else{obj.lat=ll.lat;obj.lon=ll.lng}saveEditorV13();setSelectedV14({type:'cp',id:cp.id});refreshEditorPanelV14()}});m.on('click',ev=>{L.DomEvent.stopPropagation(ev);setSelectedV14({type:'cp',id:cp.id})})}cpLayersV13[cp.id]=m})
}
drawRouteV13=drawRouteV14;
function mountRouteMapV14(){
  const el=document.getElementById('routeMapFinal');if(!el)return;if(routeMapV11){try{routeMapV11.remove()}catch(e){}routeMapV11=null;routeLayerV11=null;routeMarkersV11={}}dynamicGridLayerV13=null;dynamicGridSelectedV13=null;if(!window.L){el.innerHTML=`<div class="map-fallback-v11">${mapSvgV10()}<small>Онлайн-карта недоступна.</small></div>`;return}el.innerHTML='';routeMapV11=L.map(el,{zoomControl:true,attributionControl:true,preferCanvas:true,scrollWheelZoom:true,zoomSnap:.5,zoomDelta:.5,wheelPxPerZoomLevel:110,minZoom:12,maxZoom:19,fadeAnimation:false,markerZoomAnimation:false});routeLayerV11=makeTileV11(routeBaseV11).addTo(routeMapV11);if(gridEnabledV12){dynamicGridLayerV13=buildGridDynamicV13(routeMapV11);dynamicGridLayerV13.addTo(routeMapV11)}drawRouteV14();if(routeViewportV14){routeMapV11.setView([routeViewportV14.lat,routeViewportV14.lng],routeViewportV14.zoom,{animate:false});routeViewportV14=null}else routeMapV11.fitBounds(L.latLngBounds(editorV13.route),{padding:[34,34],animate:false});const Fit=L.Control.extend({onAdd:function(){const b=L.DomUtil.create('button','leaflet-bar fit-route-v11');b.type='button';b.innerHTML='⌂';b.title='Показать весь маршрут';L.DomEvent.disableClickPropagation(b);L.DomEvent.on(b,'click',()=>routeMapV11.fitBounds(L.latLngBounds(editorV13.route),{padding:[34,34],animate:true}));return b}});new Fit({position:'topleft'}).addTo(routeMapV11);
  routeMapV11.on('zoomend',()=>{if(editorModeV13&&editorToolV13==='route')drawRouteV14();if(gridEnabledV12)refreshGridV13()});
  routeMapV11.on('click',e=>{if(editorModeV13){if(editorToolV13==='cp')return addCpV14(e.latlng.lat,e.latlng.lng);if(editorToolV13==='route'&&routeActionV14==='add')return insertRoutePointV14(e.latlng.lat,e.latlng.lng);if(editorToolV13==='grid')return handleGridClickDynamicV13(e);if(editorToolV13==='route'&&routeActionV14==='select')return setSelectedV14(null)}else handleGridClickDynamicV13(e)});
  routeMapV11.on('popupopen',ev=>{const btn=ev.popup.getElement()?.querySelector('[data-copy-grid-v13]');if(btn)btn.onclick=()=>{navigator.clipboard?.writeText(btn.dataset.copyGridV13);toast(`Скопировано: ${btn.dataset.copyGridV13}`)}});setTimeout(()=>routeMapV11&&routeMapV11.invalidateSize(false),100);updateGridStatusV13();
}
mountRouteMapV13=mountRouteMapV14;mountRouteMapV10=mountRouteMapV14;

function redrawAllV14(){drawRouteV14();refreshEditorPanelV14();markSavedV14()}
insertRoutePointV14=function(lat,lon){const n=nearestRouteV13(lat,lon);if(!n)return;pushHistoryV13();editorV13.route.splice(n.seg+1,0,[lat,lon]);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const i=+k;next[i>n.seg?i+1:i]=v});next[n.seg+1]=next[n.seg]||'unknown';editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13={type:'vertex',index:n.seg+1};routeActionV14='select';redrawAllV14();updateCpMarkersV14();toast('Узел добавлен')}
function splitSegmentV14(i){const a=editorV13.route[i],b=editorV13.route[i+1];if(!a||!b)return;insertRoutePointV14((a[0]+b[0])/2,(a[1]+b[1])/2)}
addCpV14=function(lat,lon){pushHistoryV13();let p={lat,lon};if(editorV13.snapCps){const n=nearestRouteV13(lat,lon);p={lat:n.lat,lon:n.lon}}const id='u'+Date.now();editorV13.cps.push({id,title:'Новая контрольная точка',lat:p.lat,lon:p.lon,stopMin:0,locked:false});saveEditorV13();selectedV13={type:'cp',id};drawRouteV14();refreshEditorPanelV14();toast('КП добавлена — задай название')}
deleteVertexV13=function(i){if(i<=0||i>=editorV13.route.length-1){toast('Старт и финиш удалять нельзя');return}pushHistoryV13();editorV13.route.splice(i,1);const next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n===i)return;next[n>i?n-1:n]=v});editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13=null;redrawAllV14();updateCpMarkersV14();toast('Узел удалён')}
deleteCpV13=function(id){const cp=editorV13.cps.find(x=>x.id===id);if(!cp||cp.locked){toast('Старт / финиш удалять нельзя');return}pushHistoryV13();editorV13.cps=editorV13.cps.filter(x=>x.id!==id);saveEditorV13();selectedV13=null;redrawAllV14();toast('КП удалена')}
updateCpV13=function(id,patch){const cp=editorV13.cps.find(x=>x.id===id);if(!cp)return;pushHistoryV13();Object.assign(cp,patch);saveEditorV13();drawRouteV14();refreshEditorPanelV14();toast('КП обновлена')}
setTerrainV13=function(i,type){pushHistoryV13();editorV13.terrain[i]=type;saveEditorV13();drawRouteV14();setSelectedV14({type:'segment',index:i});refreshEditorPanelV14();toast(`Участок: ${TERRAIN_V13[type]?.label||type}`)}
undoEditorV13=function(){if(!undoV13.length)return;redoV13.push(cloneV13(editorV13));editorV13=undoV13.pop();saveEditorV13();selectedV13=null;redrawAllV14();refreshGridV13();toast('Отменено')}
redoEditorV13=function(){if(!redoV13.length)return;undoV13.push(cloneV13(editorV13));editorV13=redoV13.pop();saveEditorV13();selectedV13=null;redrawAllV14();refreshGridV13();toast('Повторено')}
resetEditorV13=function(){pushHistoryV13();editorV13=defaultEditorV13();saveEditorV13();selectedV13=null;routeActionV14='select';redrawAllV14();refreshGridV13();toast('Возвращена PDF-версия')}
async function routeSegmentBrouterV14(i){if(lastBrouterPendingV13)return;const a=editorV13.route[i],b=editorV13.route[i+1];if(!a||!b)return;lastBrouterPendingV13=true;toast('Строю выбранный участок по OSM…');try{const u=`https://brouter.de/brouter?lonlats=${a[1]},${a[0]}%7C${b[1]},${b[0]}&profile=trekking&alternativeidx=0&format=geojson`,r=await fetch(u);if(!r.ok)throw new Error();const j=await r.json(),coords=j?.features?.[0]?.geometry?.coordinates||j?.geometry?.coordinates;if(!Array.isArray(coords)||coords.length<2)throw new Error();pushHistoryV13();const repl=coords.map(c=>[+c[1],+c[0]]),delta=repl.length-2,next={};Object.entries(editorV13.terrain).forEach(([k,v])=>{const n=+k;if(n<i)next[n]=v;else if(n>i)next[n+delta]=v});for(let n=i;n<i+repl.length-1;n++)next[n]='trail';editorV13.route.splice(i,2,...repl);editorV13.terrain=next;if(editorV13.snapCps)snapAllCpsV13();saveEditorV13();selectedV13={type:'segment',index:i};redrawAllV14();updateCpMarkersV14();toast('Участок перестроен. ↶ отменит результат.')}catch(e){toast('Не удалось построить по OSM. Геометрия не изменена.')}finally{lastBrouterPendingV13=false}}
routeSegmentBrouterV13=routeSegmentBrouterV14;

const bindV14Base=bind;bind=function(){bindV14Base();
  document.getElementById('toggleEditorV14')?.addEventListener('click',()=>{editorModeV13=!editorModeV13;editorToolV13='route';routeActionV14='select';selectedV13=null;renderPreserveV14()});
  document.getElementById('undoV14')?.addEventListener('click',undoEditorV13);document.getElementById('redoV14')?.addEventListener('click',redoEditorV13);
  document.getElementById('exportAtlasV14')?.addEventListener('click',openAtlasPrintV13);document.getElementById('downloadGpxV14')?.addEventListener('click',downloadEditedGpxV13);
  document.getElementById('resetRouteV14')?.addEventListener('click',()=>{if(confirm('Вернуть маршрут, КП и сетку к исходной PDF-версии?'))resetEditorV13()});
  document.querySelectorAll('[data-tool-v14]').forEach(b=>b.onclick=()=>{editorToolV13=b.dataset.toolV14;routeActionV14='select';selectedV13=null;renderPreserveV14()});
  document.querySelectorAll('[data-action-v14]').forEach(b=>b.onclick=()=>{routeActionV14=b.dataset.actionV14;selectedV13=null;renderPreserveV14()});
  bindPanelV14();bindDynamicRowsV14();
};
const buildV14=document.querySelector('.build-label');if(buildV14)buildV14.textContent='V8 · удобный редактор маршрута';
render();
