function editorPanelV13(){
  if(!editorModeV13)return `<div class="metric"><small>Расчётная длина</small><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong><em>автопересчёт</em></div><div class="metric"><small>Расчётный финиш</small><strong>${finalEtaV13()}</strong><em>${fmtDurationV13(routeDurationMinV13())}</em></div><div class="metric"><small>КП</small><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong><em>можно редактировать</em></div><div class="metric"><small>Сетка</small><strong>${gridCfgV13().cell} × ${gridCfgV13().cell} м</strong><em>${editorV13.grid.offsetX||editorV13.grid.offsetY?'со смещением':'по PDF'}</em></div>`;
  let sel='';
  if(selectedV13?.type==='vertex'){const i=selectedV13.index,p=editorV13.route[i];sel=`<div class="editor-card-v13"><small>Узел маршрута · ${i+1}/${editorV13.route.length}</small><strong>${p[0].toFixed(6)}, ${p[1].toFixed(6)}</strong><p>Перетащи точку на карте или удали её.</p><button class="btn alt sm" data-delete-vertex-v13="${i}" ${i===0||i===editorV13.route.length-1?'disabled':''}>Удалить узел</button></div>`}
  else if(selectedV13?.type==='segment'){const i=selectedV13.index,t=editorV13.terrain[i]||'unknown',a=editorV13.route[i],b=editorV13.route[i+1];sel=`<div class="editor-card-v13"><small>Участок ${i+1}</small><strong>${(havV13(a,b)*DISTANCE_CAL_V13/1000).toFixed(2).replace('.',',')} км</strong><label>Тип движения<select data-terrain-v13="${i}">${Object.entries(TERRAIN_V13).map(([k,v])=>`<option value="${k}" ${k===t?'selected':''}>${v.label}</option>`).join('')}</select></label><div class="editor-inline-v13"><button class="btn sand sm" data-brouter-v13="${i}">Проложить по тропам OSM</button></div><p>Маршрутизация — подсказка. Если тропы в OSM нет или результат плохой, используй ручные узлы и «Отменить».</p></div>`}
  else if(selectedV13?.type==='cp'){const cp=editorV13.cps.find(x=>x.id===selectedV13.id),dyn=dynamicCpsV13().find(x=>x.id===selectedV13.id);if(cp)sel=`<div class="editor-card-v13"><small>${dyn?.number==='С'?'Старт':dyn?.number==='Ф'?'Финиш':`КП ${dyn?.number||''}`} · ${gridCodeDynamicV13(cp.lat,cp.lon)}</small><label>Название<input data-cp-title-v13="${cp.id}" value="${esc(cp.title)}"></label><label>Остановка, мин<input type="number" min="0" max="240" data-cp-stop-v13="${cp.id}" value="${cp.stopMin||0}"></label><div class="editor-inline-v13"><button class="btn sand sm" data-save-cp-v13="${cp.id}">Сохранить</button><button class="btn alt sm" data-delete-cp-v13="${cp.id}" ${cp.locked?'disabled':''}>Удалить</button></div><p>${dyn?`${dyn.km.toFixed(1).replace('.',',')} км · ETA ${dyn.arrival}`:''}</p></div>`}
  else if(editorToolV13==='grid'){const g=editorV13.grid;sel=`<div class="editor-card-v13"><small>Координатная сетка</small><label>Размер клетки<select id="gridCellV13">${[100,200,250,500].map(v=>`<option value="${v}" ${+g.cell===v?'selected':''}>${v} × ${v} м</option>`).join('')}<option value="custom" ${![100,200,250,500].includes(+g.cell)?'selected':''}>Свой размер</option></select></label><label>Свой размер, м<input id="gridCustomV13" type="number" min="50" max="1000" step="10" value="${+g.cell||200}"></label><div class="editor-grid2-v13"><label>Смещение X, м<input id="gridOffsetXV13" type="number" step="10" value="${+g.offsetX||0}"></label><label>Смещение Y, м<input id="gridOffsetYV13" type="number" step="10" value="${+g.offsetY||0}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" id="applyGridV13">Применить</button><button class="btn alt sm" id="resetGridV13">Вернуть PDF 200 м</button></div><p>Изменение размера или смещения меняет коды квадратов. Исходная привязка PDF всегда доступна через сброс.</p></div>`}
  return `<div class="editor-summary-v13"><div class="editor-stat-v13"><span>Длина</span><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div class="editor-stat-v13"><span>Финиш</span><strong>${finalEtaV13()}</strong></div><div class="editor-stat-v13"><span>КП</span><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong></div></div>${sel||`<div class="editor-empty-v13"><strong>${editorToolV13==='route'?'Редактор маршрута':editorToolV13==='cp'?'Добавление КП':'Редактор сетки'}</strong><p>${editorToolV13==='route'?'Кликни по участку или узлу. Клик по карте добавит узел маршрута.':editorToolV13==='cp'?'Кликни по карте — новая КП будет привязана к ближайшему участку маршрута.':'Настрой размер и смещение сетки справа.'}</p></div>`}`
}
function editorToolbarV13(){return `<div class="editor-toolbar-v13"><button class="btn ${editorModeV13?'sand':'alt'}" id="toggleEditorV13">${editorModeV13?'Завершить редактирование':'Редактировать маршрут'}</button>${editorModeV13?`<div class="editor-tools-v13"><button class="editor-tool-v13 ${editorToolV13==='route'?'active':''}" data-editor-tool-v13="route">Маршрут</button><button class="editor-tool-v13 ${editorToolV13==='cp'?'active':''}" data-editor-tool-v13="cp">+ КП</button><button class="editor-tool-v13 ${editorToolV13==='grid'?'active':''}" data-editor-tool-v13="grid">Сетка</button></div><button class="icon-btn" id="undoV13" ${undoV13.length?'':'disabled'} title="Отменить">↶</button><button class="icon-btn" id="redoV13" ${redoV13.length?'':'disabled'} title="Повторить">↷</button>`:''}${editorModeV13?`<button class="btn alt" id="resetRouteV13">Вернуть PDF</button>`:''}<button class="btn alt" id="downloadGpxV13">GPX</button><button class="btn alt" id="exportAtlasV13">PDF / печать</button></div>`}

function mountRouteMapV13(){const el=document.getElementById('routeMapFinal');if(!el)return;if(routeMapV11){try{routeMapV11.remove()}catch(e){}routeMapV11=null;routeLayerV11=null;routeMarkersV11={}}dynamicGridLayerV13=null;dynamicGridSelectedV13=null;if(!window.L){el.innerHTML=`<div class="map-fallback-v11">${mapSvgV10()}<small>Онлайн-карта недоступна.</small></div>`;return}el.innerHTML='';routeMapV11=L.map(el,{zoomControl:true,attributionControl:true,preferCanvas:true,scrollWheelZoom:true,zoomSnap:.5,zoomDelta:.5,wheelPxPerZoomLevel:110,minZoom:12,maxZoom:19,fadeAnimation:false,markerZoomAnimation:false});routeLayerV11=makeTileV11(routeBaseV11).addTo(routeMapV11);if(gridEnabledV12){dynamicGridLayerV13=buildGridDynamicV13(routeMapV11);dynamicGridLayerV13.addTo(routeMapV11)}drawRouteV13();fitRouteV11=function(map,animate=false){if(!map)return;map.fitBounds(L.latLngBounds(editorV13.route),{padding:[34,34],animate})};fitRouteV11(routeMapV11,false);const Fit=L.Control.extend({onAdd:function(){const b=L.DomUtil.create('button','leaflet-bar fit-route-v11');b.type='button';b.innerHTML='⌂';b.title='Показать весь маршрут';L.DomEvent.disableClickPropagation(b);L.DomEvent.on(b,'click',()=>fitRouteV11(routeMapV11,true));return b}});new Fit({position:'topleft'}).addTo(routeMapV11);
  routeMapV11.on('zoomend',()=>{if(editorModeV13&&editorToolV13==='route')drawRouteV13();if(gridEnabledV12)refreshGridV13()});
  routeMapV11.on('click',e=>{if(editorModeV13){if(editorToolV13==='cp')return addCpV13(e.latlng.lat,e.latlng.lng);if(editorToolV13==='route')return insertRoutePointV13(e.latlng.lat,e.latlng.lng);if(editorToolV13==='grid')return handleGridClickDynamicV13(e)}else handleGridClickDynamicV13(e)});
  routeMapV11.on('popupopen',ev=>{const btn=ev.popup.getElement()?.querySelector('[data-copy-grid-v13]');if(btn)btn.onclick=()=>{navigator.clipboard?.writeText(btn.dataset.copyGridV13);toast(`Скопировано: ${btn.dataset.copyGridV13}`)}});
  setTimeout(()=>routeMapV11&&routeMapV11.invalidateSize(false),100);updateGridStatusV13();
}
mountRouteMapV10=mountRouteMapV13;

function mountOverviewMapV13(){const el=document.getElementById('overviewMapV11');if(!el||!window.L)return;if(overviewMapV11){try{overviewMapV11.remove()}catch(e){}overviewMapV11=null;overviewLayerV11=null}overviewMapV11=L.map(el,{zoomControl:false,attributionControl:false,dragging:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false,touchZoom:false,zoomAnimation:false,fadeAnimation:false});overviewLayerV11=makeTileV11(overviewBaseV11).addTo(overviewMapV11);L.polyline(editorV13.route,{color:'#6c22c7',weight:4,opacity:.98,lineJoin:'round',lineCap:'round',smoothFactor:.1,interactive:false}).addTo(overviewMapV11);const cps=dynamicCpsV13(),key=cps.filter((x,i)=>x.number==='С'||x.number==='Ф'||i===4||i===7||i===11||i===16);key.forEach(cp=>L.circleMarker([cp.lat,cp.lon],{radius:cp.number==='С'?6:4,color:'#fff',weight:2,fillColor:cp.number==='С'?'#2f7a50':'#6c22c7',fillOpacity:1,interactive:false}).addTo(overviewMapV11));overviewMapV11.fitBounds(L.latLngBounds(editorV13.route),{padding:[20,20],animate:false});setTimeout(()=>overviewMapV11&&overviewMapV11.invalidateSize(false),100)}
mountOverviewMapV11=mountOverviewMapV13;
function downloadEditedGpxV13(){const pts=editorV13.route.map(p=>`<trkpt lat="${p[0].toFixed(7)}" lon="${p[1].toFixed(7)}"></trkpt>`).join(''),xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Разные люди — Походы" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>Томинский лесопарк — отредактированный маршрут</name><trkseg>${pts}</trkseg></trk></gpx>`,blob=new Blob([xml],{type:'application/gpx+xml'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='tomilinsky-route-edited.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

function routePageV13(){const body=routeModeV9==='points'?section('Контрольные точки',`<div class="cp-head"><span>КП</span><span>Точка</span><span>Км</span><span>ETA</span></div><div class="cp-list">${cpRowsDynamicV13()}</div>`,'Километраж и время пересчитываются из текущей геометрии маршрута.'):routeModeV9==='navigation'?section('Переходы и азимуты',`<div class="navigation-note"><strong>Автопересчёт</strong><p>Расстояние между КП считается вдоль маршрута, азимут — между самими контрольными точками. Тип движения задаётся по участкам в редакторе.</p></div><div class="nav-leg-list">${dynamicNavRowsV13()}</div>`,'После перемещения маршрута или КП значения обновляются автоматически.'):section('Полевой атлас и экспорт',`<div class="atlas-source"><div class="atlas-source__number">PDF</div><div><b>Маршрут → атлас</b><p>Кнопка «PDF / печать» формирует печатный атлас из текущего маршрута: обзор OSM, спутник, 8 секторных листов, таблица КП и навигационная шпаргалка.</p><p class="grid-note-v12">Это печатный HTML: в системном диалоге выбери «Сохранить как PDF» или принтер.</p></div></div><div class="materials-list">${materialRowsV10()}</div>`,'GPX/KML остаются справочными; источником текущего атласа становится редактор.');
  return `${pageHead('Навигация','Маршрут','Редактируй геометрию, КП и сетку прямо на карте. Длина, ETA, азимуты и печатный атлас пересчитываются автоматически.',editorToolbarV13())}<div class="route-source-banner-v11"><strong>${editorModeV13?'Режим редактирования':'Режим просмотра'}:</strong> ${editorModeV13?'маршрут сохраняется локально после каждого изменения. Используй ↶, если автопрокладка или ручная правка не подошла.':'нажми «Редактировать маршрут», чтобы двигать линию и контрольные точки.'}</div><div class="route-layout route-layout-v10 route-editor-layout-v13"><div class="route-map"><div class="route-map-head-v11"><div><small>${editorModeV13?'Редактор':'Финальная схема'}</small><strong>Томинский лесопарк · ${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div class="map-controls-v12"><div class="map-layer-switch-v11"><button type="button" data-map-layer-v11="osm" class="${routeBaseV11==='osm'?'active':''}">Карта</button><button type="button" data-map-layer-v11="sat" class="${routeBaseV11==='sat'?'active':''}">Спутник</button></div><button type="button" class="grid-toggle-v12 ${gridEnabledV12?'active':''}" data-grid-toggle-v12>Сетка ${gridCfgV13().cell} м</button></div></div><div class="map-shell-v11"><div id="routeMapFinal" class="leaflet-map leaflet-map-v11 ${editorModeV13?'editing-v13':''}"></div><div class="route-loading-v11">Загрузка подложки…</div><div class="route-legend-v13">${editorModeV13?Object.entries(TERRAIN_V13).map(([k,v])=>`<span><i style="background:${v.color}"></i>${v.label}</span>`).join(''):`<span><i style="background:#6c22c7"></i>маршрут</span>`}</div></div><div class="route-map-foot-v11"><span>Колесо — масштаб</span><span>⌂ — весь маршрут</span><span id="gridStatusV12">${gridEnabledV12?`Сетка ${gridCfgV13().cell}×${gridCfgV13().cell} м`:'Сетка выключена'}</span></div></div><aside class="route-summary route-editor-panel-v13">${editorPanelV13()}</aside></div><div class="segmented route-tabs"><button class="${routeModeV9==='points'?'active':''}" data-route-v9="points">КП</button><button class="${routeModeV9==='navigation'?'active':''}" data-route-v9="navigation">Навигация</button><button class="${routeModeV9==='atlas'?'active':''}" data-route-v9="atlas">Атлас</button></div>${body}`}
routePage=routePageV13;

function planPageV13(){const cps=dynamicCpsV13();return `${pageHead('Организация дня','План','Маршрутный таймлайн теперь рассчитывается из геометрии, типов участков и остановок.',`<button class="btn alt" id="openRouteEditorV13">Открыть редактор маршрута</button>`)}<div class="plan-auto-summary-v13"><div><small>Старт</small><strong>${editorV13.start}</strong></div><div><small>Финиш</small><strong>${finalEtaV13()}</strong></div><div><small>Длительность</small><strong>${fmtDurationV13(routeDurationMinV13())}</strong></div><div><small>Расстояние</small><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div></div>${section('Автоматический маршрутный план',`<div class="timeline-head"><span>Время</span><span>Точка</span><span>Км</span><span>Квадрат</span><span>Остановка</span></div>${cps.map(cp=>`<div class="timeline-row"><div class="timeline-time">${cp.arrival}</div><div><b>${cp.number==='С'?'Старт':cp.number==='Ф'?'Финиш':`КП ${cp.number} · ${esc(cp.title)}`}</b><small>${cp.lat.toFixed(6)}, ${cp.lon.toFixed(6)}</small></div><div>${cp.km.toFixed(1).replace('.',',')} км</div><div>${gridCodeDynamicV13(cp.lat,cp.lon)}</div><div>${cp.stopMin?`${cp.stopMin} мин`:'—'}</div></div>`).join('')}`,'Любая правка маршрута или КП автоматически меняет накопленный километраж и ETA.')}${section('Скоростные профили',`<div class="speed-grid-v13">${Object.entries(TERRAIN_V13).map(([k,v])=>`<label><span><i style="background:${v.color}"></i>${v.label}</span><input type="number" min="0.5" max="8" step="0.1" data-speed-v13="${k}" value="${+editorV13.speeds[k]||v.speed}"><em>км/ч</em></label>`).join('')}</div>`,'Скорость используется только для расчёта времени. Тип каждого участка задаётся в редакторе маршрута.')}`}
planPage=planPageV13;
