function gridCfgV13(){const cell=Math.max(50,Math.min(1000,+editorV13.grid.cell||200)),scale=cell/200,dx=GRID_DX_V12*scale,dy=GRID_DY_V12*scale,ox=(+editorV13.grid.offsetX||0)*(GRID_DX_V12/200),oy=(+editorV13.grid.offsetY||0)*(GRID_DY_V12/200),x0=GRID_X0_V12+ox,y1=GRID_Y1_V12+oy;return {cell,dx,dy,x0,y1}}
function rowCodeV13(i){const base=CYR_ROWS_V13.length;let n=i,s='';do{s=CYR_ROWS_V13[n%base]+s;n=Math.floor(n/base)-1}while(n>=0);return s}
function gridCellDynamicV13(lat,lon){const g=gridCfgV13(),x=mercXV12(lon),y=mercYV12(lat),col=Math.floor((x-g.x0)/g.dx),row=Math.floor((g.y1-y)/g.dy);if(col<0||row<0)return null;return {row,col,code:`${rowCodeV13(row)}${String(col+1).padStart(2,'0')}`}}
function gridCodeDynamicV13(lat,lon){return gridCellDynamicV13(lat,lon)?.code||'—'}
function gridBoundsDynamicV13(row,col){const g=gridCfgV13(),x0=g.x0+col*g.dx,x1=x0+g.dx,y1=g.y1-row*g.dy,y0=y1-g.dy;return [[latFromYV12(y0),lonFromXV12(x0)],[latFromYV12(y1),lonFromXV12(x1)]]}
function buildGridDynamicV13(map){if(!map||!window.L)return null;if(!map.getPane('gridPaneV13')){const p=map.createPane('gridPaneV13');p.style.zIndex='390';p.style.pointerEvents='none'}const g=gridCfgV13(),group=L.layerGroup(),atlasX0=GRID_X0_V12,atlasX1=GRID_X1_V12,atlasY0=GRID_Y0_V12,atlasY1=GRID_Y1_V12,line={pane:'gridPaneV13',color:'#454b49',weight:.7,opacity:.55,interactive:false};const cMin=Math.floor((atlasX0-g.x0)/g.dx)-1,cMax=Math.ceil((atlasX1-g.x0)/g.dx)+1,rMin=Math.floor((g.y1-atlasY1)/g.dy)-1,rMax=Math.ceil((g.y1-atlasY0)/g.dy)+1;
  for(let c=cMin;c<=cMax;c++){if(c<0)continue;const lon=lonFromXV12(g.x0+c*g.dx);L.polyline([[GRID_V12.south,lon],[GRID_V12.north,lon]],line).addTo(group)}
  for(let r=rMin;r<=rMax;r++){if(r<0)continue;const lat=latFromYV12(g.y1-r*g.dy);L.polyline([[lat,GRID_V12.west],[lat,GRID_V12.east]],line).addTo(group)}
  if(map.getZoom()>=13){for(let c=Math.max(0,cMin);c<cMax;c++){const x=g.x0+(c+.5)*g.dx;if(x<atlasX0||x>atlasX1)continue;L.marker([latFromYV12(atlasY1-.12*g.dy),lonFromXV12(x)],{icon:gridLabelIconV12(String(c+1).padStart(2,'0')),interactive:false,keyboard:false}).addTo(group)}for(let r=Math.max(0,rMin);r<rMax;r++){const y=g.y1-(r+.5)*g.dy;if(y<atlasY0||y>atlasY1)continue;L.marker([latFromYV12(y),lonFromXV12(atlasX0+.12*g.dx)],{icon:gridLabelIconV12(rowCodeV13(r),true),interactive:false,keyboard:false}).addTo(group)}}return group}
function refreshGridV13(){if(!routeMapV11)return;if(dynamicGridLayerV13&&routeMapV11.hasLayer(dynamicGridLayerV13))routeMapV11.removeLayer(dynamicGridLayerV13);if(dynamicGridSelectedV13&&routeMapV11.hasLayer(dynamicGridSelectedV13))routeMapV11.removeLayer(dynamicGridSelectedV13);dynamicGridSelectedV13=null;if(gridEnabledV12){dynamicGridLayerV13=buildGridDynamicV13(routeMapV11);dynamicGridLayerV13.addTo(routeMapV11)}updateGridStatusV13()}
function updateGridStatusV13(){const e=document.getElementById('gridStatusV12');if(e)e.textContent=gridEnabledV12?`Сетка ${gridCfgV13().cell}×${gridCfgV13().cell} м`:'Сетка выключена'}
function handleGridClickDynamicV13(e){if(!gridEnabledV12||editorModeV13&&editorToolV13!=='grid')return;const c=gridCellDynamicV13(e.latlng.lat,e.latlng.lng);if(!c)return;if(dynamicGridSelectedV13&&routeMapV11.hasLayer(dynamicGridSelectedV13))routeMapV11.removeLayer(dynamicGridSelectedV13);dynamicGridSelectedV13=L.rectangle(gridBoundsDynamicV13(c.row,c.col),{color:'#9d7e38',weight:2,fillColor:'#c7a65a',fillOpacity:.16,interactive:false}).addTo(routeMapV11);L.popup().setLatLng(e.latlng).setContent(`<div class="grid-popup-v12"><strong>${c.code}</strong><small>Квадрат ${gridCfgV13().cell} × ${gridCfgV13().cell} м</small><button type="button" data-copy-grid-v13="${c.code}">Скопировать ${c.code}</button></div>`).openOn(routeMapV11)}
