/* V8 — route editor UX stabilization: explicit edit modes, no accidental map edits, smooth control-point dragging */
let routeActionV14='select';
let dragRouteBaseV14=null;
let routeViewportV14=null;
let savePulseV14=null;
const ROUTE_HANDLE_MIN_Z_V14=14;

function captureViewportV14(){
  if(routeMapV11){const c=routeMapV11.getCenter();routeViewportV14={lat:c.lat,lng:c.lng,zoom:routeMapV11.getZoom()}}
}
function renderPreserveV14(){captureViewportV14();render()}
function markSavedV14(){
  const e=document.getElementById('editorSaveV14');if(!e)return;
  e.textContent='Сохранено';e.classList.add('saved');clearTimeout(savePulseV14);savePulseV14=setTimeout(()=>e.classList.remove('saved'),700);
}
function setSelectedV14(sel){selectedV13=sel;refreshSelectionStylesV14();refreshEditorPanelV14()}
function refreshSelectionStylesV14(){
  routeSegLayersV13.forEach((seg,i)=>seg.setStyle({weight:selectedV13?.type==='segment'&&selectedV13.index===i?8:5,opacity:selectedV13?.type==='segment'&&selectedV13.index!==i?.65:.95}));
  routeVertexLayersV13.forEach(m=>{const i=m._routeIndexV14;m.setIcon(iconVertexV13(selectedV13?.type==='vertex'&&selectedV13.index===i))});
  Object.entries(cpLayersV13).forEach(([id,m])=>{const d=dynamicCpsV13().find(x=>x.id===id);if(d)m.setIcon(iconCpV13(d.number,selectedV13?.type==='cp'&&selectedV13.id===id))});
}
function refreshEditorPanelV14(){
  const p=document.getElementById('editorPanelV14');if(p){p.innerHTML=editorPanelV13();bindPanelV14()}
  const len=document.getElementById('routeLenV14');if(len)len.textContent=`${(routeLenV13()/1000).toFixed(1).replace('.',',')} км`;
  const fin=document.getElementById('routeFinishV14');if(fin)fin.textContent=finalEtaV13();
  const cpCount=document.getElementById('routeCpCountV14');if(cpCount)cpCount.textContent=String(dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length);
  const grid=document.getElementById('routeGridV14');if(grid)grid.textContent=`${gridCfgV13().cell} м`;
  const table=document.querySelector('.cp-list-v14');if(table)table.innerHTML=cpRowsDynamicV13();
  const nav=document.querySelector('.nav-leg-list-v14');if(nav)nav.innerHTML=dynamicNavRowsV13();
  bindDynamicRowsV14();
  markSavedV14();
}
function bindDynamicRowsV14(){document.querySelectorAll('[data-cp-dyn-v13]').forEach(b=>b.onclick=()=>{const cp=editorV13.cps.find(x=>x.id===b.dataset.cpDynV13);if(cp&&routeMapV11){routeMapV11.setView([cp.lat,cp.lon],15,{animate:true});cpLayersV13[cp.id]?.openTooltip();setSelectedV14({type:'cp',id:cp.id})}})}
function bindPanelV14(){
  document.querySelectorAll('[data-delete-vertex-v14]').forEach(b=>b.onclick=()=>deleteVertexV13(+b.dataset.deleteVertexV14));
  document.querySelectorAll('[data-terrain-v14]').forEach(s=>s.onchange=()=>setTerrainV13(+s.dataset.terrainV14,s.value));
  document.querySelectorAll('[data-brouter-v14]').forEach(b=>b.onclick=()=>routeSegmentBrouterV13(+b.dataset.brouterV14));
  document.querySelectorAll('[data-split-segment-v14]').forEach(b=>b.onclick=()=>splitSegmentV14(+b.dataset.splitSegmentV14));
  document.querySelectorAll('[data-delete-cp-v14]').forEach(b=>b.onclick=()=>deleteCpV13(b.dataset.deleteCpV14));
  document.querySelectorAll('[data-save-cp-v14]').forEach(b=>b.onclick=()=>{const id=b.dataset.saveCpV14,title=document.querySelector(`[data-cp-title-v14="${id}"]`)?.value.trim(),stopMin=+document.querySelector(`[data-cp-stop-v14="${id}"]`)?.value||0;if(!title){toast('Название КП не может быть пустым');return}updateCpV13(id,{title,stopMin})});
  document.getElementById('applyGridV14')?.addEventListener('click',applyGridV14);
  document.getElementById('resetGridV14')?.addEventListener('click',resetGridV14);
  document.querySelectorAll('[data-grid-nudge-v14]').forEach(b=>b.onclick=()=>nudgeGridV14(b.dataset.gridNudgeV14));
  document.getElementById('snapCpsV14')?.addEventListener('change',e=>{editorV13.snapCps=e.target.checked;saveEditorV13();markSavedV14()});
}
function applyGridV14(){const sel=document.getElementById('gridCellV14'),custom=+document.getElementById('gridCustomV14')?.value||200,cell=sel?.value==='custom'?custom:+sel?.value,ox=+document.getElementById('gridOffsetXV14')?.value||0,oy=+document.getElementById('gridOffsetYV14')?.value||0;pushHistoryV13();editorV13.grid={cell:Math.max(50,Math.min(1000,cell||200)),offsetX:ox,offsetY:oy};saveEditorV13();refreshGridV13();refreshEditorPanelV14();toast('Сетка обновлена')}
function resetGridV14(){pushHistoryV13();editorV13.grid={cell:200,offsetX:0,offsetY:0};saveEditorV13();refreshGridV13();refreshEditorPanelV14();toast('Сетка возвращена к PDF')}
function nudgeGridV14(dir){const step=25;pushHistoryV13();if(dir==='left')editorV13.grid.offsetX=(+editorV13.grid.offsetX||0)-step;if(dir==='right')editorV13.grid.offsetX=(+editorV13.grid.offsetX||0)+step;if(dir==='up')editorV13.grid.offsetY=(+editorV13.grid.offsetY||0)+step;if(dir==='down')editorV13.grid.offsetY=(+editorV13.grid.offsetY||0)-step;saveEditorV13();refreshGridV13();refreshEditorPanelV14()}

editorToolbarV13=function(){return `<div class="editor-toolbar-v13 editor-toolbar-v14"><button class="btn ${editorModeV13?'sand':'alt'}" id="toggleEditorV14">${editorModeV13?'Завершить':'Редактировать'}</button>${editorModeV13?`<div class="history-v14"><button class="icon-btn" id="undoV14" ${undoV13.length?'':'disabled'} title="Отменить">↶</button><button class="icon-btn" id="redoV14" ${redoV13.length?'':'disabled'} title="Повторить">↷</button></div><span class="editor-save-v14" id="editorSaveV14">Сохранено</span><button class="btn alt" id="resetRouteV14">Вернуть PDF</button>`:''}<button class="btn alt" id="downloadGpxV14">GPX</button><button class="btn alt" id="exportAtlasV14">PDF / печать</button></div>`}
function routeToolStripV14(){if(!editorModeV13)return '';return `<div class="route-toolstrip-v14"><div class="route-toolgroup-v14"><button class="route-tool-v14 ${editorToolV13==='route'?'active':''}" data-tool-v14="route">Линия</button><button class="route-tool-v14 ${editorToolV13==='cp'?'active':''}" data-tool-v14="cp">КП</button><button class="route-tool-v14 ${editorToolV13==='grid'?'active':''}" data-tool-v14="grid">Сетка</button></div>${editorToolV13==='route'?`<div class="route-toolgroup-v14 secondary"><button class="route-tool-v14 ${routeActionV14==='select'?'active':''}" data-action-v14="select">Выбирать / двигать</button><button class="route-tool-v14 ${routeActionV14==='add'?'active':''}" data-action-v14="add">+ Добавить узел</button></div>`:''}<div class="route-modehint-v14">${editorToolV13==='route'?(routeActionV14==='add'?'Клик по карте добавит один узел. После добавления вернёмся в режим выбора.':'Перетаскивай белые узлы. Клик по пустой карте ничего не меняет.'):editorToolV13==='cp'?'Клик по карте добавит КП. Существующие КП можно перетаскивать.':'Настройки и смещение сетки — в панели справа.'}</div></div>`}
editorPanelV13=function(){
  if(!editorModeV13)return `<div class="metric"><small>Расчётная длина</small><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong><em>автопересчёт</em></div><div class="metric"><small>Расчётный финиш</small><strong>${finalEtaV13()}</strong><em>${fmtDurationV13(routeDurationMinV13())}</em></div><div class="metric"><small>КП</small><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong><em>можно редактировать</em></div><div class="metric"><small>Сетка</small><strong>${gridCfgV13().cell} × ${gridCfgV13().cell} м</strong><em>${editorV13.grid.offsetX||editorV13.grid.offsetY?'со смещением':'по PDF'}</em></div>`;
  let sel='';
  if(selectedV13?.type==='vertex'){const i=selectedV13.index,p=editorV13.route[i];sel=`<div class="editor-card-v13"><small>Контрольный узел · ${i+1}/${editorV13.route.length}</small><strong>${p[0].toFixed(6)}, ${p[1].toFixed(6)}</strong><p>При перетаскивании соседние скрытые точки двигаются плавно вместе с узлом, чтобы линия не ломалась.</p><button class="btn alt sm" data-delete-vertex-v14="${i}" ${i===0||i===editorV13.route.length-1?'disabled':''}>Удалить узел</button></div>`}
  else if(selectedV13?.type==='segment'){const i=selectedV13.index,t=editorV13.terrain[i]||'unknown',a=editorV13.route[i],b=editorV13.route[i+1];sel=`<div class="editor-card-v13"><small>Участок ${i+1}</small><strong>${(havV13(a,b)*DISTANCE_CAL_V13/1000).toFixed(2).replace('.',',')} км</strong><label>Тип движения<select data-terrain-v14="${i}">${Object.entries(TERRAIN_V13).map(([k,v])=>`<option value="${k}" ${k===t?'selected':''}>${v.label}</option>`).join('')}</select></label><div class="editor-inline-v13"><button class="btn sand sm" data-brouter-v14="${i}">По тропам OSM</button><button class="btn alt sm" data-split-segment-v14="${i}">Узел в середине</button></div><p>Автопрокладка меняет только выбранный участок. Если результат не подходит, нажми ↶.</p></div>`}
  else if(selectedV13?.type==='cp'){const cp=editorV13.cps.find(x=>x.id===selectedV13.id),dyn=dynamicCpsV13().find(x=>x.id===selectedV13.id);if(cp)sel=`<div class="editor-card-v13"><small>${dyn?.number==='С'?'Старт':dyn?.number==='Ф'?'Финиш':`КП ${dyn?.number||''}`} · ${gridCodeDynamicV13(cp.lat,cp.lon)}</small><label>Название<input data-cp-title-v14="${cp.id}" value="${esc(cp.title)}"></label><label>Остановка, мин<input type="number" min="0" max="240" data-cp-stop-v14="${cp.id}" value="${cp.stopMin||0}"></label><div class="editor-inline-v13"><button class="btn sand sm" data-save-cp-v14="${cp.id}">Сохранить</button><button class="btn alt sm" data-delete-cp-v14="${cp.id}" ${cp.locked?'disabled':''}>Удалить</button></div><p>${dyn?`${dyn.km.toFixed(1).replace('.',',')} км · ETA ${dyn.arrival}`:''}</p></div>`}
  else if(editorToolV13==='grid'){const g=editorV13.grid;sel=`<div class="editor-card-v13"><small>Координатная сетка</small><label>Размер клетки<select id="gridCellV14">${[100,200,250,500].map(v=>`<option value="${v}" ${+g.cell===v?'selected':''}>${v} × ${v} м</option>`).join('')}<option value="custom" ${![100,200,250,500].includes(+g.cell)?'selected':''}>Свой размер</option></select></label><label>Свой размер, м<input id="gridCustomV14" type="number" min="50" max="1000" step="10" value="${+g.cell||200}"></label><div class="grid-nudge-v14"><span></span><button data-grid-nudge-v14="up">↑</button><span></span><button data-grid-nudge-v14="left">←</button><button type="button" class="grid-nudge-center-v14" title="Текущее смещение">${+g.offsetX||0}; ${+g.offsetY||0}</button><button data-grid-nudge-v14="right">→</button><span></span><button data-grid-nudge-v14="down">↓</button><span></span></div><div class="editor-grid2-v13"><label>Смещение X, м<input id="gridOffsetXV14" type="number" step="10" value="${+g.offsetX||0}"></label><label>Смещение Y, м<input id="gridOffsetYV14" type="number" step="10" value="${+g.offsetY||0}"></label></div><div class="editor-inline-v13"><button class="btn sand sm" id="applyGridV14">Применить</button><button class="btn alt sm" id="resetGridV14">PDF 200 м</button></div><p>Стрелки двигают сетку по 25 м. Точная величина задаётся полями ниже.</p></div>`}
  const snap=`<label class="snap-toggle-v14"><input type="checkbox" id="snapCpsV14" ${editorV13.snapCps?'checked':''}><span><b>КП следуют за маршрутом</b><small>После изменения линии КП привязываются к ближайшему участку.</small></span></label>`;
  return `<div class="editor-summary-v13"><div class="editor-stat-v13"><span>Длина</span><strong>${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</strong></div><div class="editor-stat-v13"><span>Финиш</span><strong>${finalEtaV13()}</strong></div><div class="editor-stat-v13"><span>КП</span><strong>${dynamicCpsV13().filter(x=>!['С','Ф'].includes(x.number)).length}</strong></div></div>${sel||`<div class="editor-empty-v13"><strong>${editorToolV13==='route'?'Выбери узел или участок':editorToolV13==='cp'?'Контрольные точки':'Редактор сетки'}</strong><p>${editorToolV13==='route'?'По пустой карте можно спокойно кликать и двигать её — маршрут не изменится, пока не включён «+ Добавить узел».':editorToolV13==='cp'?'Клик по карте добавляет КП; существующую КП можно перетащить.':'Настрой размер и сдвиг сетки.'}</p></div>`}${editorToolV13!=='grid'?snap:''}`
}

function routePageV14(){
  const body=routeModeV9==='points'?section('Контрольные точки',`<div class="cp-head"><span>КП</span><span>Точка</span><span>Км</span><span>ETA</span></div><div class="cp-list cp-list-v14">${cpRowsDynamicV13()}</div>`,'Километраж и ETA считаются из текущей линии маршрута.'):routeModeV9==='navigation'?section('Переходы и азимуты',`<div class="navigation-note"><strong>Автопересчёт</strong><p>Расстояние считается вдоль маршрута, азимут — между КП. Тип движения задаётся по участкам.</p></div><div class="nav-leg-list nav-leg-list-v14">${dynamicNavRowsV13()}</div>`,'Значения обновляются после редактирования.'):section('Полевой атлас и экспорт',`<div class="atlas-source"><div class="atlas-source__number">PDF</div><div><b>Маршрут → атлас</b><p>Экспорт использует текущее состояние линии, КП и сетки.</p></div></div><div class="materials-list">${materialRowsV10()}</div>`,'GPX/KML — справочные исходники; редактор хранит актуальную версию.');
  return `${pageHead('Навигация','Маршрут','Редактор маршрута с явными режимами: выбор, добавление узла, КП и сетка. Случайный клик по карте больше не меняет линию.',editorToolbarV13())}${routeToolStripV14()}<div class="route-layout route-layout-v10 route-editor-layout-v13"><div class="route-map"><div class="route-map-head-v11"><div><small>${editorModeV13?'Редактор':'Маршрут'}</small><strong>Томинский лесопарк · <span id="routeLenV14">${(routeLenV13()/1000).toFixed(1).replace('.',',')} км</span></strong></div><div class="map-controls-v12"><div class="map-layer-switch-v11"><button type="button" data-map-layer-v11="osm" class="${routeBaseV11==='osm'?'active':''}">Карта</button><button type="button" data-map-layer-v11="sat" class="${routeBaseV11==='sat'?'active':''}">Спутник</button></div><button type="button" class="grid-toggle-v12 ${gridEnabledV12?'active':''}" data-grid-toggle-v12>Сетка</button></div></div><div class="map-shell-v11"><div id="routeMapFinal" class="leaflet-map leaflet-map-v11 ${editorModeV13?'editing-v13':''}"></div><div class="route-loading-v11">Загрузка подложки…</div><div class="editor-map-hint-v14">${editorModeV13?(editorToolV13==='route'?(routeActionV14==='add'?'Клик: добавить один узел':'Перетаскивай узлы · клик по линии: выбрать участок'):editorToolV13==='cp'?'Клик: добавить КП · маркер: перетащить':'Клик: посмотреть квадрат'):'Колесо: масштаб · карта/спутник'}</div></div><div class="route-map-foot-v11"><span>⌂ — весь маршрут</span><span>${editorModeV13?'Автосохранение включено':'Просмотр'}</span><span id="gridStatusV12">Сетка ${gridCfgV13().cell}×${gridCfgV13().cell} м</span></div></div><aside class="route-summary route-editor-panel-v13" id="editorPanelV14">${editorPanelV13()}</aside></div><div class="segmented route-tabs"><button class="${routeModeV9==='points'?'active':''}" data-route-v9="points">КП</button><button class="${routeModeV9==='navigation'?'active':''}" data-route-v9="navigation">Навигация</button><button class="${routeModeV9==='atlas'?'active':''}" data-route-v9="atlas">Атлас</button></div>${body}`
}
routePage=routePageV14;
