/* V18.1 — transport interaction fixes. */
hasCoordV24=function(p){return !!p&&p.lat!==null&&p.lon!==null&&p.lat!==''&&p.lon!==''&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lon)};
fmtCoordV24=function(lat,lon){return lat!==null&&lon!==null&&lat!==''&&lon!==''&&Number.isFinite(+lat)&&Number.isFinite(+lon)?`${(+lat).toFixed(6)}, ${(+lon).toFixed(6)}`:'координаты не заданы'};

const arrivalCardBaseV241=arrivalCardV24;
arrivalCardV24=function(){const a=tv24().arrival,time=dir==='there'?a.time:a.returnTime;return `<div class="tv24-arrival"><div class="tv24-arrival-pin">★</div><div class="tv24-arrival-copy"><small>${dir==='there'?'КУДА НУЖНО ПРИЕХАТЬ':'ОТКУДА УЕЗЖАЕМ'}</small><h3>${esc(a.title||'Место мероприятия')}</h3><p>${esc(a.note||'')}</p><div class="tv24-coordinate"><code>${esc(fmtCoordV24(a.lat,a.lon))}</code>${time?`<b>${dir==='there'?'Прибыть к':'Ориентир выезда'} ${esc(time)}</b>`:`<b>${dir==='there'?'Время прибытия не задано':'Время обратного выезда уточняется'}</b>`}</div></div><div class="tv24-arrival-actions"><button class="btn alt sm" id="tv24EditArrival">Редактировать</button>${hasCoordV24(a)?`<button class="btn sm" data-tv24-yandex-point="arrival">Яндекс ↗</button>`:''}</div></div>`};
arrivalModalV24=function(){const a=tv24().arrival,value={...a,time:dir==='there'?(a.time||''):(a.returnTime||'')};pointModalV24({title:dir==='there'?'Место прибытия мероприятия':'Место и время обратного выезда',value,kind:'arrival',onSave:o=>{const next={...a,title:o.title,lat:o.lat,lon:o.lon,note:o.note};if(dir==='there')next.time=o.time;else next.returnTime=o.time;tv24().arrival=next;transportSaveV24('Точка транспорта обновлена')}})};

const stopModalBaseV241=stopModalV24;
stopModalV24=function(r,stop=null){stopModalBaseV241(r,stop);if(!stop)return;setTimeout(()=>{const body=document.querySelector('#modalLayer .modal-body');if(!body)return;const active=(r.requests||[]).filter(q=>q.pickupId===stop.id&&['pending','approved'].includes(q.status));const wrap=document.createElement('div');wrap.className='tv24-modal-danger';wrap.innerHTML=`<button type="button" class="btn alt sm" id="tv24DeleteStop" ${active.length?'disabled':''}>Удалить точку</button>${active.length?`<small>Точку используют ${active.length} активн. заявк/пассажиров. Сначала освободи их.</small>`:''}`;body.appendChild(wrap);wrap.querySelector('#tv24DeleteStop')?.addEventListener('click',()=>{if(active.length)return;r.stops=(r.stops||[]).filter(s=>s.id!==stop.id);(r.requests||[]).filter(q=>q.pickupId===stop.id&&['declined','cancelled'].includes(q.status)).forEach(q=>q.pickupId='');document.getElementById('modalCancel')?.click();transportSaveV24('Точка удалена')})},60)};

const buildV241=document.querySelector('.build-label');if(buildV241)buildV241.textContent='V18.1 · транспорт по заявкам · точки посадки';
