/* V18 — transport planner: driver profiles, event rides, pickup points, requests and Yandex handoff. */
const TRANSPORT_V24_VERSION=1;
let transportMapV24=null,transportMapLayersV24=[];

function transportSeedV24(){
  const routeStart=(typeof editorV13!=='undefined'&&Array.isArray(editorV13.route)&&editorV13.route[0])?editorV13.route[0]:[null,null];
  const profiles={};
  (S.participants||[]).forEach(p=>profiles[p.id]={driver:false,defaultSeats:3,phone:'',vehicle:'',plate:'',color:''});
  const legacyDrivers=new Set([...(S.cars?.there||[]).map(c=>c.driver),...(S.cars?.back||[]).map(c=>c.driver)]);
  legacyDrivers.forEach(pid=>{if(profiles[pid])profiles[pid].driver=true});
  const state={version:TRANSPORT_V24_VERSION,arrival:{title:'Место прибытия мероприятия',lat:routeStart[0],lon:routeStart[1],time:S.event?.start||'09:15',note:'Точка транспорта задаётся отдельно от пешего маршрута.'},profiles,rides:{there:[],back:[]},choices:{there:{},back:{}}};
  ['there','back'].forEach(d=>{
    (S.participants||[]).forEach(p=>state.choices[d][p.id]={mode:'unset'});
    (S.cars?.[d]||[]).forEach((c,idx)=>{
      const stop={id:`legacy_${d}_${idx}`,title:c.from||'Точка посадки уточняется',lat:null,lon:null,time:c.time&&c.time!=='Уточняется'?c.time:'',note:'Уточни точные координаты точки.'};
      const ride={id:`tv24_${d}_${c.id||idx}`,driver:c.driver,seats:Math.max(0,+c.cap||3),vehicle:c.name||`Машина ${pn(c.driver)}`,color:'',plate:'',comment:'',stops:[stop],passengers:[...(c.pass||[])],requests:[]};
      state.rides[d].push(ride);state.choices[d][c.driver]={mode:'driver',rideId:ride.id};
      (c.pass||[]).forEach(pid=>{const req={id:`legacy_req_${d}_${ride.id}_${pid}`,pid,pickupId:stop.id,status:'approved',createdAt:Date.now()};ride.requests.push(req);state.choices[d][pid]={mode:'ride',rideId:ride.id,requestId:req.id,pickupId:stop.id}});
    });
    (S.participants||[]).forEach(p=>{
      if(state.choices[d][p.id].mode!=='unset')return;
      const old=S.rides?.[d]?.[p.id];
      if(old==='self')state.choices[d][p.id]={mode:'self'};
      else if(old==='need')state.choices[d][p.id]={mode:'unset'};
    });
  });
  return state;
}
function ensureTransportV24(){
  if(!S.transportV24||S.transportV24.version!==TRANSPORT_V24_VERSION)S.transportV24=transportSeedV24();
  const T=S.transportV24;T.profiles=T.profiles||{};T.rides=T.rides||{there:[],back:[]};T.choices=T.choices||{there:{},back:{}};
  (S.participants||[]).forEach(p=>{
    if(!T.profiles[p.id])T.profiles[p.id]={driver:false,defaultSeats:3,phone:'',vehicle:'',plate:'',color:''};
    ['there','back'].forEach(d=>{if(!T.choices[d])T.choices[d]={};if(!T.choices[d][p.id])T.choices[d][p.id]={mode:'unset'}});
  });
  if(!T.arrival)T.arrival={title:'Место прибытия мероприятия',lat:null,lon:null,time:'',note:''};
  syncLegacyTransportV24(false);return T;
}
function tv24(){return ensureTransportV24()}
function transportProfileV24(pid=S.current){return tv24().profiles[pid]}
function transportRideV24(id,d=dir){return tv24().rides[d].find(r=>r.id===id)}
function transportDriverRideV24(pid=S.current,d=dir){return tv24().rides[d].find(r=>r.driver===pid)}
function transportChoiceV24(pid=S.current,d=dir){return tv24().choices[d][pid]||{mode:'unset'}}
function transportRequestV24(pid=S.current,d=dir){for(const r of tv24().rides[d]){const q=(r.requests||[]).find(x=>x.pid===pid&&['pending','approved'].includes(x.status));if(q)return {ride:r,request:q}}return null}
function transportConfirmedV24(){return S.participants.filter(p=>p.rsvp==='yes')}
function transportFreeV24(r){return Math.max(0,(+r.seats||0)-(r.passengers||[]).length)}
function transportSaveV24(msg=''){syncLegacyTransportV24(true);if(msg)toast(msg);render()}
function syncLegacyTransportV24(doSave=true){
  const T=S.transportV24;if(!T)return;
  S.cars=S.cars||{there:[],back:[]};S.rides=S.rides||{there:{},back:{}};
  ['there','back'].forEach(d=>{
    S.cars[d]=(T.rides[d]||[]).map(r=>({id:r.id,driver:r.driver,name:r.vehicle||`Машина ${pn(r.driver)}`,cap:+r.seats||0,pass:[...(r.passengers||[])],time:r.stops?.[0]?.time||'',from:r.stops?.[0]?.title||'Точка уточняется'}));
    (S.participants||[]).forEach(p=>{
      const c=T.choices[d]?.[p.id]||{mode:'unset'};
      S.rides[d][p.id]=c.mode==='driver'?'own':c.mode==='self'?'self':c.mode==='ride'?c.rideId:c.mode==='request'?'need':'unset';
    });
  });
  if(doSave)save();
}
function fmtCoordV24(lat,lon){return Number.isFinite(+lat)&&Number.isFinite(+lon)?`${(+lat).toFixed(6)}, ${(+lon).toFixed(6)}`:'координаты не заданы'}
function hasCoordV24(p){return p&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lon)}
function yandexPointV24(lat,lon){return `https://yandex.ru/maps/?ll=${encodeURIComponent(`${lon},${lat}`)}&z=16&pt=${encodeURIComponent(`${lon},${lat},pm2rdm`)}`}
function yandexRouteV24(points){const pts=points.filter(hasCoordV24);if(pts.length<2)return null;return `https://yandex.ru/maps/?mode=routes&rtext=${pts.map(p=>`${(+p.lat).toFixed(6)}%2C${(+p.lon).toFixed(6)}`).join('~')}&rtt=auto`}
function rideRoutePointsV24(r,d=dir){const a=tv24().arrival,st=(r.stops||[]).filter(hasCoordV24);return d==='there'?[...st,a]:[a,...st]}
function openYandexRideV24(r,d=dir){const u=yandexRouteV24(rideRoutePointsV24(r,d));if(!u)return toast('Сначала задай координаты хотя бы двух точек');window.open(u,'_blank','noopener')}
function copyTextV24(s,msg='Скопировано'){navigator.clipboard?.writeText(s).then(()=>toast(msg)).catch(()=>toast('Не удалось скопировать'))}

function transportSummaryV24(d=dir){
  const T=tv24(),people=transportConfirmedV24(),rides=T.rides[d],drivers=people.filter(p=>rides.some(r=>r.driver===p.id)).length;
  let inCars=0,self=0,pending=0,unset=0;
  people.forEach(p=>{const c=T.choices[d][p.id]||{mode:'unset'};if(c.mode==='ride')inCars++;else if(c.mode==='self')self++;else if(c.mode==='request')pending++;else if(c.mode!=='driver')unset++});
  const free=rides.reduce((n,r)=>n+transportFreeV24(r),0);return {total:people.length,drivers,inCars,self,pending,unset,free};
}
function directionLabelV24(d){return d==='there'?'Туда':'Обратно'}
function stopKindV24(d){return d==='there'?'Точка посадки':'Точка высадки'}

function profileCardV24(){const p=transportProfileV24(),ride=transportDriverRideV24(S.current,dir);return `<div class="tv24-profile"><div class="tv24-profile-main"><div class="avatar small">${initials(pn(S.current))}</div><div><small>МОЙ ТРАНСПОРТНЫЙ ПРОФИЛЬ</small><strong>${esc(pn(S.current))}</strong><span>${p.driver?`Водитель · обычно ${p.defaultSeats} пасс. мест${p.vehicle?' · '+esc(p.vehicle):''}`:'Не водитель'}${p.phone?' · телефон указан':''}</span></div></div><div class="row-actions"><button class="btn alt sm" id="tv24ProfileEdit">Настроить профиль</button>${p.driver&&!ride?`<button class="btn sand sm" id="tv24CreateRide">Создать рейс ${dir==='there'?'туда':'обратно'}</button>`:''}</div></div>`}
function arrivalCardV24(){const a=tv24().arrival;return `<div class="tv24-arrival"><div class="tv24-arrival-pin">★</div><div class="tv24-arrival-copy"><small>${dir==='there'?'КУДА НУЖНО ПРИЕХАТЬ':'ОТКУДА УЕЗЖАЕМ'}</small><h3>${esc(a.title||'Место прибытия')}</h3><p>${esc(a.note||'')}</p><div class="tv24-coordinate"><code>${esc(fmtCoordV24(a.lat,a.lon))}</code>${a.time?`<b>${dir==='there'?'Прибыть к':'Отъезд ориентировочно'} ${esc(a.time)}</b>`:''}</div></div><div class="tv24-arrival-actions"><button class="btn alt sm" id="tv24EditArrival">Редактировать</button>${hasCoordV24(a)?`<button class="btn sm" data-tv24-yandex-point="arrival">Яндекс ↗</button>`:''}</div></div>`}
function requestStateCardV24(){const c=transportChoiceV24(),active=transportRequestV24();if(c.mode==='self')return `<div class="tv24-myride self"><div><small>МОЙ ВАРИАНТ · ${directionLabelV24(dir).toUpperCase()}</small><strong>Добираюсь самостоятельно</strong><span>При необходимости можно выбрать машину ниже.</span></div><button class="btn alt sm" data-tv24-unset-self>Изменить</button></div>`;
  if(active){const r=active.ride,q=active.request,stop=(r.stops||[]).find(s=>s.id===q.pickupId),approved=q.status==='approved';return `<div class="tv24-myride ${approved?'approved':'pending'}"><div><small>${approved?'ПОДТВЕРЖДЕНО':'ЗАЯВКА ОТПРАВЛЕНА'}</small><strong>${esc(pn(r.driver))} · ${esc(r.vehicle||'автомобиль')}</strong><span>${esc(stop?.title||stopKindV24(dir))}${stop?.time?' · '+esc(stop.time):''}</span>${approved&&transportProfileV24(r.driver).phone?`<a href="tel:${esc(transportProfileV24(r.driver).phone)}">${esc(transportProfileV24(r.driver).phone)}</a>`:''}</div><div class="row-actions">${stop&&hasCoordV24(stop)?`<button class="btn sm" data-tv24-yandex-stop="${r.id}:${stop.id}">Точка в Яндекс</button>`:''}<button class="btn alt sm" data-tv24-cancel-request="${q.id}">${approved?'Отказаться от места':'Отменить заявку'}</button></div></div>`}
  const ride=transportDriverRideV24();if(ride)return `<div class="tv24-myride approved"><div><small>МОЙ РЕЙС · ${directionLabelV24(dir).toUpperCase()}</small><strong>Вы водитель</strong><span>${(ride.passengers||[]).length} пассажиров · ${transportFreeV24(ride)} свободных мест</span></div><button class="btn alt sm" data-tv24-edit-ride="${ride.id}">Редактировать рейс</button></div>`;
  return `<div class="tv24-myride unset"><div><small>МОЙ ВАРИАНТ · ${directionLabelV24(dir).toUpperCase()}</small><strong>Транспорт пока не выбран</strong><span>Можно попроситься к водителю или отметить самостоятельную поездку.</span></div><button class="btn alt sm" data-tv24-self>Поеду самостоятельно</button></div>`;
}
function rideStopsHtmlV24(r){return (r.stops||[]).map((s,i)=>`<div class="tv24-stop ${hasCoordV24(s)?'':'missing'}"><div class="tv24-stop-index">${i+1}</div><div><b>${esc(s.title||stopKindV24(dir))}</b><small>${s.time?esc(s.time):'время уточняется'} · ${esc(fmtCoordV24(s.lat,s.lon))}</small>${s.note?`<em>${esc(s.note)}</em>`:''}</div>${r.driver===S.current?`<button class="icon-btn" data-tv24-edit-stop="${r.id}:${s.id}" title="Редактировать">✎</button>`:''}</div>`).join('')||`<div class="tv24-empty-small">${dir==='there'?'Водитель ещё не указал точку посадки.':'Точки высадки пока не указаны.'}</div>`}
function pendingForRideV24(r){return (r.requests||[]).filter(q=>q.status==='pending')}
function rideCardV24(r){const me=r.driver===S.current,free=transportFreeV24(r),prof=transportProfileV24(r.driver),pending=pendingForRideV24(r),my=transportRequestV24(),activeElsewhere=my&&my.ride.id!==r.id;return `<article class="tv24-ride ${me?'mine':''}"><header><div><small>${me?'МОЙ РЕЙС':'ВОДИТЕЛЬ'}</small><h3>${esc(pn(r.driver))}${r.vehicle?' · '+esc(r.vehicle):''}</h3><span>${r.color?esc(r.color)+' · ':''}${r.plate?esc(r.plate):''}</span></div><div class="tv24-seats"><strong>${(r.passengers||[]).length} / ${+r.seats||0}</strong><small>${free} свободно</small>${pending.length?`<em>${pending.length} заявк${pending.length===1?'а':'и'}</em>`:''}</div></header><div class="tv24-route-line"><div><span>${dir==='there'?'Посадки':'Старт'}</span><b>${dir==='there'?`${(r.stops||[]).length} точ${(r.stops||[]).length===1?'ка':'ки'}`:esc(tv24().arrival.title)}</b></div><i>→</i><div><span>${dir==='there'?'Прибытие':'Высадки'}</span><b>${dir==='there'?esc(tv24().arrival.title):`${(r.stops||[]).length} точ${(r.stops||[]).length===1?'ка':'ки'}`}</b></div></div><div class="tv24-stops">${rideStopsHtmlV24(r)}</div><div class="tv24-passengers"><small>ПАССАЖИРЫ</small>${(r.passengers||[]).length?(r.passengers||[]).map(pid=>`<span>${esc(pn(pid))}</span>`).join(''):'<em>Пока никого</em>'}</div>${me&&pending.length?`<div class="tv24-requests"><small>ОЖИДАЮТ РЕШЕНИЯ</small>${pending.map(q=>{const st=(r.stops||[]).find(s=>s.id===q.pickupId);return `<div><span><b>${esc(pn(q.pid))}</b><small>${esc(st?.title||'точка не выбрана')}</small></span><button class="btn sm" data-tv24-approve="${r.id}:${q.id}">Подтвердить</button><button class="btn alt sm" data-tv24-decline="${r.id}:${q.id}">Отказать</button></div>`}).join('')}</div>`:''}<footer><div class="row-actions">${me?`<button class="btn alt sm" data-tv24-edit-ride="${r.id}">Настройки рейса</button><button class="btn sm" data-tv24-add-stop="${r.id}">+ ${dir==='there'?'Посадка':'Высадка'}</button>`:`<button class="btn sand sm" data-tv24-request="${r.id}" ${free<=0||activeElsewhere||my?.ride.id===r.id?'disabled':''}>${my?.ride.id===r.id?'Заявка уже отправлена':free<=0?'Мест нет':'Попроситься'}</button>`}<button class="btn alt sm" data-tv24-yandex-ride="${r.id}">Маршрут в Яндекс</button></div>${me&&dir==='there'?`<button class="text-button" data-tv24-copy-back="${r.id}">Скопировать этот рейс обратно</button>`:''}</footer></article>`}
function organizerSummaryV24(){const s=transportSummaryV24();return `<div class="tv24-summary"><div><small>ПОДТВЕРДИЛИ УЧАСТИЕ</small><strong>${s.total}</strong></div><div><small>Водителей</small><strong>${s.drivers}</strong></div><div><small>В машинах</small><strong>${s.inCars}</strong></div><div><small>Самостоятельно</small><strong>${s.self}</strong></div><div class="${s.pending?'warn':''}"><small>Ждут ответа</small><strong>${s.pending}</strong></div><div class="${s.unset?'risk':''}"><small>Не определились</small><strong>${s.unset}</strong></div><div><small>Свободных мест</small><strong>${s.free}</strong></div></div>`}
function transportPage(){ensureTransportV24();const rides=tv24().rides[dir],prof=transportProfileV24();return `${pageHead('Логистика','Транспорт','Водители сами задают точки посадки, время и места. Пассажир отправляет одну заявку и получает точку после подтверждения.',prof.driver&&dir==='there'&&transportDriverRideV24(S.current,'there')?`<button class="btn alt" data-tv24-copy-back="${transportDriverRideV24(S.current,'there').id}">Скопировать рейс обратно</button>`:'')}<div class="segmented tv24-dir"><button class="${dir==='there'?'active':''}" data-tv24-dir="there">Туда</button><button class="${dir==='back'?'active':''}" data-tv24-dir="back">Обратно</button></div>${profileCardV24()}${organizerSummaryV24()}${arrivalCardV24()}${requestStateCardV24()}<div class="tv24-layout"><section class="section tv24-rides-section"><div class="section-head"><div><h2>${dir==='there'?'Доступные рейсы':'Обратные рейсы'}</h2><p>${dir==='there'?'Выбери водителя и конкретную точку посадки. Место считается занятым только после подтверждения водителем.':'По умолчанию водитель может скопировать рейс «туда» и затем изменить высадки, время и состав.'}</p></div></div><div class="tv24-rides">${rides.length?rides.map(rideCardV24).join(''):'<div class="empty-state"><strong>Рейсов пока нет</strong><span>Водитель может создать первый рейс из своего профиля.</span></div>'}</div></section><aside class="section tv24-map-section"><div class="section-head"><div><h2>Карта транспорта</h2><p>Точки посадки и место мероприятия. Дорожный маршрут открывается в Яндекс Картах.</p></div></div><div id="transportMapV24" class="tv24-map"></div><div class="tv24-map-legend"><span><i class="arrival"></i>Место мероприятия</span><span><i class="pickup"></i>${dir==='there'?'Посадка':'Высадка'}</span></div></aside></div>`}

function transportProfileModalV24(){const p=transportProfileV24(),hasRide=['there','back'].some(d=>!!transportDriverRideV24(S.current,d));openModal('Транспортный профиль',`<div class="form-grid"><div class="field full"><label class="tv24-check"><input id="tv24ProfDriver" type="checkbox" ${p.driver?'checked':''}><span><b>Я водитель</b><small>Смогу создавать рейсы и брать пассажиров.</small></span></label></div><div class="field"><label>Обычно пассажирских мест</label><input id="tv24ProfSeats" type="number" min="0" max="12" value="${+p.defaultSeats||3}"></div><div class="field"><label>Телефон</label><input id="tv24ProfPhone" type="tel" value="${esc(p.phone||'')}" placeholder="+7 ..."></div><div class="field"><label>Автомобиль</label><input id="tv24ProfVehicle" value="${esc(p.vehicle||'')}" placeholder="Например, Kia Sportage"></div><div class="field"><label>Цвет</label><input id="tv24ProfColor" value="${esc(p.color||'')}" placeholder="Серый"></div><div class="field"><label>Госномер</label><input id="tv24ProfPlate" value="${esc(p.plate||'')}" placeholder="Необязательно"></div></div>`,layer=>{const driver=layer.querySelector('#tv24ProfDriver').checked;if(!driver&&hasRide){toast('Сначала удали свои рейсы в мероприятии');return false}Object.assign(p,{driver,defaultSeats:Math.max(0,+layer.querySelector('#tv24ProfSeats').value||0),phone:layer.querySelector('#tv24ProfPhone').value.trim(),vehicle:layer.querySelector('#tv24ProfVehicle').value.trim(),color:layer.querySelector('#tv24ProfColor').value.trim(),plate:layer.querySelector('#tv24ProfPlate').value.trim()});transportSaveV24('Профиль транспорта обновлён')})}
function transportRideModalV24(ride=null,d=dir){const p=transportProfileV24(),r=ride||{seats:p.defaultSeats||3,vehicle:p.vehicle||'',color:p.color||'',plate:p.plate||'',comment:''};openModal(ride?'Настройки рейса':`Новый рейс · ${directionLabelV24(d)}`,`<div class="form-grid"><div class="field"><label>Пассажирских мест на этот выезд</label><input id="tv24RideSeats" type="number" min="0" max="12" value="${+r.seats||0}"></div><div class="field"><label>Автомобиль</label><input id="tv24RideVehicle" value="${esc(r.vehicle||'')}" placeholder="Можно оставить пустым"></div><div class="field"><label>Цвет</label><input id="tv24RideColor" value="${esc(r.color||'')}"></div><div class="field"><label>Госномер</label><input id="tv24RidePlate" value="${esc(r.plate||'')}"></div><div class="field full"><label>Комментарий для пассажиров</label><textarea id="tv24RideComment" placeholder="Где искать машину, особенности поездки">${esc(r.comment||'')}</textarea></div></div>${ride?`<div class="tv24-modal-danger"><button type="button" class="btn alt sm" id="tv24DeleteRide">Удалить рейс</button></div>`:''}`,layer=>{const seats=Math.max(0,+layer.querySelector('#tv24RideSeats').value||0);if(ride&&seats<(ride.passengers||[]).length){toast('Нельзя поставить мест меньше подтверждённых пассажиров');return false}if(!ride){if(transportDriverRideV24(S.current,d)){toast('У вас уже есть рейс в этом направлении');return false}ride={id:`ride_${d}_${Date.now()}`,driver:S.current,seats,vehicle:'',color:'',plate:'',comment:'',stops:[],passengers:[],requests:[]};tv24().rides[d].push(ride);tv24().choices[d][S.current]={mode:'driver',rideId:ride.id}}Object.assign(ride,{seats,vehicle:layer.querySelector('#tv24RideVehicle').value.trim(),color:layer.querySelector('#tv24RideColor').value.trim(),plate:layer.querySelector('#tv24RidePlate').value.trim(),comment:layer.querySelector('#tv24RideComment').value.trim()});transportSaveV24(ride.stops.length?'Рейс обновлён':'Рейс создан — добавь точку')});setTimeout(()=>{document.getElementById('tv24DeleteRide')?.addEventListener('click',()=>deleteRideV24(ride,d))},0)}
function deleteRideV24(r,d=dir){if(!r)return;if((r.passengers||[]).length||pendingForRideV24(r).length)return toast('Сначала закрой заявки и пассажиров');if(!confirm('Удалить этот рейс?'))return;tv24().rides[d]=tv24().rides[d].filter(x=>x.id!==r.id);tv24().choices[d][r.driver]={mode:'unset'};document.getElementById('modalCancel')?.click();transportSaveV24('Рейс удалён')}

function pointModalV24({title,value={},kind='stop',onSave}){const v={title:value.title||'',lat:value.lat,lon:value.lon,time:value.time||'',note:value.note||''};openModal(title,`<div class="form-grid"><div class="field full"><label>Название точки</label><input id="tv24PointTitle" value="${esc(v.title)}" placeholder="Например, парковка у метро"></div><div class="field"><label>Время</label><input id="tv24PointTime" type="time" value="${esc(v.time)}"></div><div class="field"></div><div class="field"><label>Широта</label><input id="tv24PointLat" type="number" step="0.000001" value="${Number.isFinite(+v.lat)?(+v.lat).toFixed(6):''}"></div><div class="field"><label>Долгота</label><input id="tv24PointLon" type="number" step="0.000001" value="${Number.isFinite(+v.lon)?(+v.lon).toFixed(6):''}"></div><div class="field full"><label>Комментарий</label><textarea id="tv24PointNote" placeholder="Выход, парковка, ориентир">${esc(v.note)}</textarea></div><div class="field full"><div id="tv24PointPicker" class="tv24-point-picker"></div><small class="tv24-field-help">Кликни по карте или перетащи метку. Для городской навигации после сохранения можно открыть точку в Яндекс Картах.</small></div></div>`,layer=>{const obj={title:layer.querySelector('#tv24PointTitle').value.trim(),time:layer.querySelector('#tv24PointTime').value,lat:+layer.querySelector('#tv24PointLat').value,lon:+layer.querySelector('#tv24PointLon').value,note:layer.querySelector('#tv24PointNote').value.trim()};if(!obj.title){toast('Укажи название точки');return false}if(!Number.isFinite(obj.lat)||!Number.isFinite(obj.lon)){toast('Укажи точку на карте или координаты');return false}onSave(obj)});setTimeout(()=>mountPointPickerV24(v),40)}
function mountPointPickerV24(v){const el=document.getElementById('tv24PointPicker');if(!el||!window.L)return;let lat=Number.isFinite(+v.lat)?+v.lat:(hasCoordV24(tv24().arrival)?+tv24().arrival.lat:55.75),lon=Number.isFinite(+v.lon)?+v.lon:(hasCoordV24(tv24().arrival)?+tv24().arrival.lon:37.62);const m=L.map(el,{zoomControl:true,attributionControl:false}).setView([lat,lon],Number.isFinite(+v.lat)?15:11);let spec;try{spec=tileSpecStudioV21('city')}catch(e){spec={url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',opts:{maxZoom:19}}}L.tileLayer(spec.url,spec.opts).addTo(m);const marker=L.marker([lat,lon],{draggable:true}).addTo(m);const set=ll=>{marker.setLatLng(ll);const a=document.getElementById('tv24PointLat'),o=document.getElementById('tv24PointLon');if(a)a.value=ll.lat.toFixed(6);if(o)o.value=ll.lng.toFixed(6)};m.on('click',e=>set(e.latlng));marker.on('dragend',e=>set(e.target.getLatLng()));setTimeout(()=>m.invalidateSize(false),100)}
function arrivalModalV24(){pointModalV24({title:'Место прибытия мероприятия',value:tv24().arrival,kind:'arrival',onSave:o=>{tv24().arrival={...tv24().arrival,...o};transportSaveV24('Место мероприятия обновлено')}})}
function stopModalV24(r,stop=null){pointModalV24({title:stop?`Редактировать · ${stopKindV24(dir)}`:`Добавить · ${stopKindV24(dir)}`,value:stop||{},kind:'stop',onSave:o=>{if(stop)Object.assign(stop,o);else(r.stops||(r.stops=[])).push({id:`stop_${Date.now()}`,...o});transportSaveV24(stop?'Точка обновлена':'Точка добавлена')}})}
function requestModalV24(r){if(transportRequestV24())return toast('Сначала откажись от текущей заявки или места');const stops=(r.stops||[]);if(!stops.length)return toast('Водитель ещё не указал точку посадки');openModal('Попроситься в машину',`<div class="tv24-request-choice"><p>Выбери, где ${dir==='there'?'тебя забрать':'тебя высадить'}:</p>${stops.map((s,i)=>`<label><input type="radio" name="tv24Pickup" value="${s.id}" ${i===0?'checked':''}><span><b>${esc(s.title)}</b><small>${s.time?esc(s.time)+' · ':''}${esc(fmtCoordV24(s.lat,s.lon))}</small></span></label>`).join('')}</div>`,layer=>{if(transportFreeV24(r)<=0){toast('Свободных мест уже нет');return false}const pickupId=layer.querySelector('[name="tv24Pickup"]:checked')?.value;if(!pickupId){toast('Выбери точку');return false}const q={id:`req_${Date.now()}`,pid:S.current,pickupId,status:'pending',createdAt:Date.now()};(r.requests||(r.requests=[])).push(q);tv24().choices[dir][S.current]={mode:'request',rideId:r.id,requestId:q.id,pickupId};transportSaveV24('Заявка отправлена водителю')})}
function findRequestByIdV24(id,d=dir){for(const r of tv24().rides[d]){const q=(r.requests||[]).find(x=>x.id===id);if(q)return {r,q}}return null}
function approveRequestV24(rid,qid){const r=transportRideV24(rid);if(!r||r.driver!==S.current)return;const q=(r.requests||[]).find(x=>x.id===qid);if(!q||q.status!=='pending')return;if(transportFreeV24(r)<=0)return toast('Свободных мест больше нет');const other=transportRequestV24(q.pid,dir);if(other&&(other.ride.id!==r.id||other.request.id!==q.id))return toast('У пассажира уже есть другой активный вариант');q.status='approved';if(!r.passengers.includes(q.pid))r.passengers.push(q.pid);tv24().choices[dir][q.pid]={mode:'ride',rideId:r.id,requestId:q.id,pickupId:q.pickupId};transportSaveV24(`${pn(q.pid)} подтверждён`)}
function declineRequestV24(rid,qid){const r=transportRideV24(rid);if(!r||r.driver!==S.current)return;const q=(r.requests||[]).find(x=>x.id===qid);if(!q)return;q.status='declined';r.passengers=(r.passengers||[]).filter(pid=>pid!==q.pid);tv24().choices[dir][q.pid]={mode:'unset'};transportSaveV24('Заявка отклонена')}
function cancelRequestV24(qid){const x=findRequestByIdV24(qid);if(!x||x.q.pid!==S.current)return;x.q.status='cancelled';x.r.passengers=(x.r.passengers||[]).filter(pid=>pid!==S.current);tv24().choices[dir][S.current]={mode:'unset'};transportSaveV24('Транспорт освобождён')}
function setSelfV24(){const active=transportRequestV24();if(active)return toast('Сначала откажись от текущей заявки или места');if(transportDriverRideV24())return toast('Сначала удали свой рейс');tv24().choices[dir][S.current]={mode:'self'};transportSaveV24('Отмечено: самостоятельно')}
function unsetSelfV24(){if(transportChoiceV24().mode==='self'){tv24().choices[dir][S.current]={mode:'unset'};transportSaveV24()}}
function copyRideBackV24(rid){const src=transportRideV24(rid,'there');if(!src||src.driver!==S.current)return;const existing=transportDriverRideV24(S.current,'back');if(existing)return toast('Обратный рейс уже существует');if(!confirm('Скопировать машину, пассажиров и точки в обратном порядке? Время можно будет изменить.'))return;const stops=[...(src.stops||[])].reverse().map(s=>({...s,id:`back_stop_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,time:''}));const back={id:`ride_back_${Date.now()}`,driver:src.driver,seats:src.seats,vehicle:src.vehicle,color:src.color,plate:src.plate,comment:src.comment,stops,passengers:[],requests:[]};tv24().rides.back.push(back);tv24().choices.back[src.driver]={mode:'driver',rideId:back.id};let copied=0,skipped=0;(src.passengers||[]).forEach(pid=>{const c=tv24().choices.back[pid]||{mode:'unset'};if(['ride','request','driver'].includes(c.mode)){skipped++;return}const origReq=(src.requests||[]).find(q=>q.pid===pid&&q.status==='approved'),origIndex=(src.stops||[]).findIndex(s=>s.id===origReq?.pickupId),newIndex=origIndex<0?0:stops.length-1-origIndex,q={id:`back_req_${Date.now()}_${pid}`,pid,pickupId:stops[newIndex]?.id||'',status:'approved',createdAt:Date.now()};back.requests.push(q);back.passengers.push(pid);tv24().choices.back[pid]={mode:'ride',rideId:back.id,requestId:q.id,pickupId:q.pickupId};copied++});transportSaveV24(`Обратный рейс создан · пассажиров ${copied}${skipped?`, пропущено ${skipped}`:''}`)}

function mountTransportMapV24(){const el=document.getElementById('transportMapV24');if(!el||!window.L)return;try{transportMapV24?.remove()}catch(e){}transportMapV24=L.map(el,{zoomControl:true,attributionControl:true,scrollWheelZoom:true});let spec;try{spec=tileSpecStudioV21('city')}catch(e){spec={url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',opts:{maxZoom:19,attribution:'© OpenStreetMap contributors'}}}L.tileLayer(spec.url,spec.opts).addTo(transportMapV24);const pts=[],a=tv24().arrival;if(hasCoordV24(a)){const m=L.marker([a.lat,a.lon],{icon:L.divIcon({className:'',html:'<span class="tv24-map-arrival">★</span>',iconSize:[30,30],iconAnchor:[15,15]})}).addTo(transportMapV24).bindTooltip(a.title);pts.push([a.lat,a.lon])}tv24().rides[dir].forEach((r,ri)=>{const line=[];(r.stops||[]).forEach((s,si)=>{if(!hasCoordV24(s))return;const m=L.marker([s.lat,s.lon],{icon:L.divIcon({className:'',html:`<span class="tv24-map-stop">${ri+1}.${si+1}</span>`,iconSize:[28,28],iconAnchor:[14,14]})}).addTo(transportMapV24).bindTooltip(`${pn(r.driver)} · ${s.title}`);pts.push([s.lat,s.lon]);line.push([s.lat,s.lon])});if(hasCoordV24(a)){if(dir==='there')line.push([a.lat,a.lon]);else line.unshift([a.lat,a.lon])}if(line.length>1)L.polyline(line,{weight:3,opacity:.6,dashArray:'6 7'}).addTo(transportMapV24)});if(pts.length)transportMapV24.fitBounds(pts,{padding:[28,28],maxZoom:14});else transportMapV24.setView([55.75,37.62],9);setTimeout(()=>transportMapV24?.invalidateSize(false),80)}

function bindTransportV24(){
  document.querySelectorAll('[data-tv24-dir]').forEach(b=>b.onclick=()=>{dir=b.dataset.tv24Dir;render()});
  document.getElementById('tv24ProfileEdit')?.addEventListener('click',transportProfileModalV24);document.getElementById('tv24CreateRide')?.addEventListener('click',()=>transportRideModalV24(null,dir));document.getElementById('tv24EditArrival')?.addEventListener('click',arrivalModalV24);
  document.querySelectorAll('[data-tv24-edit-ride]').forEach(b=>b.onclick=()=>transportRideModalV24(transportRideV24(b.dataset.tv24EditRide),dir));
  document.querySelectorAll('[data-tv24-add-stop]').forEach(b=>b.onclick=()=>stopModalV24(transportRideV24(b.dataset.tv24AddStop)));
  document.querySelectorAll('[data-tv24-edit-stop]').forEach(b=>b.onclick=()=>{const [rid,sid]=b.dataset.tv24EditStop.split(':');const r=transportRideV24(rid),s=r?.stops.find(x=>x.id===sid);if(r&&s)stopModalV24(r,s)});
  document.querySelectorAll('[data-tv24-request]').forEach(b=>b.onclick=()=>requestModalV24(transportRideV24(b.dataset.tv24Request)));
  document.querySelectorAll('[data-tv24-approve]').forEach(b=>b.onclick=()=>{const [r,q]=b.dataset.tv24Approve.split(':');approveRequestV24(r,q)});document.querySelectorAll('[data-tv24-decline]').forEach(b=>b.onclick=()=>{const [r,q]=b.dataset.tv24Decline.split(':');declineRequestV24(r,q)});
  document.querySelectorAll('[data-tv24-cancel-request]').forEach(b=>b.onclick=()=>cancelRequestV24(b.dataset.tv24CancelRequest));document.querySelectorAll('[data-tv24-self]').forEach(b=>b.onclick=setSelfV24);document.querySelectorAll('[data-tv24-unset-self]').forEach(b=>b.onclick=unsetSelfV24);
  document.querySelectorAll('[data-tv24-copy-back]').forEach(b=>b.onclick=()=>copyRideBackV24(b.dataset.tv24CopyBack));
  document.querySelectorAll('[data-tv24-yandex-ride]').forEach(b=>b.onclick=()=>openYandexRideV24(transportRideV24(b.dataset.tv24YandexRide),dir));
  document.querySelectorAll('[data-tv24-yandex-point]').forEach(b=>b.onclick=()=>{const a=tv24().arrival;if(hasCoordV24(a))window.open(yandexPointV24(a.lat,a.lon),'_blank','noopener')});
  document.querySelectorAll('[data-tv24-yandex-stop]').forEach(b=>b.onclick=()=>{const [rid,sid]=b.dataset.tv24YandexStop.split(':'),r=transportRideV24(rid),s=r?.stops.find(x=>x.id===sid);if(hasCoordV24(s))window.open(yandexPointV24(s.lat,s.lon),'_blank','noopener')});
  requestAnimationFrame(mountTransportMapV24);
}

ensureTransportV24();
const bindBeforeV24=bind;bind=function(){bindBeforeV24();if(tab==='transport')bindTransportV24()};
const buildV24=document.querySelector('.build-label');if(buildV24)buildV24.textContent='V18 · транспорт по заявкам · точки посадки';
render();
