import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await readFile(new URL('./workspace.js',import.meta.url),'utf8');
const S={current:'p1',participants:[{id:'p1',name:'Organizer'},{id:'p2',name:'Navigator'},{id:'p3',name:'Passenger'}],rolesV36:{roles:[{id:'lead',p:'p1',title:'Lead'},{id:'nav',p:'p2',title:'Navigator'},{id:'logistics',p:'',title:'Quartermaster'}],candidates:{}},transportV24:{rides:{there:[{id:'r1',driver:'p2',seats:2,stops:[{id:'s1',time:'07:30'}],requests:[{id:'q1',pid:'p3',pickupId:'s1',status:'approved',createdAt:1}],passengers:['p3']}],back:[]},choices:{there:{p2:{mode:'driver',rideId:'r1'},p3:{mode:'ride',rideId:'r1'}},back:{}}}};
const window={},document={querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null};
const api=new Function('window','document','S','render','beginEditV15','openStudioV21','transportSaveV24','tab','pageHead','esc','initials','pn','let editorModeV13=false;'+source+'\nreturn window.HikeWorkspace;')(window,document,S,()=>{},()=>{},()=>{},()=>{},'roles',()=>'',x=>String(x??''),x=>x.slice(0,2),pid=>S.participants.find(p=>p.id===pid)?.name||pid);
api.syncReturn();
assert.ok(S.transportV24.rides.back[0].passengers.includes('p3'));
assert.equal(S.transportV24.rides.back[0].stops[0].time,'');
S.transportV24.rides.there[0].requests[0].status='cancelled';api.syncReturn();
assert.equal(S.transportV24.rides.back[0].passengers.length,0);
assert.equal(S.transportV24.choices.back.p3.mode,'unset');
S.transportV24.choices.there.p3={mode:'self'};api.syncReturn();
assert.equal(S.transportV24.choices.back.p3.mode,'self');
S.current='p2';assert.ok(api.can('route')&&!api.can('food')&&!api.can('roles'));
S.rolesV36.roles.push({id:'medic',p:'p3'});S.current='p3';assert.ok(api.can('medical')&&!api.can('gear'));
S.rolesV36.roles.push({id:'cook',p:'p3',manageFood:true});assert.ok(api.can('food')&&!api.can('roles'));
window.HikePreviewV48={active:true,pid:'p2'};assert.ok(!api.can('route')&&!api.canAct());
window.HikePreviewV48=null;window.HikeSession={signed:true,approved:false,organizer:false};assert.ok(!api.can('medical')&&!api.canAct());
window.HikeSession=null;S.current='p1';assert.ok(api.rolesPage().includes('Предложить себя'));
S.transportV24.rides.back=[{id:'independent',driver:'p2',seats:1,stops:[],requests:[],passengers:[]}];
api.syncReturn();assert.equal(S.transportV24.rides.back[0].id,'independent');assert.equal(S.transportV24.rides.back[0].seats,1);
console.log('Workspace interaction tests passed. DOM rendering and authenticated cloud writes require browser integration tests.');
