(()=>{
const style=document.createElement('style');
style.textContent=`
.lead>summary{grid-template-columns:minmax(255px,1.75fr) minmax(190px,1.08fr) 92px 100px 100px 28px}
.summary-score.demand b{color:#294a67}.summary-score.sales b{color:#1f654d}.summary-score span,.summary-vacancies span{white-space:nowrap}
.summary-contact-line{margin-top:6px;font-size:11px;color:#69737d;display:flex;gap:7px;align-items:center;flex-wrap:wrap;line-height:1.35}.summary-contact-line a{color:#1f654d;text-decoration:none;max-width:230px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.summary-contact-line a:hover{text-decoration:underline}
.lead-kpis.v4{grid-template-columns:repeat(4,minmax(120px,1fr))}.industry-line{font-weight:700}.industry-line small{display:block;color:#69737d;font-weight:400;margin-top:3px}
.metric-help{position:relative;display:inline-flex;align-items:center;gap:4px;cursor:help;border-bottom:1px dotted #9aa4ac}.tip-q{display:inline-flex;width:14px;height:14px;border:1px solid #aeb7be;border-radius:50%;align-items:center;justify-content:center;font-size:9px;line-height:1;color:#68737c;font-weight:700}
.metric-help:after{content:attr(data-tip);position:absolute;z-index:80;right:0;bottom:calc(100% + 9px);width:330px;max-width:min(330px,80vw);background:#17212b;color:#fff;padding:10px 12px;font-size:12px;line-height:1.45;text-align:left;white-space:pre-line;box-shadow:0 8px 24px rgba(0,0,0,.18);opacity:0;pointer-events:none;transform:translateY(4px);transition:.12s}.metric-help:before{content:'';position:absolute;z-index:81;right:16px;bottom:calc(100% + 3px);border:6px solid transparent;border-top-color:#17212b;opacity:0;transition:.12s}.metric-help:hover:after,.metric-help:hover:before{opacity:1;transform:none}
.reason-list{margin:7px 0 0;padding-left:18px;font-size:13px}.reason-list li{margin:4px 0}.risk{background:#fff8e8;border:1px solid #ead7a6;padding:8px 10px;margin-top:8px;font-size:12px;color:#66501d}.quality-flag{background:#fff1f1;border:1px solid #e7c7c7;padding:8px 10px;margin:8px 0;font-size:12px;color:#762828}.feature-chip{font-size:11px;padding:4px 6px;background:#f3f7fb;border:1px solid #d8e3eb}.score-details{border:1px solid #e2e7ea;background:#fafbfc;margin-top:10px}.score-details>summary{cursor:pointer;padding:8px 10px;font-size:12px;font-weight:700}.score-breakdown{padding:0 10px 9px;font-size:12px;color:#4f5c66;line-height:1.55}.score-breakdown b{color:#26313b}.contact-detail{font-size:13px;line-height:1.7;margin-top:7px}.contact-detail a{color:#1f654d}.contact-row b{display:inline-block;min-width:70px}.data-note{font-size:12px;color:#69737d;line-height:1.5}.no-contacts{color:#8a939b;font-size:12px;margin-top:7px}
@media(max-width:1050px){.lead>summary{grid-template-columns:minmax(220px,1.5fr) minmax(150px,1fr) 78px 82px 82px 24px}.lead-kpis.v4{grid-template-columns:repeat(2,1fr)}}
@media(max-width:720px){.lead>summary{grid-template-columns:1fr auto auto}.summary-direction{grid-column:1/2}.summary-vacancies{display:none}.summary-score.demand{grid-column:2/3;grid-row:1/3}.summary-score.sales{grid-column:3/4;grid-row:1/3}.chev{display:none}.lead-kpis.v4{grid-template-columns:repeat(2,1fr)}.metric-help:after{right:-30px;width:280px}}
`;
document.head.appendChild(style);

function siteHost(href){try{return new URL(href,location.href).hostname.replace(/^www\./,'')}catch{return 'сайт'}}
function volumePts(n){if(n>=20)return 50;if(n>=13)return 44;if(n>=8)return 38;if(n>=5)return 30;if(n===4)return 23;if(n===3)return 18;if(n===2)return 13;if(n===1)return 8;return 0}
function demandBreakdown(l){const m=l.metrics||{},jobs=l.jobs||[],n=Number(m.relevantJobs||jobs.length||0),new7=Number(m.newJobs7d||0),roles=(m.roleSummary||[]).length,f=m.jobFeatures||{};const volume=volumePts(n),fresh=Math.min(20,Math.round((n?new7/n:0)*12+Math.min(new7,8))),diversity=Math.min(12,roles*3);let operations=0;if(Number(f.noExperience||0)>0)operations+=3;if(Number(f.shiftWork||0)>0)operations+=3;if(Number(f.housing||0)>0)operations+=3;if(Number(f.transport||0)>0)operations+=3;if(Number(f.meals||0)>0)operations+=1;if(Number(f.workwear||0)>0)operations+=1;if(Number(f.medical||0)>0)operations+=1;if(Number(f.referral||0)>0)operations+=2;if(f.multipleLocations)operations+=2;operations=Math.min(18,operations);return{n,new7,roles,volume,fresh,diversity,operations,total:Number(m.demandScore||0)}}
function salesBreakdown(l,demand){const m=l.metrics||{},signals=l.signals||[],providers=l.providers||m.providers||[];const demandPart=demand*.55,staff=Number(m.staffScore||0),industry=Number(m.businessFit??m.industryFit??0),hiring=Number(m.totalVacancyScore||0),multi=providers.length>=2?5:0,surge=signals.some(x=>x.type==='JOB_SURGE')?5:0,publicPenalty=(m.publicSector===true||m.publicSector==='true')?-15:0;return{demandPart,staff,industry,hiring,multi,surge,publicPenalty,total:Number(m.salesPriority??m.salesPriorityScore??l.score??0)}}
function targetTip(l){const m=l.metrics||{},n=Number(m.relevantJobs||(l.jobs||[]).length||0);return `Целевых вакансий: ${n}\n\nЭто уникальные вакансии, которые Scout отнёс к нашим целевым ролям: склад, производство, клининг, контакт-центр и т. п.\n\nВажно: это число вакансий, а не гарантированное количество требуемых людей — одна вакансия может предполагать несколько сотрудников.`}
function demandTip(l){const p=demandBreakdown(l);return `Потребность: ${p.total}/100\n\nПоказывает силу кадровой потребности, а не вероятность купить аутсорс.\n\nТекущая раскладка:\n• объём целевых вакансий: +${p.volume}\n• свежесть найма: +${p.fresh}\n• разнообразие целевых ролей: +${p.diversity}\n• признаки массовой операционки: +${p.operations}\n\nИтог ограничивается 100 баллами.`}
function salesTip(l){const demand=Number(l.metrics?.demandScore||0),p=salesBreakdown(l,demand),fmt=x=>Number.isInteger(x)?String(x):x.toFixed(1);return `Приоритет продаж: ${p.total}/100\n\nПоказывает, насколько компании стоит уделить время менеджера именно как потенциальному заказчику аутсорса.\n\nТекущая раскладка:\n• 55% от кадровой потребности: +${fmt(p.demandPart)}\n• размер компании: +${p.staff}\n• соответствие отрасли: +${p.industry}\n• общий объём найма: +${p.hiring}${p.multi?`\n• подтверждение несколькими источниками: +${p.multi}`:''}${p.surge?`\n• всплеск найма: +${p.surge}`:''}${p.publicPenalty?`\n• ограничение госсектора: ${p.publicPenalty}`:''}\n\nЭто приоритет для прозвона, а не вероятность сделки.`}
function tipLabel(label,tip){return `<span class="metric-help" data-tip="${esc(tip)}">${esc(label)} <span class="tip-q">?</span></span>`}
function compactContacts(c){const x=[];if(c.site)x.push(`<a onclick="event.stopPropagation()" href="${esc(c.site)}" target="_blank" rel="noopener" title="${esc(c.site)}">${esc(siteHost(c.site))}</a>`);if(c.public_email)x.push(`<a onclick="event.stopPropagation()" href="mailto:${esc(c.public_email)}">${esc(c.public_email)}</a>`);if(c.public_phone)x.push(`<span>${esc(c.public_phone)}</span>`);return x.length?`<div class="summary-contact-line">${x.join('<span>·</span>')}</div>`:''}
function contactBlock(c){const rows=[];if(c.site)rows.push(`<div class="contact-row"><b>Сайт</b> <a href="${esc(c.site)}" target="_blank" rel="noopener">${esc(c.site)}</a></div>`);if(c.public_phone)rows.push(`<div class="contact-row"><b>Телефон</b> ${esc(c.public_phone)}</div>`);if(c.public_email)rows.push(`<div class="contact-row"><b>Email</b> <a href="mailto:${esc(c.public_email)}">${esc(c.public_email)}</a></div>`);return rows.length?`<div class="contact-detail">${rows.join('')}</div>`:'<div class="no-contacts">Публичные контакты пока не найдены.</div>'}
function workforceLabels(m){if(Array.isArray(m.workforceSignals)&&m.workforceSignals.length)return m.workforceSignals;const f=m.jobFeatures||{},x=[];if(Number(f.noExperience||0)>0)x.push('Без опыта / обучение');if(Number(f.shiftWork||0)>0)x.push('Сменный / интенсивный график');if(Number(f.housing||0)>0)x.push('Проживание');if(Number(f.transport||0)>0)x.push('Развозка');if(Number(f.meals||0)>0)x.push('Питание');if(Number(f.workwear||0)>0)x.push('Спецодежда');if(Number(f.medical||0)>0)x.push('Медосмотр / медкнижка');if(Number(f.referral||0)>0)x.push('Реферальная программа');if(f.multipleLocations)x.push('Несколько локаций');return x}
function fallbackReasons(m,relevant,fresh,industry,staff,allVac){const x=[];if(relevant>=8)x.push(`Массовая текущая потребность: ${relevant} целевых вакансий`);else if(relevant>=3)x.push(`Несколько целевых вакансий одновременно: ${relevant}`);if(fresh>=5)x.push(`Высокая свежесть найма: ${fresh} вакансий за 7 дней`);if(String(staff).includes('более 5000'))x.push('Крупный работодатель: более 5000 сотрудников');if(allVac>=100)x.push(`Высокая общая активность найма: ${allVac.toLocaleString('ru-RU')} вакансий`);if(Number(m.businessFit??m.industryFit??0)>=13)x.push(`Профиль бизнеса подходит под массовый аутсорс: ${industry}`);return x}
function breakdownHtml(l){const d=demandBreakdown(l),s=salesBreakdown(l,d.total),fmt=x=>Number.isInteger(x)?String(x):x.toFixed(1);return `<details class="score-details"><summary>Как рассчитаны баллы</summary><div class="score-breakdown"><b>Потребность ${d.total}/100:</b> объём +${d.volume}, свежесть +${d.fresh}, роли +${d.diversity}, массовые условия +${d.operations}.<br><b>Приоритет ${s.total}/100:</b> потребность × 55% = +${fmt(s.demandPart)}, размер +${s.staff}, отрасль +${s.industry}, общий найм +${s.hiring}${s.multi?`, несколько источников +${s.multi}`:''}${s.surge?`, всплеск +${s.surge}`:''}${s.publicPenalty?`, госсектор ${s.publicPenalty}`:''}.</div></details>`}

leadHtml=function(l){
 const c=l.company||{},raw=c.raw||{},m=l.metrics||{},roles=m.roleSummary||[],signals=l.signals||[],jobs=l.jobs||[],prov=l.providers||m.providers||[];
 const staff=m.staffCount||raw.staffCount||'нет данных',allVac=Number(m.totalVacancies||raw.totalVacancies||0),direction=demandDirection(roles),fresh=Number(m.newJobs7d||0),relevant=Number(m.relevantJobs||jobs.length||0),demand=Number(m.demandScore||0),sales=Number(m.salesPriority??m.salesPriorityScore??l.score??0),industry=m.businessDirectionLabel||m.industry||l.explanation?.industry||'Отрасль не определена';
 const wf=workforceLabels(m),flags=Array.isArray(m.dataQualityFlags)?m.dataQualityFlags:(Array.isArray(m.dataQualityWarnings)?m.dataQualityWarnings:[]),reasons=(Array.isArray(m.salesReasons)&&m.salesReasons.length?m.salesReasons:fallbackReasons(m,relevant,fresh,industry,staff,allVac)),risks=Array.isArray(m.salesRisks)?m.salesRisks:[];
 if(relevant<=1&&!risks.length)risks.push('Текущая целевая потребность подтверждена только одной вакансией.');
 return `<details class="lead ${esc(l.priority)}"><summary>
  <div><div class="company-name">${esc(c.name||l.company_id)}</div><div class="summary-sub"><span class="status-pill ${esc(l.status||'new')}">${esc(statusLabel(l.status))}</span><span class="priority-pill">${esc(priorityLabel(l.priority))}</span>${c.inn?'<span class="muted">ИНН '+esc(c.inn)+'</span>':''}</div>${compactContacts(c)}</div>
  <div class="summary-direction industry-line">${esc(industry)}<small>${esc(direction)} · ${esc(staff)}</small></div>
  <div class="summary-vacancies"><b>${relevant}</b><span>${tipLabel('целевых',targetTip(l))}</span></div>
  <div class="summary-score demand"><b>${demand}</b><span>${tipLabel('Потребность',demandTip(l))}</span></div>
  <div class="summary-score sales"><b>${sales}</b><span>${tipLabel('Приоритет',salesTip(l))}</span></div><div class="chev">⌄</div>
 </summary><div class="lead-body">
  ${flags.length?'<div class="quality-flag"><b>Требует проверки данных:</b> '+flags.map(esc).join(' · ')+'</div>':''}
  <div class="lead-kpis v4"><div class="lead-kpi"><span>Свежих за 7 дней</span><b>${fresh}</b></div><div class="lead-kpi"><span>Размер компании</span><b>${esc(staff)}</b></div><div class="lead-kpi"><span>Всего вакансий работодателя</span><b>${allVac?allVac.toLocaleString('ru-RU'):'нет данных'}</b></div><div class="lead-kpi"><span>Последний сигнал</span><b>${esc(fmtDateTime(l.lastSignalAt)||'—')}</b></div></div>
  <div class="lead-columns"><div>
   <div class="subsection"><h4>Почему стоит проверить компанию</h4>${reasons.length?'<ul class="reason-list">'+reasons.map(x=>'<li>'+esc(x)+'</li>').join(''):'<div class="muted">Сильных коммерческих факторов пока недостаточно.</div>'}${breakdownHtml(l)}</div>
   <div class="subsection"><h4>Признаки массового найма</h4><div class="chips">${signals.length?signals.map(s=>'<span class="chip">'+esc(s.type)+' · '+esc(s.evidence)+'</span>').join(''):'<span class="muted">Резких динамических сигналов пока нет</span>'}</div>${wf.length?'<div class="chips">'+wf.map(x=>'<span class="feature-chip">'+esc(x)+'</span>').join(''):'<div class="muted">Дополнительные признаки пока не обнаружены.</div>'}</div>
  </div><div>
   <div class="subsection"><h4>Компания и контакты</h4><div class="fact"><b>Отрасль:</b> ${esc(industry)}</div><div class="fact"><b>Направление потребности:</b> ${esc(direction)}</div><div class="fact"><b>Источники:</b> ${esc(prov.join(', ')||'не указаны')}</div><div class="fact"><b>Основные роли:</b> ${esc(roles.slice(0,6).map(r=>r.label+' — '+r.count).join(', ')||'—')}</div>${contactBlock(c)}</div>
   <div class="subsection"><h4>Ограничения и качество сигнала</h4>${risks.length?risks.map(x=>'<div class="risk">'+esc(x)+'</div>').join(''):'<div class="data-note">Критических ограничений по текущим данным не обнаружено.</div>'}<div class="data-note" style="margin-top:8px">${esc(l.explanation?.caveat||'Вакансии подтверждают найм, но сами по себе не подтверждают готовность компании использовать аутсорс.')}</div></div>
  </div></div>
  <div class="jobs-title"><h4>Вакансии (${jobs.length})</h4><span class="muted">Сгруппированы по профессиям</span></div>${jobs.length?vacancyGroups(jobs,roles):'<div class="muted">Вакансий нет</div>'}
  <div class="actions">${[['working','В работу'],['need','Потребность есть'],['proposal','Запросили КП'],['later','Вернуться позже'],['no_need','Нет потребности'],['outsourcing_no','Не используют аутсорс'],['bad_signal','Неверный сигнал']].map(x=>'<button onclick="event.preventDefault();event.stopPropagation();setStatus(\''+encodeURIComponent(l.company_id)+'\',\''+x[0]+'\')">'+x[1]+'</button>').join('')}</div>
 </div></details>`
};
})();
