/* Scout main UI refinements v1 */
(()=>{
const style=document.createElement('style');
style.textContent=`
.sources-compact-panel{padding:0!important;overflow:hidden}.sources-compact-head{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:13px 16px}.sources-compact-title{font-size:15px;font-weight:800}.sources-compact-sub{font-size:11px;color:#69737d;margin-top:3px}.sources-compact-actions{display:flex;align-items:center;gap:12px;white-space:nowrap}.sources-compact-actions a{color:#1f654d;font-size:12px}.sources-tech{border-top:1px solid #e3e8eb}.sources-tech>summary{cursor:pointer;list-style:none;padding:9px 16px;background:#fafbfc;font-size:12px;font-weight:700;color:#56616c}.sources-tech>summary::-webkit-details-marker{display:none}.sources-tech>summary:before{content:'›';display:inline-block;margin-right:7px;transition:.15s}.sources-tech[open]>summary:before{transform:rotate(90deg)}.sources-tech-body{padding:12px 16px 16px}.sources-tech-note{font-size:11px;color:#69737d;margin-bottom:10px}.sources-state{font-size:11px;padding:4px 7px;border:1px solid #d8e0e4;background:#f5f7f8;color:#56616c}.sources-state.ok{background:#eaf5ee;border-color:#cbe1d3;color:#24593e}@media(max-width:700px){.sources-compact-head{display:block}.sources-compact-actions{margin-top:8px;white-space:normal}}
`;
document.head.appendChild(style);
function providerPanel(){return [...document.querySelectorAll('#app > section.panel')].find(p=>p.querySelector('h2')?.textContent.trim()==='Источники данных')||null}
function activeNames(grid){return [...grid.querySelectorAll('.provider')].filter(p=>p.querySelector('input[type="checkbox"]')?.checked).map(p=>p.querySelector('.provider-name')?.textContent?.trim()).filter(Boolean)}
function refreshState(panel){const grid=panel?.querySelector('#providers'),state=panel?.querySelector('.sources-state');if(!grid||!state)return;const names=activeNames(grid);state.textContent=names.length?`Активно: ${names.join(', ')}`:'Нет активных источников';state.classList.toggle('ok',names.length>0)}
function compactSources(){const panel=providerPanel();if(!panel||panel.dataset.compactUi==='1')return false;const grid=panel.querySelector('#providers');if(!grid)return false;panel.dataset.compactUi='1';panel.classList.add('sources-compact-panel');const oldTitle=panel.querySelector('.section-title');if(oldTitle)oldTitle.remove();const head=document.createElement('div');head.className='sources-compact-head';head.innerHTML=`<div><div class="sources-compact-title">Источники данных</div><div class="sources-compact-sub">Ключи и диагностика скрыты с рабочего экрана — они нужны только при настройке.</div></div><div class="sources-compact-actions"><span class="sources-state">Проверяем…</span><a href="providers.html">Настройки источников</a></div>`;panel.insertBefore(head,panel.firstChild);const details=document.createElement('details');details.className='sources-tech';const summary=document.createElement('summary');summary.textContent='Показать технический блок на этой странице';const body=document.createElement('div');body.className='sources-tech-body';body.innerHTML='<div class="sources-tech-note">Здесь остаются API-ключи, проверка соединения и включение/отключение провайдеров. Для обычной работы этот раздел можно не открывать.</div>';grid.parentNode.insertBefore(details,grid);details.appendChild(summary);details.appendChild(body);body.appendChild(grid);grid.style.marginTop='0';refreshState(panel);const obs=new MutationObserver(()=>refreshState(panel));obs.observe(grid,{subtree:true,childList:true,attributes:true,attributeFilter:['checked']});grid.addEventListener('change',()=>setTimeout(()=>refreshState(panel),0));return true}
function placeMonitoring(){if(window.ScoutMonitoring){window.ScoutMonitoring.refresh?.();return}if(document.querySelector('script[data-main-monitoring-v2]'))return;const s=document.createElement('script');s.dataset.mainMonitoringV2='1';s.src='monitoring-v1.js?v=2';s.onload=()=>window.ScoutMonitoring?.refresh?.();s.onerror=()=>console.error('SCOUT_MONITORING_LOAD_FAILED');document.body.appendChild(s)}
function run(){compactSources();placeMonitoring()}
const obs=new MutationObserver(()=>run());obs.observe(document.body,{subtree:true,childList:true});requestAnimationFrame(run);setTimeout(run,150);setTimeout(run,700);
window.ScoutMainUI={refresh:run};
})();
