/* Scout automatic monitoring v1 */
(()=>{
const style=document.createElement('style');
style.textContent=`
.monitor-panel{background:#fff;border:1px solid #dfe4e8;padding:16px;margin-bottom:15px}.monitor-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.monitor-head h2{margin:0;font-size:20px}.monitor-state{font-size:11px;padding:4px 7px;border:1px solid #cbe1d3;background:#eaf5ee;color:#24593e}.monitor-state.off{border-color:#e0e5e9;background:#f3f5f6;color:#69737d}.monitor-grid{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:8px;margin-top:13px}.monitor-card{border:1px solid #e3e8eb;background:#fafbfc;padding:10px}.monitor-card span{display:block;font-size:10px;color:#69737d;margin-bottom:4px}.monitor-card b{font-size:13px;line-height:1.3}.monitor-foot{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:10px;font-size:11px;color:#69737d}.monitor-run-ok{color:#24593e}.monitor-run-bad{color:#762828}@media(max-width:900px){.monitor-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.monitor-grid{grid-template-columns:1fr}.monitor-head,.monitor-foot{display:block}.monitor-foot>*{margin-top:6px}}
`;
document.head.appendChild(style);
const e=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){if(!v)return'—';try{return new Date(v).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return String(v)}}
function depth(n){return Number(n)===1?'Базовая':Number(n)===2?'Расширенная':'Максимальная'}
function shell(){return `<section class="monitor-panel" id="auto-monitor"><div class="monitor-head"><div><h2>Автоматический мониторинг</h2><div class="muted" style="margin-top:4px">Scout сам обновляет рынок и накапливает историю изменений.</div></div><span class="monitor-state">загрузка…</span></div><div class="monitor-grid"><div class="monitor-card"><span>Регион</span><b data-m="region">—</b></div><div class="monitor-card"><span>Расписание</span><b data-m="schedule">—</b></div><div class="monitor-card"><span>Следующий запуск</span><b data-m="next">—</b></div><div class="monitor-card"><span>Последний автозапуск</span><b data-m="last">—</b></div><div class="monitor-card"><span>Последний результат</span><b data-m="result">—</b></div></div><div class="monitor-foot"><span data-m="detail">Загрузка состояния…</span><span>История компаний сохраняется в Supabase</span></div></section>`}
function place(){if(document.getElementById('auto-monitor'))return true;const app=document.getElementById('app');if(!app)return false;const panels=[...app.children].filter(x=>x.tagName==='SECTION');if(!panels.length)return false;panels[0].insertAdjacentHTML('afterend',shell());return true}
async function load(){if(!place())return;const root=document.getElementById('auto-monitor');if(!root||root.dataset.loading==='1')return;root.dataset.loading='1';try{const r=await af('/api/monitoring');const d=await safeJson(r);if(!r.ok)throw Error(d.error||'Не удалось загрузить мониторинг');const c=d.config||{},last=d.lastRun||{},state=root.querySelector('.monitor-state');state.textContent=c.enabled?'Включён':'Выключен';state.classList.toggle('off',!c.enabled);root.querySelector('[data-m="region"]').textContent=c.regionLabel||'—';root.querySelector('[data-m="schedule"]').textContent=c.enabled?`Ежедневно ${c.localTime||'06:30'} МСК`:'Отключён';root.querySelector('[data-m="next"]').textContent=c.enabled?fmt(d.nextRunAt):'—';root.querySelector('[data-m="last"]').textContent=last.started_at?fmt(last.started_at):'ещё не было';const ok=last?.params?.status==='finished'&&!((last.errors||[]).length);const result=root.querySelector('[data-m="result"]');result.textContent=last.started_at?`${Number(last.jobs_fetched||0)} вакансий · ${Number(last.companies_processed||0)} компаний`:'—';result.className=last.started_at?(ok?'monitor-run-ok':'monitor-run-bad'):'';root.querySelector('[data-m="detail"]').textContent=last.started_at?`${ok?'Последний запуск завершён без ошибок':'Есть ошибки в последнем запуске'} · глубина: ${depth(c.maxPages)}`:`Глубина: ${depth(c.maxPages)}`;root.dataset.loaded='1'}catch(err){root.querySelector('.monitor-state').textContent='Ошибка';root.querySelector('.monitor-state').classList.add('off');root.querySelector('[data-m="detail"]').textContent=err.message||String(err)}finally{delete root.dataset.loading}}
function schedule(){requestAnimationFrame(()=>{place();load()});setTimeout(()=>{place();load()},120)}
const original=window.boot;if(typeof original==='function')window.boot=async function(){const r=await original.apply(this,arguments);schedule();return r};
const obs=new MutationObserver(()=>{if(document.getElementById('app')&&!document.getElementById('auto-monitor'))schedule()});obs.observe(document.body,{childList:true,subtree:true});
window.ScoutMonitoring={refresh(){const r=document.getElementById('auto-monitor');if(r)delete r.dataset.loaded;load()}};
schedule();
})();
